// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/drive_post_fast.comp - do not edit.
// glsl-sha256: 14285b778220d9d8ab6f258b5d21bb56aaa05d27eaf56341f58776aca57f736d
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(512u, 1u, 1u);

ByteAddressBuffer _81 : register(t0);
ByteAddressBuffer _198 : register(t1);
RWByteAddressBuffer _353 : register(u3);
ByteAddressBuffer _375 : register(t4);
RWByteAddressBuffer _432 : register(u2);
ByteAddressBuffer _507 : register(t5);
RWByteAddressBuffer _523 : register(u6);
cbuffer PostParams
{
    int P_supply : packoffset(c0);
    int P_spot : packoffset(c0.y);
    float P_k1 : packoffset(c0.z);
    int P_persistence : packoffset(c0.w);
    int P_newSlot : packoffset(c1);
    int P_depth : packoffset(c1.y);
    int P_rows : packoffset(c1.z);
    int P_rx : packoffset(c1.w);
};


static uint3 gl_WorkGroupID;
static uint3 gl_LocalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_WorkGroupID : SV_GroupID;
    uint3 gl_LocalInvocationID : SV_GroupThreadID;
};

groupshared float rowv[1536];

uint spvPackHalf2x16(float2 value)
{
    uint2 Packed = f32tof16(value);
    return Packed.x | (Packed.y << 16);
}

float2 spvUnpackHalf2x16(uint value)
{
    return f16tof32(uint2(value & 0xffff, value >> 16));
}

float3 postResample(int py, int x, float2 k)
{
    if ((x < 0) || (x >= 512))
    {
        return 0.0f.xxx;
    }
    if (P_supply == 0)
    {
        return asfloat(_81.Load4(((py * 512) + x) * 16 + 0)).xyz;
    }
    float sx = (256.0f + (((float(x) + 0.5f) - 256.0f) / k.x)) - 0.5f;
    int x0 = int(floor(sx));
    float t = sx - float(x0);
    float3 _120;
    if ((x0 >= 0) && (x0 < 512))
    {
        _120 = asfloat(_81.Load4(((py * 512) + x0) * 16 + 0)).xyz;
    }
    else
    {
        _120 = 0.0f.xxx;
    }
    float3 a = _120;
    bool _136 = (x0 + 1) >= 0;
    bool _142;
    if (_136)
    {
        _142 = (x0 + 1) < 512;
    }
    else
    {
        _142 = _136;
    }
    float3 _143;
    if (_142)
    {
        _143 = asfloat(_81.Load4((((py * 512) + x0) + 1) * 16 + 0)).xyz;
    }
    else
    {
        _143 = 0.0f.xxx;
    }
    float3 b = _143;
    return ((a * (1.0f - t)) + (b * t)) * k.y;
}

uint2 packH4(float4 v)
{
    return uint2(spvPackHalf2x16(v.xy), spvPackHalf2x16(v.zw));
}

float4 unpackH4(uint2 h)
{
    return float4(spvUnpackHalf2x16(h.x), spvUnpackHalf2x16(h.y));
}

void comp_main()
{
    int px = int(gl_LocalInvocationID.x);
    int py = int(gl_WorkGroupID.x);
    int i = (py * 512) + px;
    float2 _192;
    if (P_supply != 0)
    {
        _192 = asfloat(_198.Load4(py * 16 + 0)).xy;
    }
    else
    {
        _192 = 1.0f.xx;
    }
    float2 k = _192;
    float3 v;
    if (P_spot != 0)
    {
        v = 0.0f.xxx;
        float3 _282;
        float3 _289;
        for (int d = -3; d <= 3; d++)
        {
            int j = px - d;
            if ((j < 0) || (j >= 512))
            {
                continue;
            }
            int param = py;
            int param_1 = j;
            float2 param_2 = k;
            float3 u = postResample(param, param_1, param_2);
            float3 sg = sqrt(max(u, 0.0f.xxx)) * P_k1;
            float3 e1 = exp((-0.5f).xxx / max(sg * sg, 1.0000000031710768509710513471353e-30f.xxx));
            float3 e2 = e1 * e1;
            e2 *= e2;
            float3 e3 = (e2 * e2) * e1;
            int ad = abs(d);
            if (ad == 0)
            {
                _282 = 1.0f.xxx;
            }
            else
            {
                if (ad == 1)
                {
                    _289 = e1;
                }
                else
                {
                    bool3 _299 = (ad == 2).xxx;
                    _289 = float3(_299.x ? e2.x : e3.x, _299.y ? e2.y : e3.y, _299.z ? e2.z : e3.z);
                }
                _282 = _289;
            }
            float3 ek = _282;
            float3 wk = ek / (1.0f.xxx + (((e1 + e2) + e3) * 2.0f));
            float3 _319 = float(ad == 0).xxx;
            bool3 _323 = bool3(sg.x <= 9.9999999747524270787835121154785e-07f.xxx.x, sg.y <= 9.9999999747524270787835121154785e-07f.xxx.y, sg.z <= 9.9999999747524270787835121154785e-07f.xxx.z);
            wk = float3(_323.x ? _319.x : wk.x, _323.y ? _319.y : wk.y, _323.z ? _319.z : wk.z);
            v += (u * wk);
        }
    }
    else
    {
        int param_3 = py;
        int param_4 = px;
        float2 param_5 = k;
        v = postResample(param_3, param_4, param_5);
    }
    if (P_persistence != 0)
    {
        int area = 512 * P_rows;
        float4 param_6 = float4(v, 1.0f);
        _353.Store2(((P_newSlot * area) + i) * 8 + 0, packH4(param_6));
        float3 eff = v * asfloat(_375.Load4(P_newSlot * 16 + 0)).xyz;
        for (int s = 0; s < P_depth; s++)
        {
            float3 q = asfloat(_375.Load4(s * 16 + 0)).xyz;
            bool _401 = s == P_newSlot;
            bool _408;
            if (!_401)
            {
                _408 = all(bool3(q.x == 0.0f.xxx.x, q.y == 0.0f.xxx.y, q.z == 0.0f.xxx.z));
            }
            else
            {
                _408 = _401;
            }
            if (_408)
            {
                continue;
            }
            uint2 param_7 = _353.Load2(((s * area) + i) * 8 + 0);
            eff += (unpackH4(param_7).xyz * q);
        }
        v = eff;
    }
    _432.Store4(i * 16 + 0, asuint(float4(v, 1.0f)));
    rowv[px] = v.x;
    rowv[512 + px] = v.y;
    rowv[1024 + px] = v.z;
    GroupMemoryBarrierWithGroupSync();
    float3 s_1 = 0.0f.xxx;
    int lo = max((-P_rx), (-px));
    int hi = min(P_rx, (511 - px));
    for (int d_1 = lo; d_1 <= hi; d_1++)
    {
        int j_1 = px + d_1;
        s_1 += (float3(rowv[j_1], rowv[512 + j_1], rowv[1024 + j_1]) * asfloat(_507.Load((d_1 + P_rx) * 4 + 0)));
    }
    float4 param_8 = float4(s_1, 1.0f);
    _523.Store2(i * 8 + 0, packH4(param_8));
}

[numthreads(512, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_WorkGroupID = stage_input.gl_WorkGroupID;
    gl_LocalInvocationID = stage_input.gl_LocalInvocationID;
    comp_main();
}
