// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/raster_area.comp - do not edit.
// glsl-sha256: 813e6928e83c7b6dacd5d9bb958a8cf26ea560952badd4c0c32a20fe5dc042ad
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(32u, 8u, 1u);

ByteAddressBuffer _133 : register(t1);
ByteAddressBuffer _167 : register(t0);
RWByteAddressBuffer _209 : register(u2);
cbuffer RasterParams
{
    int P_lines : packoffset(c0);
    int P_decode : packoffset(c0.y);
    int P_rgbSource : packoffset(c0.z);
    int P_pad : packoffset(c0.w);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

float3 linearize(float3 v)
{
    float3 a = pow((v + 0.054999999701976776123046875f.xxx) / 1.05499994754791259765625f.xxx, 2.400000095367431640625f.xxx);
    float3 b = v / 12.9200000762939453125f.xxx;
    bool3 _36 = bool3(v.x <= 0.040449999272823333740234375f.xxx.x, v.y <= 0.040449999272823333740234375f.xxx.y, v.z <= 0.040449999272823333740234375f.xxx.z);
    return float3(_36.x ? b.x : a.x, _36.y ? b.y : a.y, _36.z ? b.z : a.z);
}

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _54 = g.x >= 512u;
    bool _71;
    if (!_54)
    {
        _71 = int(g.y) >= P_lines;
    }
    else
    {
        _71 = _54;
    }
    if (_71)
    {
        return;
    }
    int px = int(g.x);
    int py = int(g.y);
    int low = py * 240;
    int high = (py + 1) * 240;
    float3 sum = 0.0f.xxx;
    int first = low / P_lines;
    float3 v;
    for (int k = 0; k < 4; k++)
    {
        int y = first + k;
        if ((y * P_lines) >= high)
        {
            break;
        }
        if (P_rgbSource != 0)
        {
            uint c = _133.Load(((y * 256) + (px / 2)) * 4 + 0);
            precise float3 _161 = float3(float((c >> uint(16)) & 255u), float((c >> uint(8)) & 255u), float(c & 255u)) / 255.0f.xxx;
            v = _161;
        }
        else
        {
            v = asfloat(_167.Load4(((y * 512) + px) * 16 + 0)).xyz;
        }
        if (P_decode != 0)
        {
            float3 param = v;
            v = linearize(param);
        }
        precise float3 _201 = v * float(min(high, ((y + 1) * P_lines)) - max(low, (y * P_lines)));
        precise float3 _203 = sum + _201;
        sum = _203;
    }
    _209.Store4(((py * 512) + px) * 16 + 0, asuint(float4(sum / 240.0f.xxx, 1.0f)));
}

[numthreads(32, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
