// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/rf_butterfly2.comp - do not edit.
// glsl-sha256: f1eacaacfe65dd5dd2051da5148c4472c76cdea3cfc4028395bf9211e0360c61
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(32u, 8u, 1u);

ByteAddressBuffer _65 : register(t2);
ByteAddressBuffer _98 : register(t0);
RWByteAddressBuffer _271 : register(u1);
cbuffer FFTParams
{
    int P_span : packoffset(c0);
    float P_signValue : packoffset(c0.y);
    int P_blocks : packoffset(c0.z);
    int P_pad : packoffset(c0.w);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

float2 twv(int k, float s)
{
    float2 p = asfloat(_65.Load2(k * 8 + 0));
    return float2(p.x, s * p.y);
}

float2 cmul(float2 a, float2 b)
{
    precise float _36 = a.x * b.x;
    precise float _42 = a.y * b.y;
    precise float _43 = _36 - _42;
    float re = _43;
    precise float _49 = a.x * b.y;
    precise float _54 = a.y * b.x;
    precise float _55 = _49 + _54;
    float im = _55;
    return float2(re, im);
}

float2 stage1(int k, int row, int span, float s)
{
    int h = span / 2;
    int b = (k / span) * span;
    int j = k % h;
    float2 a = asfloat(_98.Load2((((row * 4096) + b) + j) * 8 + 0));
    float2 c = asfloat(_98.Load2(((((row * 4096) + b) + j) + h) * 8 + 0));
    int param = j * (4096 / span);
    float param_1 = s;
    float2 param_2 = c;
    float2 param_3 = twv(param, param_1);
    float2 t = cmul(param_2, param_3);
    float2 _139;
    if ((k % span) < h)
    {
        precise float2 _144 = a + t;
        _139 = _144;
    }
    else
    {
        precise float2 _148 = a - t;
        _139 = _148;
    }
    float2 r = _139;
    return r;
}

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _165 = g.x >= 4096u;
    bool _179;
    if (!_165)
    {
        _179 = int(g.y) >= P_blocks;
    }
    else
    {
        _179 = _165;
    }
    if (_179)
    {
        return;
    }
    int x = int(g.x);
    int row = int(g.y);
    int span = P_span;
    int s2 = span * 2;
    int base = (x / s2) * s2;
    int j = x % span;
    int param = base + j;
    int param_1 = row;
    int param_2 = span;
    float param_3 = P_signValue;
    float2 a = stage1(param, param_1, param_2, param_3);
    int param_4 = (base + j) + span;
    int param_5 = row;
    int param_6 = span;
    float param_7 = P_signValue;
    float2 c = stage1(param_4, param_5, param_6, param_7);
    int param_8 = j * (4096 / s2);
    float param_9 = P_signValue;
    float2 param_10 = c;
    float2 param_11 = twv(param_8, param_9);
    float2 t = cmul(param_10, param_11);
    float2 _257;
    if ((x % s2) < span)
    {
        precise float2 _262 = a + t;
        _257 = _262;
    }
    else
    {
        precise float2 _266 = a - t;
        _257 = _266;
    }
    float2 r = _257;
    _271.Store2(((row * 4096) + x) * 8 + 0, asuint(r));
}

[numthreads(32, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
