// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/rf_butterfly.comp - do not edit.
// glsl-sha256: b696cc3bcb707a275e89853f2fda826ee7c51c94d28b8b968224aba5db707bd0
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(32u, 8u, 1u);

ByteAddressBuffer _58 : register(t2);
ByteAddressBuffer _133 : register(t0);
RWByteAddressBuffer _190 : register(u1);
cbuffer FFTParams
{
    int P_span : packoffset(c0);
    float P_signValue : packoffset(c0.y);
    int P_blocks : packoffset(c0.z);
    int P_pad : packoffset(c0.w);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

float2 twv(int k, float s)
{
    float2 p = asfloat(_58.Load2(k * 8 + 0));
    return float2(p.x, s * p.y);
}

float2 cmul(float2 a, float2 b)
{
    precise float _29 = a.x * b.x;
    precise float _35 = a.y * b.y;
    precise float _36 = _29 - _35;
    float re = _36;
    precise float _42 = a.x * b.y;
    precise float _47 = a.y * b.x;
    precise float _48 = _42 + _47;
    float im = _48;
    return float2(re, im);
}

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _86 = g.x >= 4096u;
    bool _101;
    if (!_86)
    {
        _101 = int(g.y) >= P_blocks;
    }
    else
    {
        _101 = _86;
    }
    if (_101)
    {
        return;
    }
    int x = int(g.x);
    int row = int(g.y);
    int span = P_span;
    int halfSpan = span / 2;
    int j = x % halfSpan;
    int base = (x / span) * span;
    float2 a = asfloat(_133.Load2((((row * 4096) + base) + j) * 8 + 0));
    float2 b = asfloat(_133.Load2(((((row * 4096) + base) + j) + halfSpan) * 8 + 0));
    int param = j * (4096 / span);
    float param_1 = P_signValue;
    float2 param_2 = b;
    float2 param_3 = twv(param, param_1);
    float2 t = cmul(param_2, param_3);
    float2 _176;
    if ((x % span) < halfSpan)
    {
        precise float2 _181 = a + t;
        _176 = _181;
    }
    else
    {
        precise float2 _185 = a - t;
        _176 = _185;
    }
    float2 r = _176;
    _190.Store2(((row * 4096) + x) * 8 + 0, asuint(r));
}

[numthreads(32, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
