// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/rf_extract.comp - do not edit.
// glsl-sha256: ac4c770de4d82830752a5a646ec10141f45d2ad145c2f59192017e3b31928354
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(32u, 8u, 1u);

RWByteAddressBuffer _51 : register(u1);
ByteAddressBuffer _57 : register(t0);
cbuffer RFParams
{
    int P_hop : packoffset(c0);
    int P_overlap : packoffset(c0.y);
    int P_delay : packoffset(c0.z);
    int P_blocks : packoffset(c0.w);
    float P_scale : packoffset(c1);
    float P_signalLevel : packoffset(c1.y);
    float P_noiseSigma : packoffset(c1.z);
    int P_noiseKey : packoffset(c1.w);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _21 = g.x >= 2728u;
    bool _30;
    if (!_21)
    {
        _30 = g.y >= 240u;
    }
    else
    {
        _30 = _21;
    }
    if (_30)
    {
        return;
    }
    int n = (int(g.y) * 2728) + int(g.x);
    _51.Store2(n * 8 + 0, asuint(asfloat(_57.Load2(((((n / P_hop) * 4096) + (n % P_hop)) + P_overlap) * 8 + 0)) / 4096.0f.xx));
}

[numthreads(32, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
