// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/rf_forward_tg.comp - do not edit.
// glsl-sha256: 64a9db2286ed6039ca08740958560754810836a374320beebf8d551bfa9baf2c
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
struct ResType
{
    float _m0;
    int _m1;
};

static const uint3 gl_WorkGroupSize = uint3(512u, 1u, 1u);

ByteAddressBuffer _373 : register(t1);
ByteAddressBuffer _416 : register(t2);
ByteAddressBuffer _447 : register(t3);
ByteAddressBuffer _557 : register(t4);
RWByteAddressBuffer _713 : register(u0);
cbuffer RFParams
{
    int P_hop : packoffset(c0);
    int P_overlap : packoffset(c0.y);
    int P_delay : packoffset(c0.z);
    int P_blocks : packoffset(c0.w);
    float P_scale : packoffset(c1);
    float P_signalLevel : packoffset(c1.y);
    float P_noiseSigma : packoffset(c1.z);
    int P_noiseKey : packoffset(c1.w);
};


static uint3 gl_WorkGroupID;
static uint3 gl_LocalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_WorkGroupID : SV_GroupID;
    uint3 gl_LocalInvocationID : SV_GroupThreadID;
};

groupshared float2 buf[4096];

int reverse12(inout int x)
{
    int y = 0;
    for (int b = 0; b < 12; b++)
    {
        y = (y << 1) | (x & 1);
        x = x >> 1;
    }
    return y;
}

uint codeAt(int i)
{
    uint w = _373.Load((i >> 1) * 4 + 0);
    uint _382;
    if ((i & 1) != 0)
    {
        _382 = w >> 16u;
    }
    else
    {
        _382 = w & 65535u;
    }
    return _382;
}

uint lowbias(inout uint x)
{
    x ^= (x >> 16u);
    x *= 2146121005u;
    x ^= (x >> 15u);
    x *= 2221713035u;
    x ^= (x >> 16u);
    return x;
}

float rn_log(float xin)
{
    ResType _232;
    _232._m0 = frexp(xin, _232._m1);
    int e = _232._m1;
    float m = _232._m0;
    float x;
    if (m < 0.707106769084930419921875f)
    {
        e--;
        precise float _245 = m + m;
        precise float _246 = _245 - 1.0f;
        x = _246;
    }
    else
    {
        precise float _249 = m - 1.0f;
        x = _249;
    }
    precise float _253 = x * x;
    float z = _253;
    float p = 0.070376835763454437255859375f;
    precise float _258 = p * x;
    precise float _260 = _258 - 0.115146100521087646484375f;
    p = _260;
    precise float _263 = p * x;
    precise float _265 = _263 + 0.11676998436450958251953125f;
    p = _265;
    precise float _268 = p * x;
    precise float _270 = _268 - 0.124201409518718719482421875f;
    p = _270;
    precise float _273 = p * x;
    precise float _275 = _273 + 0.14249323308467864990234375f;
    p = _275;
    precise float _278 = p * x;
    precise float _280 = _278 - 0.1666805744171142578125f;
    p = _280;
    precise float _283 = p * x;
    precise float _285 = _283 + 0.200007140636444091796875f;
    p = _285;
    precise float _288 = p * x;
    precise float _290 = _288 - 0.249999940395355224609375f;
    p = _290;
    precise float _293 = p * x;
    precise float _295 = _293 + 0.333333313465118408203125f;
    p = _295;
    precise float _299 = p * x;
    precise float _301 = _299 * z;
    float y = _301;
    float fe = float(e);
    precise float _308 = (-0.00021219444170128554105758666992188f) * fe;
    precise float _309 = y + _308;
    y = _309;
    precise float _313 = (-0.5f) * z;
    precise float _314 = y + _313;
    y = _314;
    precise float _318 = x + y;
    float r = _318;
    precise float _322 = 0.693359375f * fe;
    precise float _323 = r + _322;
    r = _323;
    return r;
}

float rn_cos(float x)
{
    precise float _142 = x * 0.636619746685028076171875f;
    precise float _144 = _142 + 0.5f;
    float q = floor(_144);
    precise float _150 = q * 1.5703125f;
    precise float _151 = x - _150;
    precise float _154 = q * 0.0004837512969970703125f;
    precise float _155 = _151 - _154;
    precise float _158 = q * 7.5497901264043321134522557258606e-08f;
    precise float _159 = _155 - _158;
    float r = _159;
    int quadrant = int(q) & 3;
    precise float _168 = r * r;
    float z = _168;
    precise float _172 = (-0.00019515295571181923151016235351562f) * z;
    precise float _174 = _172 + 0.00833216123282909393310546875f;
    precise float _176 = _174 * z;
    precise float _178 = _176 - 0.16666655242443084716796875f;
    precise float _180 = _178 * z;
    precise float _182 = _180 * r;
    precise float _184 = _182 + r;
    float s = _184;
    precise float _188 = 2.4433156795566901564598083496094e-05f * z;
    precise float _190 = _188 - 0.00138873164542019367218017578125f;
    precise float _192 = _190 * z;
    precise float _194 = _192 + 0.0416666455566883087158203125f;
    precise float _196 = _194 * z;
    precise float _198 = _196 * z;
    precise float _200 = 0.5f * z;
    precise float _201 = _198 - _200;
    precise float _203 = _201 + 1.0f;
    float c = _203;
    if (quadrant == 0)
    {
        return c;
    }
    if (quadrant == 1)
    {
        return -s;
    }
    if (quadrant == 2)
    {
        return -c;
    }
    return s;
}

float gaussAt(int pos, int key)
{
    uint k = uint(key);
    uint param = (uint(pos) * 2u) ^ k;
    uint _338 = lowbias(param);
    float u1 = (float(_338) + 0.5f) / 4294967296.0f;
    uint param_1 = ((uint(pos) * 2u) + 1u) ^ k;
    uint _351 = lowbias(param_1);
    float u2 = (float(_351) + 0.5f) / 4294967296.0f;
    float param_2 = u1;
    float param_3 = 6.283185482025146484375f * u2;
    return sqrt((-2.0f) * rn_log(param_2)) * rn_cos(param_3);
}

float rfInitAt(int pos)
{
    float v = 0.3120000064373016357421875f;
    if ((pos >= 0) && (pos < 654720))
    {
        int row = pos / 2728;
        int n = pos % 2728;
        int phase = (n + int(_416.Load(row * 4 + 0))) % 12;
        if ((n >= 36) && (n < 2084))
        {
            int param = (row * 256) + ((n - 36) / 8);
            int code = int(codeAt(param));
            v = asfloat(_447.Load(((phase * 512) + code) * 4 + 0));
        }
        else
        {
            if ((n >= 2244) && (n < 2444))
            {
                v = 0.048000000417232513427734375f;
            }
            else
            {
                if ((n >= 2476) && (n < 2596))
                {
                    v = (((8 + phase) % 12) < 6) ? 0.523999989032745361328125f : 0.1480000019073486328125f;
                }
            }
        }
    }
    bool _490 = (pos >= 0) && (pos < 654720);
    bool _501;
    if (_490)
    {
        _501 = P_noiseSigma > 0.0f;
    }
    else
    {
        _501 = _490;
    }
    float _502;
    if (_501)
    {
        int param_1 = pos;
        int param_2 = P_noiseKey;
        precise float _515 = P_noiseSigma * gaussAt(param_1, param_2);
        _502 = _515;
    }
    else
    {
        _502 = 0.0f;
    }
    float _noise = _502;
    precise float _523 = v - 0.048000000417232513427734375f;
    precise float _524 = P_scale * _523;
    precise float _525 = 1.0f - _524;
    precise float _529 = _525 * P_signalLevel;
    precise float _531 = _529 + _noise;
    float r = _531;
    return r;
}

float rfInitValue(int x, int block)
{
    int param = x;
    int _547 = reverse12(param);
    int param_1 = (((block * P_hop) + P_delay) - P_overlap) + _547;
    return rfInitAt(param_1);
}

float2 twv(int k, float s)
{
    float2 p = asfloat(_557.Load2(k * 8 + 0));
    return float2(p.x, s * p.y);
}

float2 cmul(float2 a, float2 b)
{
    precise float _91 = a.x * b.x;
    precise float _97 = a.y * b.y;
    precise float _98 = _91 - _97;
    float re = _98;
    precise float _104 = a.x * b.y;
    precise float _109 = a.y * b.x;
    precise float _110 = _104 + _109;
    float im = _110;
    return float2(re, im);
}

void fftStagesTG(float sgn)
{
    uint tid = gl_LocalInvocationID.x;
    uint nthreads = 512u;
    for (int span = 2; span <= 4096; span *= 2)
    {
        int h = span / 2;
        int _step = 4096 / span;
        int _597 = int(tid);
        for (int p = _597; p < 2048; p += int(nthreads))
        {
            int j = p % h;
            int i0 = ((p / h) * span) + j;
            int i1 = i0 + h;
            float2 a = buf[i0];
            int param = j * _step;
            float param_1 = sgn;
            float2 param_2 = buf[i1];
            float2 param_3 = twv(param, param_1);
            float2 t = cmul(param_2, param_3);
            precise float2 _648 = a + t;
            float2 s0 = _648;
            precise float2 _652 = a - t;
            float2 s1 = _652;
            buf[i0] = s0;
            buf[i1] = s1;
        }
        GroupMemoryBarrierWithGroupSync();
    }
}

void comp_main()
{
    uint tid = gl_LocalInvocationID.x;
    uint nthreads = 512u;
    uint blk = gl_WorkGroupID.x;
    int _676 = int(tid);
    for (int i = _676; i < 4096; i += int(nthreads))
    {
        int param = i;
        int param_1 = int(blk);
        buf[i] = float2(rfInitValue(param, param_1), 0.0f);
    }
    GroupMemoryBarrierWithGroupSync();
    float param_2 = -1.0f;
    fftStagesTG(param_2);
    int _702 = int(tid);
    for (int i_1 = _702; i_1 < 4096; i_1 += int(nthreads))
    {
        _713.Store2(((blk * 4096u) + uint(i_1)) * 8 + 0, asuint(buf[i_1]));
    }
}

[numthreads(512, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_WorkGroupID = stage_input.gl_WorkGroupID;
    gl_LocalInvocationID = stage_input.gl_LocalInvocationID;
    comp_main();
}
