// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/rf_forward_tg.comp - do not edit.
// glsl-sha256: df1090f156090f2c88448dc253ecfb068968e26fd35cb568e5d9e7213a32dff3
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
struct ResType
{
    float _m0;
    int _m1;
};

static const uint3 gl_WorkGroupSize = uint3(512u, 1u, 1u);

ByteAddressBuffer _369 : register(t1);
ByteAddressBuffer _431 : register(t2);
ByteAddressBuffer _462 : register(t3);
ByteAddressBuffer _550 : register(t4);
RWByteAddressBuffer _706 : register(u0);
cbuffer RFParams
{
    int P_hop : packoffset(c0);
    int P_overlap : packoffset(c0.y);
    int P_delay : packoffset(c0.z);
    int P_blocks : packoffset(c0.w);
    float P_scale : packoffset(c1);
    float P_signalLevel : packoffset(c1.y);
    float P_noiseSigma : packoffset(c1.z);
    int P_noiseKey : packoffset(c1.w);
};


static uint3 gl_WorkGroupID;
static uint3 gl_LocalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_WorkGroupID : SV_GroupID;
    uint3 gl_LocalInvocationID : SV_GroupThreadID;
};

groupshared float2 buf[4096];

int reverse12(inout int x)
{
    int y = 0;
    for (int b = 0; b < 12; b++)
    {
        y = (y << 1) | (x & 1);
        x = x >> 1;
    }
    return y;
}

uint codeAt(int i)
{
    uint w = _369.Load((i >> 1) * 4 + 0);
    uint _378;
    if ((i & 1) != 0)
    {
        _378 = w >> 16u;
    }
    else
    {
        _378 = w & 65535u;
    }
    return _378;
}

uint lowbias(inout uint x)
{
    x ^= (x >> 16u);
    x *= 2146121005u;
    x ^= (x >> 15u);
    x *= 2221713035u;
    x ^= (x >> 16u);
    return x;
}

float rn_log(float xin)
{
    ResType _228;
    _228._m0 = frexp(xin, _228._m1);
    int e = _228._m1;
    float m = _228._m0;
    float x;
    if (m < 0.707106769084930419921875f)
    {
        e--;
        precise float _241 = m + m;
        precise float _242 = _241 - 1.0f;
        x = _242;
    }
    else
    {
        precise float _245 = m - 1.0f;
        x = _245;
    }
    precise float _249 = x * x;
    float z = _249;
    float p = 0.070376835763454437255859375f;
    precise float _254 = p * x;
    precise float _256 = _254 - 0.115146100521087646484375f;
    p = _256;
    precise float _259 = p * x;
    precise float _261 = _259 + 0.11676998436450958251953125f;
    p = _261;
    precise float _264 = p * x;
    precise float _266 = _264 - 0.124201409518718719482421875f;
    p = _266;
    precise float _269 = p * x;
    precise float _271 = _269 + 0.14249323308467864990234375f;
    p = _271;
    precise float _274 = p * x;
    precise float _276 = _274 - 0.1666805744171142578125f;
    p = _276;
    precise float _279 = p * x;
    precise float _281 = _279 + 0.200007140636444091796875f;
    p = _281;
    precise float _284 = p * x;
    precise float _286 = _284 - 0.249999940395355224609375f;
    p = _286;
    precise float _289 = p * x;
    precise float _291 = _289 + 0.333333313465118408203125f;
    p = _291;
    precise float _295 = p * x;
    precise float _297 = _295 * z;
    float y = _297;
    float fe = float(e);
    precise float _304 = (-0.00021219444170128554105758666992188f) * fe;
    precise float _305 = y + _304;
    y = _305;
    precise float _309 = (-0.5f) * z;
    precise float _310 = y + _309;
    y = _310;
    precise float _314 = x + y;
    float r = _314;
    precise float _318 = 0.693359375f * fe;
    precise float _319 = r + _318;
    r = _319;
    return r;
}

float rn_cos(float x)
{
    precise float _138 = x * 0.636619746685028076171875f;
    precise float _140 = _138 + 0.5f;
    float q = floor(_140);
    precise float _146 = q * 1.5703125f;
    precise float _147 = x - _146;
    precise float _150 = q * 0.0004837512969970703125f;
    precise float _151 = _147 - _150;
    precise float _154 = q * 7.5497901264043321134522557258606e-08f;
    precise float _155 = _151 - _154;
    float r = _155;
    int quadrant = int(q) & 3;
    precise float _164 = r * r;
    float z = _164;
    precise float _168 = (-0.00019515295571181923151016235351562f) * z;
    precise float _170 = _168 + 0.00833216123282909393310546875f;
    precise float _172 = _170 * z;
    precise float _174 = _172 - 0.16666655242443084716796875f;
    precise float _176 = _174 * z;
    precise float _178 = _176 * r;
    precise float _180 = _178 + r;
    float s = _180;
    precise float _184 = 2.4433156795566901564598083496094e-05f * z;
    precise float _186 = _184 - 0.00138873164542019367218017578125f;
    precise float _188 = _186 * z;
    precise float _190 = _188 + 0.0416666455566883087158203125f;
    precise float _192 = _190 * z;
    precise float _194 = _192 * z;
    precise float _196 = 0.5f * z;
    precise float _197 = _194 - _196;
    precise float _199 = _197 + 1.0f;
    float c = _199;
    if (quadrant == 0)
    {
        return c;
    }
    if (quadrant == 1)
    {
        return -s;
    }
    if (quadrant == 2)
    {
        return -c;
    }
    return s;
}

float gaussAt(int pos, int key)
{
    uint k = uint(key);
    uint param = (uint(pos) * 2u) ^ k;
    uint _334 = lowbias(param);
    float u1 = (float(_334) + 0.5f) / 4294967296.0f;
    uint param_1 = ((uint(pos) * 2u) + 1u) ^ k;
    uint _347 = lowbias(param_1);
    float u2 = (float(_347) + 0.5f) / 4294967296.0f;
    float param_2 = u1;
    float param_3 = 6.283185482025146484375f * u2;
    return sqrt((-2.0f) * rn_log(param_2)) * rn_cos(param_3);
}

float rfInitValue(int x, int block)
{
    int param = x;
    int _407 = reverse12(param);
    int pos = (((block * P_hop) + P_delay) - P_overlap) + _407;
    float v = 0.3120000064373016357421875f;
    if ((pos >= 0) && (pos < 654720))
    {
        int row = pos / 2728;
        int n = pos % 2728;
        int phase = (n + int(_431.Load(row * 4 + 0))) % 12;
        if ((n >= 36) && (n < 2084))
        {
            int param_1 = (row * 256) + ((n - 36) / 8);
            int code = int(codeAt(param_1));
            v = asfloat(_462.Load(((phase * 512) + code) * 4 + 0));
        }
        else
        {
            if ((n >= 2244) && (n < 2444))
            {
                v = 0.048000000417232513427734375f;
            }
            else
            {
                if ((n >= 2476) && (n < 2596))
                {
                    v = (((8 + phase) % 12) < 6) ? 0.523999989032745361328125f : 0.1480000019073486328125f;
                }
            }
        }
    }
    bool _505 = (pos >= 0) && (pos < 654720);
    bool _513;
    if (_505)
    {
        _513 = P_noiseSigma > 0.0f;
    }
    else
    {
        _513 = _505;
    }
    float _514;
    if (_513)
    {
        int param_2 = pos;
        int param_3 = P_noiseKey;
        precise float _526 = P_noiseSigma * gaussAt(param_2, param_3);
        _514 = _526;
    }
    else
    {
        _514 = 0.0f;
    }
    float _noise = _514;
    precise float _534 = v - 0.048000000417232513427734375f;
    precise float _535 = P_scale * _534;
    precise float _536 = 1.0f - _535;
    precise float _540 = _536 * P_signalLevel;
    precise float _542 = _540 + _noise;
    float r = _542;
    return r;
}

float2 twv(int k, float s)
{
    float2 p = asfloat(_550.Load2(k * 8 + 0));
    return float2(p.x, s * p.y);
}

float2 cmul(float2 a, float2 b)
{
    precise float _87 = a.x * b.x;
    precise float _93 = a.y * b.y;
    precise float _94 = _87 - _93;
    float re = _94;
    precise float _100 = a.x * b.y;
    precise float _105 = a.y * b.x;
    precise float _106 = _100 + _105;
    float im = _106;
    return float2(re, im);
}

void fftStagesTG(float sgn)
{
    uint tid = gl_LocalInvocationID.x;
    uint nthreads = 512u;
    for (int span = 2; span <= 4096; span *= 2)
    {
        int h = span / 2;
        int _step = 4096 / span;
        int _590 = int(tid);
        for (int p = _590; p < 2048; p += int(nthreads))
        {
            int j = p % h;
            int i0 = ((p / h) * span) + j;
            int i1 = i0 + h;
            float2 a = buf[i0];
            int param = j * _step;
            float param_1 = sgn;
            float2 param_2 = buf[i1];
            float2 param_3 = twv(param, param_1);
            float2 t = cmul(param_2, param_3);
            precise float2 _641 = a + t;
            float2 s0 = _641;
            precise float2 _645 = a - t;
            float2 s1 = _645;
            buf[i0] = s0;
            buf[i1] = s1;
        }
        GroupMemoryBarrierWithGroupSync();
    }
}

void comp_main()
{
    uint tid = gl_LocalInvocationID.x;
    uint nthreads = 512u;
    uint blk = gl_WorkGroupID.x;
    int _669 = int(tid);
    for (int i = _669; i < 4096; i += int(nthreads))
    {
        int param = i;
        int param_1 = int(blk);
        buf[i] = float2(rfInitValue(param, param_1), 0.0f);
    }
    GroupMemoryBarrierWithGroupSync();
    float param_2 = -1.0f;
    fftStagesTG(param_2);
    int _695 = int(tid);
    for (int i_1 = _695; i_1 < 4096; i_1 += int(nthreads))
    {
        _706.Store2(((blk * 4096u) + uint(i_1)) * 8 + 0, asuint(buf[i_1]));
    }
}

[numthreads(512, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_WorkGroupID = stage_input.gl_WorkGroupID;
    gl_LocalInvocationID = stage_input.gl_LocalInvocationID;
    comp_main();
}
