// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/rf_fast.comp - do not edit.
// glsl-sha256: 771573a3404ec262a204643c11986153953d7f54cd36ebc816474df7e151dc7d
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
struct ResType
{
    float _m0;
    int _m1;
};

static const uint3 gl_WorkGroupSize = uint3(512u, 1u, 1u);

ByteAddressBuffer _345 : register(t1);
ByteAddressBuffer _388 : register(t2);
ByteAddressBuffer _420 : register(t3);
ByteAddressBuffer _707 : register(t4);
ByteAddressBuffer _954 : register(t5);
RWByteAddressBuffer _1027 : register(u0);
cbuffer RFParams
{
    int P_hop : packoffset(c0);
    int P_overlap : packoffset(c0.y);
    int P_delay : packoffset(c0.z);
    int P_blocks : packoffset(c0.w);
    float P_scale : packoffset(c1);
    float P_signalLevel : packoffset(c1.y);
    float P_noiseSigma : packoffset(c1.z);
    int P_noiseKey : packoffset(c1.w);
};


static uint3 gl_WorkGroupID;
static uint3 gl_LocalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_WorkGroupID : SV_GroupID;
    uint3 gl_LocalInvocationID : SV_GroupThreadID;
};

static float2 v[8];
groupshared float xs[4096];

uint codeAt(int i)
{
    uint w = _345.Load((i >> 1) * 4 + 0);
    uint _354;
    if ((i & 1) != 0)
    {
        _354 = w >> 16u;
    }
    else
    {
        _354 = w & 65535u;
    }
    return _354;
}

uint lowbias(inout uint x)
{
    x ^= (x >> 16u);
    x *= 2146121005u;
    x ^= (x >> 15u);
    x *= 2221713035u;
    x ^= (x >> 16u);
    return x;
}

float rn_log(float xin)
{
    ResType _204;
    _204._m0 = frexp(xin, _204._m1);
    int e = _204._m1;
    float m = _204._m0;
    float x;
    if (m < 0.707106769084930419921875f)
    {
        e--;
        precise float _217 = m + m;
        precise float _218 = _217 - 1.0f;
        x = _218;
    }
    else
    {
        precise float _221 = m - 1.0f;
        x = _221;
    }
    precise float _225 = x * x;
    float z = _225;
    float p = 0.070376835763454437255859375f;
    precise float _230 = p * x;
    precise float _232 = _230 - 0.115146100521087646484375f;
    p = _232;
    precise float _235 = p * x;
    precise float _237 = _235 + 0.11676998436450958251953125f;
    p = _237;
    precise float _240 = p * x;
    precise float _242 = _240 - 0.124201409518718719482421875f;
    p = _242;
    precise float _245 = p * x;
    precise float _247 = _245 + 0.14249323308467864990234375f;
    p = _247;
    precise float _250 = p * x;
    precise float _252 = _250 - 0.1666805744171142578125f;
    p = _252;
    precise float _255 = p * x;
    precise float _257 = _255 + 0.200007140636444091796875f;
    p = _257;
    precise float _260 = p * x;
    precise float _262 = _260 - 0.249999940395355224609375f;
    p = _262;
    precise float _265 = p * x;
    precise float _267 = _265 + 0.333333313465118408203125f;
    p = _267;
    precise float _271 = p * x;
    precise float _273 = _271 * z;
    float y = _273;
    float fe = float(e);
    precise float _280 = (-0.00021219444170128554105758666992188f) * fe;
    precise float _281 = y + _280;
    y = _281;
    precise float _285 = (-0.5f) * z;
    precise float _286 = y + _285;
    y = _286;
    precise float _290 = x + y;
    float r = _290;
    precise float _294 = 0.693359375f * fe;
    precise float _295 = r + _294;
    r = _295;
    return r;
}

float rn_cos(float x)
{
    precise float _111 = x * 0.636619746685028076171875f;
    precise float _113 = _111 + 0.5f;
    float q = floor(_113);
    precise float _119 = q * 1.5703125f;
    precise float _120 = x - _119;
    precise float _123 = q * 0.0004837512969970703125f;
    precise float _124 = _120 - _123;
    precise float _127 = q * 7.5497901264043321134522557258606e-08f;
    precise float _128 = _124 - _127;
    float r = _128;
    int quadrant = int(q) & 3;
    precise float _137 = r * r;
    float z = _137;
    precise float _141 = (-0.00019515295571181923151016235351562f) * z;
    precise float _143 = _141 + 0.00833216123282909393310546875f;
    precise float _145 = _143 * z;
    precise float _147 = _145 - 0.16666655242443084716796875f;
    precise float _149 = _147 * z;
    precise float _151 = _149 * r;
    precise float _153 = _151 + r;
    float s = _153;
    precise float _157 = 2.4433156795566901564598083496094e-05f * z;
    precise float _159 = _157 - 0.00138873164542019367218017578125f;
    precise float _161 = _159 * z;
    precise float _163 = _161 + 0.0416666455566883087158203125f;
    precise float _165 = _163 * z;
    precise float _167 = _165 * z;
    precise float _169 = 0.5f * z;
    precise float _170 = _167 - _169;
    precise float _172 = _170 + 1.0f;
    float c = _172;
    if (quadrant == 0)
    {
        return c;
    }
    if (quadrant == 1)
    {
        return -s;
    }
    if (quadrant == 2)
    {
        return -c;
    }
    return s;
}

float gaussAt(int pos, int key)
{
    uint k = uint(key);
    uint param = (uint(pos) * 2u) ^ k;
    uint _310 = lowbias(param);
    float u1 = (float(_310) + 0.5f) / 4294967296.0f;
    uint param_1 = ((uint(pos) * 2u) + 1u) ^ k;
    uint _323 = lowbias(param_1);
    float u2 = (float(_323) + 0.5f) / 4294967296.0f;
    float param_2 = u1;
    float param_3 = 6.283185482025146484375f * u2;
    return sqrt((-2.0f) * rn_log(param_2)) * rn_cos(param_3);
}

float rfInitAt(int pos)
{
    float v_1 = 0.3120000064373016357421875f;
    if ((pos >= 0) && (pos < 654720))
    {
        int row = pos / 2728;
        int n = pos % 2728;
        int phase = (n + int(_388.Load(row * 4 + 0))) % 12;
        if ((n >= 36) && (n < 2084))
        {
            int param = (row * 256) + ((n - 36) / 8);
            int code = int(codeAt(param));
            v_1 = asfloat(_420.Load(((phase * 512) + code) * 4 + 0));
        }
        else
        {
            if ((n >= 2244) && (n < 2444))
            {
                v_1 = 0.048000000417232513427734375f;
            }
            else
            {
                if ((n >= 2476) && (n < 2596))
                {
                    v_1 = (((8 + phase) % 12) < 6) ? 0.523999989032745361328125f : 0.1480000019073486328125f;
                }
            }
        }
    }
    bool _463 = (pos >= 0) && (pos < 654720);
    bool _474;
    if (_463)
    {
        _474 = P_noiseSigma > 0.0f;
    }
    else
    {
        _474 = _463;
    }
    float _475;
    if (_474)
    {
        int param_1 = pos;
        int param_2 = P_noiseKey;
        precise float _488 = P_noiseSigma * gaussAt(param_1, param_2);
        _475 = _488;
    }
    else
    {
        _475 = 0.0f;
    }
    float _noise = _475;
    precise float _496 = v_1 - 0.048000000417232513427734375f;
    precise float _497 = P_scale * _496;
    precise float _498 = 1.0f - _497;
    precise float _502 = _498 * P_signalLevel;
    precise float _504 = _502 + _noise;
    float r = _504;
    return r;
}

float2 cmulF(float2 a, float2 b)
{
    return float2((a.x * b.x) - (a.y * b.y), (a.x * b.y) + (a.y * b.x));
}

void dft8(float s)
{
    float2 a0 = v[0] + v[4];
    float2 a1 = v[1] + v[5];
    float2 a2 = v[2] + v[6];
    float2 a3 = v[3] + v[7];
    float2 b0 = v[0] - v[4];
    float2 b1 = v[1] - v[5];
    float2 b2 = v[2] - v[6];
    float2 b3 = v[3] - v[7];
    b1 = float2(0.707106769084930419921875f * (b1.x - (s * b1.y)), 0.707106769084930419921875f * (b1.y + (s * b1.x)));
    b2 = float2((-s) * b2.y, s * b2.x);
    b3 = float2((-0.707106769084930419921875f) * (b3.x + (s * b3.y)), 0.707106769084930419921875f * ((s * b3.x) - b3.y));
    float2 c0 = a0 + a2;
    float2 c1 = a1 + a3;
    float2 d0 = a0 - a2;
    float2 d1 = a1 - a3;
    d1 = float2((-s) * d1.y, s * d1.x);
    float2 e0 = b0 + b2;
    float2 e1 = b1 + b3;
    float2 f0 = b0 - b2;
    float2 f1 = b1 - b3;
    f1 = float2((-s) * f1.y, s * f1.x);
    v[0] = c0 + c1;
    v[4] = c0 - c1;
    v[2] = d0 + d1;
    v[6] = d0 - d1;
    v[1] = e0 + e1;
    v[5] = e0 - e1;
    v[3] = f0 + f1;
    v[7] = f0 - f1;
}

void fftPass(float s, int j, int ns)
{
    int k = j % ns;
    int _step = 4096 / (ns * 8);
    if (k > 0)
    {
        float2 t = asfloat(_707.Load2((k * _step) * 8 + 0));
        float2 w1 = float2(t.x, s * t.y);
        float2 wr = w1;
        for (int r = 1; r < 8; r++)
        {
            float2 param = v[r];
            float2 param_1 = wr;
            v[r] = cmulF(param, param_1);
            float2 param_2 = wr;
            float2 param_3 = w1;
            wr = cmulF(param_2, param_3);
        }
    }
    float param_4 = s;
    dft8(param_4);
    int d = (((j / ns) * ns) * 8) + k;
    GroupMemoryBarrierWithGroupSync();
    for (int r_1 = 0; r_1 < 8; r_1++)
    {
        xs[d + (r_1 * ns)] = v[r_1].x;
    }
    GroupMemoryBarrierWithGroupSync();
    float re[8];
    for (int r_2 = 0; r_2 < 8; r_2++)
    {
        re[r_2] = xs[j + (r_2 * 512)];
    }
    GroupMemoryBarrierWithGroupSync();
    for (int r_3 = 0; r_3 < 8; r_3++)
    {
        xs[d + (r_3 * ns)] = v[r_3].y;
    }
    GroupMemoryBarrierWithGroupSync();
    for (int r_4 = 0; r_4 < 8; r_4++)
    {
        v[r_4] = float2(re[r_4], xs[j + (r_4 * 512)]);
    }
}

void fft4096(float s, int j)
{
    for (int ns = 1; ns < 4096; ns *= 8)
    {
        float param = s;
        int param_1 = j;
        int param_2 = ns;
        fftPass(param, param_1, param_2);
    }
}

void comp_main()
{
    int j = int(gl_LocalInvocationID.x);
    int b0 = int(gl_WorkGroupID.x) * 2;
    bool has1 = (b0 + 1) < P_blocks;
    int base0 = ((b0 * P_hop) + P_delay) - P_overlap;
    int base1 = base0 + P_hop;
    float _922;
    for (int r = 0; r < 8; r++)
    {
        int i = j + (r * 512);
        int param = base0 + i;
        if (has1)
        {
            int param_1 = base1 + i;
            _922 = rfInitAt(param_1);
        }
        else
        {
            _922 = 0.0f;
        }
        v[r] = float2(rfInitAt(param), _922);
    }
    float param_2 = -1.0f;
    int param_3 = j;
    fft4096(param_2, param_3);
    for (int r_1 = 0; r_1 < 8; r_1++)
    {
        float2 param_4 = v[r_1];
        float2 param_5 = asfloat(_954.Load2((j + (r_1 * 512)) * 8 + 0));
        v[r_1] = cmulF(param_4, param_5);
    }
    float param_6 = 1.0f;
    int param_7 = j;
    fft4096(param_6, param_7);
    for (int r_2 = 0; r_2 < 8; r_2++)
    {
        int k = (j + (r_2 * 512)) - P_overlap;
        bool _990 = k < 0;
        bool _998;
        if (!_990)
        {
            _998 = k >= P_hop;
        }
        else
        {
            _998 = _990;
        }
        if (_998)
        {
            continue;
        }
        float2 y = v[r_2] * 0.000244140625f;
        int n0 = (b0 * P_hop) + k;
        int n1 = n0 + P_hop;
        if (n0 < 654720)
        {
            _1027.Store(n0 * 4 + 0, asuint(y.x));
        }
        if (has1 && (n1 < 654720))
        {
            _1027.Store(n1 * 4 + 0, asuint(y.y));
        }
    }
}

[numthreads(512, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_WorkGroupID = stage_input.gl_WorkGroupID;
    gl_LocalInvocationID = stage_input.gl_LocalInvocationID;
    comp_main();
}
