// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/rf_init_codes.comp - do not edit.
// glsl-sha256: 1a323ba6265d02c598917c8ed0507fc45ac3945047d76f9cb46233ef18645849
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
struct ResType
{
    float _m0;
    int _m1;
};

static const uint3 gl_WorkGroupSize = uint3(64u, 4u, 1u);

ByteAddressBuffer _323 : register(t1);
ByteAddressBuffer _385 : register(t2);
ByteAddressBuffer _416 : register(t3);
RWByteAddressBuffer _530 : register(u0);
cbuffer RFParams
{
    int P_hop : packoffset(c0);
    int P_overlap : packoffset(c0.y);
    int P_delay : packoffset(c0.z);
    int P_blocks : packoffset(c0.w);
    float P_scale : packoffset(c1);
    float P_signalLevel : packoffset(c1.y);
    float P_noiseSigma : packoffset(c1.z);
    int P_noiseKey : packoffset(c1.w);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

int reverse12(inout int x)
{
    int y = 0;
    for (int b = 0; b < 12; b++)
    {
        y = (y << 1) | (x & 1);
        x = x >> 1;
    }
    return y;
}

uint codeAt(int i)
{
    uint w = _323.Load((i >> 1) * 4 + 0);
    uint _332;
    if ((i & 1) != 0)
    {
        _332 = w >> 16u;
    }
    else
    {
        _332 = w & 65535u;
    }
    return _332;
}

uint lowbias(inout uint x)
{
    x ^= (x >> 16u);
    x *= 2146121005u;
    x ^= (x >> 15u);
    x *= 2221713035u;
    x ^= (x >> 16u);
    return x;
}

float rn_log(float xin)
{
    ResType _181;
    _181._m0 = frexp(xin, _181._m1);
    int e = _181._m1;
    float m = _181._m0;
    float x;
    if (m < 0.707106769084930419921875f)
    {
        e--;
        precise float _194 = m + m;
        precise float _195 = _194 - 1.0f;
        x = _195;
    }
    else
    {
        precise float _198 = m - 1.0f;
        x = _198;
    }
    precise float _202 = x * x;
    float z = _202;
    float p = 0.070376835763454437255859375f;
    precise float _207 = p * x;
    precise float _209 = _207 - 0.115146100521087646484375f;
    p = _209;
    precise float _212 = p * x;
    precise float _214 = _212 + 0.11676998436450958251953125f;
    p = _214;
    precise float _217 = p * x;
    precise float _219 = _217 - 0.124201409518718719482421875f;
    p = _219;
    precise float _222 = p * x;
    precise float _224 = _222 + 0.14249323308467864990234375f;
    p = _224;
    precise float _227 = p * x;
    precise float _229 = _227 - 0.1666805744171142578125f;
    p = _229;
    precise float _232 = p * x;
    precise float _234 = _232 + 0.200007140636444091796875f;
    p = _234;
    precise float _237 = p * x;
    precise float _239 = _237 - 0.249999940395355224609375f;
    p = _239;
    precise float _242 = p * x;
    precise float _244 = _242 + 0.333333313465118408203125f;
    p = _244;
    precise float _248 = p * x;
    precise float _250 = _248 * z;
    float y = _250;
    float fe = float(e);
    precise float _257 = (-0.00021219444170128554105758666992188f) * fe;
    precise float _258 = y + _257;
    y = _258;
    precise float _262 = (-0.5f) * z;
    precise float _263 = y + _262;
    y = _263;
    precise float _267 = x + y;
    float r = _267;
    precise float _271 = 0.693359375f * fe;
    precise float _272 = r + _271;
    r = _272;
    return r;
}

float rn_cos(float x)
{
    precise float _91 = x * 0.636619746685028076171875f;
    precise float _93 = _91 + 0.5f;
    float q = floor(_93);
    precise float _99 = q * 1.5703125f;
    precise float _100 = x - _99;
    precise float _103 = q * 0.0004837512969970703125f;
    precise float _104 = _100 - _103;
    precise float _107 = q * 7.5497901264043321134522557258606e-08f;
    precise float _108 = _104 - _107;
    float r = _108;
    int quadrant = int(q) & 3;
    precise float _117 = r * r;
    float z = _117;
    precise float _121 = (-0.00019515295571181923151016235351562f) * z;
    precise float _123 = _121 + 0.00833216123282909393310546875f;
    precise float _125 = _123 * z;
    precise float _127 = _125 - 0.16666655242443084716796875f;
    precise float _129 = _127 * z;
    precise float _131 = _129 * r;
    precise float _133 = _131 + r;
    float s = _133;
    precise float _137 = 2.4433156795566901564598083496094e-05f * z;
    precise float _139 = _137 - 0.00138873164542019367218017578125f;
    precise float _141 = _139 * z;
    precise float _143 = _141 + 0.0416666455566883087158203125f;
    precise float _145 = _143 * z;
    precise float _147 = _145 * z;
    precise float _149 = 0.5f * z;
    precise float _150 = _147 - _149;
    precise float _152 = _150 + 1.0f;
    float c = _152;
    if (quadrant == 0)
    {
        return c;
    }
    if (quadrant == 1)
    {
        return -s;
    }
    if (quadrant == 2)
    {
        return -c;
    }
    return s;
}

float gaussAt(int pos, int key)
{
    uint k = uint(key);
    uint param = (uint(pos) * 2u) ^ k;
    uint _287 = lowbias(param);
    float u1 = (float(_287) + 0.5f) / 4294967296.0f;
    uint param_1 = ((uint(pos) * 2u) + 1u) ^ k;
    uint _301 = lowbias(param_1);
    float u2 = (float(_301) + 0.5f) / 4294967296.0f;
    float param_2 = u1;
    float param_3 = 6.283185482025146484375f * u2;
    return sqrt((-2.0f) * rn_log(param_2)) * rn_cos(param_3);
}

float rfInitValue(int x, int block)
{
    int param = x;
    int _361 = reverse12(param);
    int pos = (((block * P_hop) + P_delay) - P_overlap) + _361;
    float v = 0.3120000064373016357421875f;
    if ((pos >= 0) && (pos < 654720))
    {
        int row = pos / 2728;
        int n = pos % 2728;
        int phase = (n + int(_385.Load(row * 4 + 0))) % 12;
        if ((n >= 36) && (n < 2084))
        {
            int param_1 = (row * 256) + ((n - 36) / 8);
            int code = int(codeAt(param_1));
            v = asfloat(_416.Load(((phase * 512) + code) * 4 + 0));
        }
        else
        {
            if ((n >= 2244) && (n < 2444))
            {
                v = 0.048000000417232513427734375f;
            }
            else
            {
                if ((n >= 2476) && (n < 2596))
                {
                    v = (((8 + phase) % 12) < 6) ? 0.523999989032745361328125f : 0.1480000019073486328125f;
                }
            }
        }
    }
    bool _459 = (pos >= 0) && (pos < 654720);
    bool _467;
    if (_459)
    {
        _467 = P_noiseSigma > 0.0f;
    }
    else
    {
        _467 = _459;
    }
    float _468;
    if (_467)
    {
        int param_2 = pos;
        int param_3 = P_noiseKey;
        precise float _480 = P_noiseSigma * gaussAt(param_2, param_3);
        _468 = _480;
    }
    else
    {
        _468 = 0.0f;
    }
    float _noise = _468;
    precise float _488 = v - 0.048000000417232513427734375f;
    precise float _489 = P_scale * _488;
    precise float _490 = 1.0f - _489;
    precise float _494 = _490 * P_signalLevel;
    precise float _496 = _494 + _noise;
    float r = _496;
    return r;
}

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _512 = g.x >= 4096u;
    bool _522;
    if (!_512)
    {
        _522 = int(g.y) >= P_blocks;
    }
    else
    {
        _522 = _512;
    }
    if (_522)
    {
        return;
    }
    int param = int(g.x);
    int param_1 = int(g.y);
    _530.Store2(((g.y * 4096u) + g.x) * 8 + 0, asuint(float2(rfInitValue(param, param_1), 0.0f)));
}

[numthreads(64, 4, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
