// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/rf_init_codes.comp - do not edit.
// glsl-sha256: 909856c84e32306a25afa4465a4fe3bd990fa7fcf86297696fd4d8182786876a
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
struct ResType
{
    float _m0;
    int _m1;
};

static const uint3 gl_WorkGroupSize = uint3(64u, 4u, 1u);

ByteAddressBuffer _327 : register(t1);
ByteAddressBuffer _370 : register(t2);
ByteAddressBuffer _401 : register(t3);
RWByteAddressBuffer _537 : register(u0);
cbuffer RFParams
{
    int P_hop : packoffset(c0);
    int P_overlap : packoffset(c0.y);
    int P_delay : packoffset(c0.z);
    int P_blocks : packoffset(c0.w);
    float P_scale : packoffset(c1);
    float P_signalLevel : packoffset(c1.y);
    float P_noiseSigma : packoffset(c1.z);
    int P_noiseKey : packoffset(c1.w);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

int reverse12(inout int x)
{
    int y = 0;
    for (int b = 0; b < 12; b++)
    {
        y = (y << 1) | (x & 1);
        x = x >> 1;
    }
    return y;
}

uint codeAt(int i)
{
    uint w = _327.Load((i >> 1) * 4 + 0);
    uint _336;
    if ((i & 1) != 0)
    {
        _336 = w >> 16u;
    }
    else
    {
        _336 = w & 65535u;
    }
    return _336;
}

uint lowbias(inout uint x)
{
    x ^= (x >> 16u);
    x *= 2146121005u;
    x ^= (x >> 15u);
    x *= 2221713035u;
    x ^= (x >> 16u);
    return x;
}

float rn_log(float xin)
{
    ResType _185;
    _185._m0 = frexp(xin, _185._m1);
    int e = _185._m1;
    float m = _185._m0;
    float x;
    if (m < 0.707106769084930419921875f)
    {
        e--;
        precise float _198 = m + m;
        precise float _199 = _198 - 1.0f;
        x = _199;
    }
    else
    {
        precise float _202 = m - 1.0f;
        x = _202;
    }
    precise float _206 = x * x;
    float z = _206;
    float p = 0.070376835763454437255859375f;
    precise float _211 = p * x;
    precise float _213 = _211 - 0.115146100521087646484375f;
    p = _213;
    precise float _216 = p * x;
    precise float _218 = _216 + 0.11676998436450958251953125f;
    p = _218;
    precise float _221 = p * x;
    precise float _223 = _221 - 0.124201409518718719482421875f;
    p = _223;
    precise float _226 = p * x;
    precise float _228 = _226 + 0.14249323308467864990234375f;
    p = _228;
    precise float _231 = p * x;
    precise float _233 = _231 - 0.1666805744171142578125f;
    p = _233;
    precise float _236 = p * x;
    precise float _238 = _236 + 0.200007140636444091796875f;
    p = _238;
    precise float _241 = p * x;
    precise float _243 = _241 - 0.249999940395355224609375f;
    p = _243;
    precise float _246 = p * x;
    precise float _248 = _246 + 0.333333313465118408203125f;
    p = _248;
    precise float _252 = p * x;
    precise float _254 = _252 * z;
    float y = _254;
    float fe = float(e);
    precise float _261 = (-0.00021219444170128554105758666992188f) * fe;
    precise float _262 = y + _261;
    y = _262;
    precise float _266 = (-0.5f) * z;
    precise float _267 = y + _266;
    y = _267;
    precise float _271 = x + y;
    float r = _271;
    precise float _275 = 0.693359375f * fe;
    precise float _276 = r + _275;
    r = _276;
    return r;
}

float rn_cos(float x)
{
    precise float _95 = x * 0.636619746685028076171875f;
    precise float _97 = _95 + 0.5f;
    float q = floor(_97);
    precise float _103 = q * 1.5703125f;
    precise float _104 = x - _103;
    precise float _107 = q * 0.0004837512969970703125f;
    precise float _108 = _104 - _107;
    precise float _111 = q * 7.5497901264043321134522557258606e-08f;
    precise float _112 = _108 - _111;
    float r = _112;
    int quadrant = int(q) & 3;
    precise float _121 = r * r;
    float z = _121;
    precise float _125 = (-0.00019515295571181923151016235351562f) * z;
    precise float _127 = _125 + 0.00833216123282909393310546875f;
    precise float _129 = _127 * z;
    precise float _131 = _129 - 0.16666655242443084716796875f;
    precise float _133 = _131 * z;
    precise float _135 = _133 * r;
    precise float _137 = _135 + r;
    float s = _137;
    precise float _141 = 2.4433156795566901564598083496094e-05f * z;
    precise float _143 = _141 - 0.00138873164542019367218017578125f;
    precise float _145 = _143 * z;
    precise float _147 = _145 + 0.0416666455566883087158203125f;
    precise float _149 = _147 * z;
    precise float _151 = _149 * z;
    precise float _153 = 0.5f * z;
    precise float _154 = _151 - _153;
    precise float _156 = _154 + 1.0f;
    float c = _156;
    if (quadrant == 0)
    {
        return c;
    }
    if (quadrant == 1)
    {
        return -s;
    }
    if (quadrant == 2)
    {
        return -c;
    }
    return s;
}

float gaussAt(int pos, int key)
{
    uint k = uint(key);
    uint param = (uint(pos) * 2u) ^ k;
    uint _291 = lowbias(param);
    float u1 = (float(_291) + 0.5f) / 4294967296.0f;
    uint param_1 = ((uint(pos) * 2u) + 1u) ^ k;
    uint _305 = lowbias(param_1);
    float u2 = (float(_305) + 0.5f) / 4294967296.0f;
    float param_2 = u1;
    float param_3 = 6.283185482025146484375f * u2;
    return sqrt((-2.0f) * rn_log(param_2)) * rn_cos(param_3);
}

float rfInitAt(int pos)
{
    float v = 0.3120000064373016357421875f;
    if ((pos >= 0) && (pos < 654720))
    {
        int row = pos / 2728;
        int n = pos % 2728;
        int phase = (n + int(_370.Load(row * 4 + 0))) % 12;
        if ((n >= 36) && (n < 2084))
        {
            int param = (row * 256) + ((n - 36) / 8);
            int code = int(codeAt(param));
            v = asfloat(_401.Load(((phase * 512) + code) * 4 + 0));
        }
        else
        {
            if ((n >= 2244) && (n < 2444))
            {
                v = 0.048000000417232513427734375f;
            }
            else
            {
                if ((n >= 2476) && (n < 2596))
                {
                    v = (((8 + phase) % 12) < 6) ? 0.523999989032745361328125f : 0.1480000019073486328125f;
                }
            }
        }
    }
    bool _444 = (pos >= 0) && (pos < 654720);
    bool _455;
    if (_444)
    {
        _455 = P_noiseSigma > 0.0f;
    }
    else
    {
        _455 = _444;
    }
    float _456;
    if (_455)
    {
        int param_1 = pos;
        int param_2 = P_noiseKey;
        precise float _469 = P_noiseSigma * gaussAt(param_1, param_2);
        _456 = _469;
    }
    else
    {
        _456 = 0.0f;
    }
    float _noise = _456;
    precise float _477 = v - 0.048000000417232513427734375f;
    precise float _478 = P_scale * _477;
    precise float _479 = 1.0f - _478;
    precise float _483 = _479 * P_signalLevel;
    precise float _485 = _483 + _noise;
    float r = _485;
    return r;
}

float rfInitValue(int x, int block)
{
    int param = x;
    int _501 = reverse12(param);
    int param_1 = (((block * P_hop) + P_delay) - P_overlap) + _501;
    return rfInitAt(param_1);
}

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _519 = g.x >= 4096u;
    bool _529;
    if (!_519)
    {
        _529 = int(g.y) >= P_blocks;
    }
    else
    {
        _529 = _519;
    }
    if (_529)
    {
        return;
    }
    int param = int(g.x);
    int param_1 = int(g.y);
    _537.Store2(((g.y * 4096u) + g.x) * 8 + 0, asuint(float2(rfInitValue(param, param_1), 0.0f)));
}

[numthreads(64, 4, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
