// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/rf_inverse_tg.comp - do not edit.
// glsl-sha256: b3abe3fc8c58466c91cd2765e20198976769145cc6a51b2535e0a5efd5375401
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(512u, 1u, 1u);

ByteAddressBuffer _91 : register(t3);
ByteAddressBuffer _225 : register(t0);
ByteAddressBuffer _269 : register(t2);
RWByteAddressBuffer _343 : register(u1);
cbuffer RFParams
{
    int P_hop : packoffset(c0);
    int P_overlap : packoffset(c0.y);
    int P_delay : packoffset(c0.z);
    int P_blocks : packoffset(c0.w);
    float P_scale : packoffset(c1);
    float P_signalLevel : packoffset(c1.y);
    float P_noiseSigma : packoffset(c1.z);
    int P_noiseKey : packoffset(c1.w);
};


static uint3 gl_WorkGroupID;
static uint3 gl_LocalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_WorkGroupID : SV_GroupID;
    uint3 gl_LocalInvocationID : SV_GroupThreadID;
};

groupshared float2 buf[4096];

int reverse12(inout int x)
{
    int y = 0;
    for (int b = 0; b < 12; b++)
    {
        y = (y << 1) | (x & 1);
        x = x >> 1;
    }
    return y;
}

float2 cmul(float2 a, float2 b)
{
    precise float _62 = a.x * b.x;
    precise float _68 = a.y * b.y;
    precise float _69 = _62 - _68;
    float re = _69;
    precise float _75 = a.x * b.y;
    precise float _80 = a.y * b.x;
    precise float _81 = _75 + _80;
    float im = _81;
    return float2(re, im);
}

float2 twv(int k, float s)
{
    float2 p = asfloat(_91.Load2(k * 8 + 0));
    return float2(p.x, s * p.y);
}

void fftStagesTG(float sgn)
{
    uint tid = gl_LocalInvocationID.x;
    uint nthreads = 512u;
    for (int span = 2; span <= 4096; span *= 2)
    {
        int h = span / 2;
        int _step = 4096 / span;
        int _133 = int(tid);
        for (int p = _133; p < 2048; p += int(nthreads))
        {
            int j = p % h;
            int i0 = ((p / h) * span) + j;
            int i1 = i0 + h;
            float2 a = buf[i0];
            int param = j * _step;
            float param_1 = sgn;
            float2 param_2 = buf[i1];
            float2 param_3 = twv(param, param_1);
            float2 t = cmul(param_2, param_3);
            precise float2 _184 = a + t;
            float2 s0 = _184;
            precise float2 _188 = a - t;
            float2 s1 = _188;
            buf[i0] = s0;
            buf[i1] = s1;
        }
        GroupMemoryBarrierWithGroupSync();
    }
}

void comp_main()
{
    uint tid = gl_LocalInvocationID.x;
    uint nthreads = 512u;
    uint blk = gl_WorkGroupID.x;
    int _213 = int(tid);
    for (int i = _213; i < 4096; i += int(nthreads))
    {
        buf[i] = asfloat(_225.Load2(((blk * 4096u) + uint(i)) * 8 + 0));
    }
    GroupMemoryBarrierWithGroupSync();
    int _240 = int(tid);
    for (int i_1 = _240; i_1 < 4096; i_1 += int(nthreads))
    {
        int param = i_1;
        int _251 = reverse12(param);
        int j = _251;
        if (i_1 < j)
        {
            float2 a = buf[i_1];
            float2 b = buf[j];
            float2 param_1 = b;
            float2 param_2 = asfloat(_269.Load2(j * 8 + 0));
            buf[i_1] = cmul(param_1, param_2);
            float2 param_3 = a;
            float2 param_4 = asfloat(_269.Load2(i_1 * 8 + 0));
            buf[j] = cmul(param_3, param_4);
        }
        else
        {
            if (i_1 == j)
            {
                float2 param_5 = buf[i_1];
                float2 param_6 = asfloat(_269.Load2(i_1 * 8 + 0));
                buf[i_1] = cmul(param_5, param_6);
            }
        }
    }
    GroupMemoryBarrierWithGroupSync();
    float param_7 = 1.0f;
    fftStagesTG(param_7);
    int _313 = int(tid);
    for (int k = _313; k < P_hop; k += int(nthreads))
    {
        int n = (int(blk) * P_hop) + k;
        if (n < 654720)
        {
            _343.Store2(n * 8 + 0, asuint(buf[k + P_overlap] / 4096.0f.xx));
        }
    }
}

[numthreads(512, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_WorkGroupID = stage_input.gl_WorkGroupID;
    gl_LocalInvocationID = stage_input.gl_LocalInvocationID;
    comp_main();
}
