// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/rf_multiply.comp - do not edit.
// glsl-sha256: 0370a68879f5c8b8385c3e04761cd23dfe4bac62d1058ba8826c16b5932c743d
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(32u, 8u, 1u);

RWByteAddressBuffer _118 : register(u1);
ByteAddressBuffer _128 : register(t0);
ByteAddressBuffer _139 : register(t2);
cbuffer FFTParams
{
    int P_span : packoffset(c0);
    float P_signValue : packoffset(c0.y);
    int P_blocks : packoffset(c0.z);
    int P_pad : packoffset(c0.w);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

int reverse12(inout int x)
{
    int y = 0;
    for (int b = 0; b < 12; b++)
    {
        y = (y << 1) | (x & 1);
        x = x >> 1;
    }
    return y;
}

float2 cmul(float2 a, float2 b)
{
    precise float _53 = a.x * b.x;
    precise float _59 = a.y * b.y;
    precise float _60 = _53 - _59;
    float re = _60;
    precise float _66 = a.x * b.y;
    precise float _71 = a.y * b.x;
    precise float _72 = _66 + _71;
    float im = _72;
    return float2(re, im);
}

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _90 = g.x >= 4096u;
    bool _105;
    if (!_90)
    {
        _105 = int(g.y) >= P_blocks;
    }
    else
    {
        _105 = _90;
    }
    if (_105)
    {
        return;
    }
    int param = int(g.x);
    int _114 = reverse12(param);
    int j = _114;
    float2 param_1 = asfloat(_128.Load2(((int(g.y) * 4096) + j) * 8 + 0));
    float2 param_2 = asfloat(_139.Load2(j * 8 + 0));
    _118.Store2(((g.y * 4096u) + g.x) * 8 + 0, asuint(cmul(param_1, param_2)));
}

[numthreads(32, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
