// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/row_mean_fast.comp - do not edit.
// glsl-sha256: 0cca0f7a3cf40d09b4c5817e4bb6cf08dffea3b8ecba0db8d432edfc77eb71ba
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(128u, 1u, 1u);

ByteAddressBuffer _44 : register(t0);
RWByteAddressBuffer _103 : register(u1);

static uint3 gl_WorkGroupID;
static uint3 gl_LocalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_WorkGroupID : SV_GroupID;
    uint3 gl_LocalInvocationID : SV_GroupThreadID;
};

groupshared float3 part[128];

void comp_main()
{
    int row = int(gl_WorkGroupID.x);
    int t = int(gl_LocalInvocationID.x);
    float3 s = 0.0f.xxx;
    for (int x = t; x < 512; x += 128)
    {
        s += asfloat(_44.Load4(((row * 512) + x) * 16 + 0)).xyz;
    }
    part[t] = s;
    GroupMemoryBarrierWithGroupSync();
    for (int w = 64; w > 0; w = w >> 1)
    {
        if (t < w)
        {
            part[t] += part[t + w];
        }
        GroupMemoryBarrierWithGroupSync();
    }
    if (t == 0)
    {
        _103.Store4(row * 16 + 0, asuint(float4(part[0] / 512.0f.xxx, 1.0f)));
    }
}

[numthreads(128, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_WorkGroupID = stage_input.gl_WorkGroupID;
    gl_LocalInvocationID = stage_input.gl_LocalInvocationID;
    comp_main();
}
