// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/rx_agc.comp - do not edit.
// glsl-sha256: 91f42a8be26bf69da541678b74b7312ade3d56e476ccc823c8845983a6e76ed6
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(1u, 1u, 1u);

RWByteAddressBuffer _41 : register(u2);
ByteAddressBuffer _68 : register(t0);
RWByteAddressBuffer _132 : register(u1);
cbuffer AGCParams
{
    float P_lineSeconds : packoffset(c0);
    float P_attack : packoffset(c0.y);
    float P_release : packoffset(c0.z);
    float P_minGain : packoffset(c0.w);
    float P_maxGain : packoffset(c1);
    int P_enabled : packoffset(c1.y);
    int P_delay : packoffset(c1.z);
    int P_pad : packoffset(c1.w);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

void comp_main()
{
    if (gl_GlobalInvocationID.x != 0u)
    {
        return;
    }
    float lo = log(P_minGain);
    float hi = log(P_maxGain);
    float gain = asfloat(_41.Load(0));
    float logGain = log(gain);
    float lost = 0.0f;
    float _161;
    for (int row = 0; row < 240; row++)
    {
        float gainBefore = gain;
        float4 s = asfloat(_68.Load4(row * 16 + 0));
        bool _85 = (((row * 2728) + 2324) - P_delay) >= 0;
        bool _97;
        if (_85)
        {
            _97 = (((row * 2728) + 2363) + P_delay) < 654720;
        }
        else
        {
            _97 = _85;
        }
        bool gateValid = _97;
        float detectedSync = gainBefore * s.w;
        float amplitude = (gainBefore * sqrt((s.y * s.y) + (s.z * s.z))) / 0.831749022006988525390625f;
        if (amplitude < 9.9999999600419720025001879548654e-13f)
        {
            lost = 1.0f;
        }
        _132.Store(row * 4 + 0, asuint(gainBefore));
        bool controlGate = ((P_enabled != 0) && gateValid) && (detectedSync > 0.0f);
        if (controlGate)
        {
            float desired = clamp(logGain - log(detectedSync), lo, hi);
            if (desired < logGain)
            {
                _161 = P_attack;
            }
            else
            {
                _161 = P_release;
            }
            float tau = _161;
            float fraction = 1.0f - exp((-P_lineSeconds) / tau);
            logGain = clamp(logGain + ((desired - logGain) * fraction), lo, hi);
            gain = clamp(exp(logGain), P_minGain, P_maxGain);
        }
    }
    _41.Store4(0, asuint(float4(gain, lost, 0.0f, 0.0f)));
}

[numthreads(1, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
