// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/rx_agc_fast.comp - do not edit.
// glsl-sha256: 1772c19e0a3a0aef34c8f48307ed1f8463923acd38df3d977c45b8e064529a18
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(256u, 1u, 1u);

ByteAddressBuffer _35 : register(t0);
RWByteAddressBuffer _90 : register(u2);
RWByteAddressBuffer _175 : register(u1);
cbuffer AGCParams
{
    float P_lineSeconds : packoffset(c0);
    float P_attack : packoffset(c0.y);
    float P_release : packoffset(c0.z);
    float P_minGain : packoffset(c0.w);
    float P_maxGain : packoffset(c1);
    int P_enabled : packoffset(c1.y);
    int P_delay : packoffset(c1.z);
    int P_pad : packoffset(c1.w);
};


static uint3 gl_LocalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_LocalInvocationID : SV_GroupThreadID;
};

groupshared float2 target[240];
groupshared float logg[240];
groupshared float g0T;

void comp_main()
{
    int t = int(gl_LocalInvocationID.x);
    if (t < 240)
    {
        target[t] = asfloat(_35.Load4(t * 16 + 0)).xy;
    }
    GroupMemoryBarrierWithGroupSync();
    if (t == 0)
    {
        float lo = log(P_minGain);
        float hi = log(P_maxGain);
        float fa = 1.0f - exp((-P_lineSeconds) / P_attack);
        float fr = 1.0f - exp((-P_lineSeconds) / P_release);
        float g0 = asfloat(_90.Load(0));
        float lg = log(g0);
        bool changed = false;
        for (int r = 0; r < 240; r++)
        {
            logg[r] = changed ? lg : 1000000015047466219876688855040.0f;
            float2 q = target[r];
            if (q.y != 0.0f)
            {
                lg = clamp(lg + ((q.x - lg) * ((q.x < lg) ? fa : fr)), lo, hi);
                changed = true;
            }
        }
        float _151;
        if (changed)
        {
            _151 = clamp(exp(lg), P_minGain, P_maxGain);
        }
        else
        {
            _151 = g0;
        }
        _90.Store4(0, asuint(float4(_151, 0.0f, 0.0f, 0.0f)));
        g0T = g0;
    }
    GroupMemoryBarrierWithGroupSync();
    if (t < 240)
    {
        float _182;
        if (logg[t] > 100000001504746621987668885504.0f)
        {
            _182 = g0T;
        }
        else
        {
            _182 = clamp(exp(logg[t]), P_minGain, P_maxGain);
        }
        _175.Store(t * 4 + 0, asuint(_182));
    }
}

[numthreads(256, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_LocalInvocationID = stage_input.gl_LocalInvocationID;
    comp_main();
}
