// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/rx_decode.comp - do not edit.
// glsl-sha256: 277a7d7ef612ce5aff618a23cd3b15bbe82e7b087f34fee4f7b927f761f57042
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(32u, 8u, 1u);

ByteAddressBuffer _51 : register(t1);
ByteAddressBuffer _62 : register(t2);
ByteAddressBuffer _102 : register(t0);
RWByteAddressBuffer _231 : register(u3);

static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _21 = g.x >= 512u;
    bool _30;
    if (!_21)
    {
        _30 = g.y >= 240u;
    }
    else
    {
        _30 = _21;
    }
    if (_30)
    {
        return;
    }
    int px = int(g.x);
    int py = int(g.y);
    float4 stat = asfloat(_51.Load4(py * 16 + 0));
    float gn = asfloat(_62.Load(py * 4 + 0));
    float lengthC = length(stat.yz);
    float2 rot = float2(-stat.y, stat.z) / max(lengthC, 1.0000000031710768509710513471353e-30f).xx;
    float Y = 0.0f;
    float2 CS = 0.0f.xx;
    for (int k = 0; k < 3; k++)
    {
        precise float _115 = Y + asfloat(_102.Load(((((py * 682) + px) + 8) + k) * 16 + 0));
        Y = _115;
    }
    for (int k_1 = 0; k_1 < 12; k_1++)
    {
        precise float2 _139 = CS + asfloat(_102.Load4(((((py * 682) + px) + 3) + k_1) * 16 + 0)).yz;
        CS = _139;
    }
    precise float _145 = gn / 0.65541827678680419921875f;
    float factor = _145;
    precise float _148 = factor / 12.0f;
    precise float _150 = Y * _148;
    Y = _150;
    float u = (((CS.x * rot.x) - (CS.y * rot.y)) * factor) * (-0.0416666679084300994873046875f);
    float cv = (((CS.y * rot.x) + (CS.x * rot.y)) * factor) * 0.0416666679084300994873046875f;
    float I = (0.838670551776885986328125f * cv) - (0.544639050960540771484375f * u);
    float Q = (0.544639050960540771484375f * cv) + (0.838670551776885986328125f * u);
    float3 rgb = float3((Y + (0.95599997043609619140625f * I)) + (0.620999991893768310546875f * Q), (Y - (0.272000014781951904296875f * I)) - (0.647000014781951904296875f * Q), (Y - (1.10599994659423828125f * I)) + (1.70299994945526123046875f * Q));
    _231.Store4(((py * 512) + px) * 16 + 0, asuint(float4(pow(clamp(rgb, 0.0f.xxx, 1.0f.xxx), 2.2000000476837158203125f.xxx), 1.0f)));
}

[numthreads(32, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
