// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/rx_decode_fast.comp - do not edit.
// glsl-sha256: 39aceada88b10d680adfc683f14635490cc9eb36d55c45703cf9df8119d67c6f
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(256u, 1u, 1u);

ByteAddressBuffer _34 : register(t2);
ByteAddressBuffer _77 : register(t0);
ByteAddressBuffer _106 : register(t1);
ByteAddressBuffer _148 : register(t3);
RWByteAddressBuffer _320 : register(u4);
RWByteAddressBuffer _376 : register(u5);

static uint3 gl_WorkGroupID;
static uint3 gl_LocalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_WorkGroupID : SV_GroupID;
    uint3 gl_LocalInvocationID : SV_GroupThreadID;
};

groupshared float3 prep[682];
groupshared float3 part[256];

void comp_main()
{
    int py = int(gl_WorkGroupID.x);
    int t = int(gl_LocalInvocationID.x);
    int c = py * 2728;
    float4 stat = asfloat(_34.Load4(py * 16 + 0));
    float porch = stat.x;
    for (int px = t; px < 682; px += 256)
    {
        float Y = 0.0f;
        float C = 0.0f;
        float S = 0.0f;
        for (int k = 0; k < 4; k++)
        {
            int n = (px * 4) + k;
            Y += (porch - asfloat(_77.Load((c + n) * 4 + 0)));
            n = min((n + 2), 2727);
            float a = porch - asfloat(_77.Load((c + n) * 4 + 0));
            float2 b = asfloat(_106.Load2(n * 8 + 0));
            C += (a * b.x);
            S += (a * b.y);
        }
        prep[px] = float3(Y, C, S);
    }
    GroupMemoryBarrierWithGroupSync();
    float gn = asfloat(_148.Load(py * 4 + 0));
    float lengthC = length(stat.yz);
    float2 rot = float2(-stat.y, stat.z) / max(lengthC, 1.0000000031710768509710513471353e-30f).xx;
    float factor = gn / 0.65541827678680419921875f;
    float3 total = 0.0f.xxx;
    for (int px_1 = t; px_1 < 512; px_1 += 256)
    {
        float Y_1 = 0.0f;
        float2 CS = 0.0f.xx;
        for (int k_1 = 0; k_1 < 3; k_1++)
        {
            Y_1 += prep[(px_1 + 8) + k_1].x;
        }
        for (int k_2 = 0; k_2 < 12; k_2++)
        {
            CS += prep[(px_1 + 3) + k_2].yz;
        }
        Y_1 *= (factor / 12.0f);
        float u = (((CS.x * rot.x) - (CS.y * rot.y)) * factor) * (-0.0416666679084300994873046875f);
        float cv = (((CS.y * rot.x) + (CS.x * rot.y)) * factor) * 0.0416666679084300994873046875f;
        float I = (0.838670551776885986328125f * cv) - (0.544639050960540771484375f * u);
        float Q = (0.544639050960540771484375f * cv) + (0.838670551776885986328125f * u);
        float3 rgb = float3((Y_1 + (0.95599997043609619140625f * I)) + (0.620999991893768310546875f * Q), (Y_1 - (0.272000014781951904296875f * I)) - (0.647000014781951904296875f * Q), (Y_1 - (1.10599994659423828125f * I)) + (1.70299994945526123046875f * Q));
        rgb = pow(clamp(rgb, 0.0f.xxx, 1.0f.xxx), 2.2000000476837158203125f.xxx);
        _320.Store4(((py * 512) + px_1) * 16 + 0, asuint(float4(rgb, 1.0f)));
        total += rgb;
    }
    part[t] = total;
    GroupMemoryBarrierWithGroupSync();
    for (int w = 128; w > 0; w = w >> 1)
    {
        if (t < w)
        {
            part[t] += part[t + w];
        }
        GroupMemoryBarrierWithGroupSync();
    }
    if (t == 0)
    {
        _376.Store4(py * 16 + 0, asuint(float4(part[0] / 512.0f.xxx, 1.0f)));
    }
}

[numthreads(256, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_WorkGroupID = stage_input.gl_WorkGroupID;
    gl_LocalInvocationID = stage_input.gl_LocalInvocationID;
    comp_main();
}
