// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/rx_prepare.comp - do not edit.
// glsl-sha256: ade8b4b9d85f4fec0ec71b2bcf948a7496c4653f87ff8877817f0f2ae6ce8dca
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(32u, 8u, 1u);

ByteAddressBuffer _51 : register(t2);
ByteAddressBuffer _80 : register(t0);
ByteAddressBuffer _110 : register(t1);
RWByteAddressBuffer _133 : register(u3);

static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _21 = g.x >= 682u;
    bool _30;
    if (!_21)
    {
        _30 = g.y >= 240u;
    }
    else
    {
        _30 = _21;
    }
    if (_30)
    {
        return;
    }
    int px = int(g.x);
    int py = int(g.y);
    float porch = asfloat(_51.Load(py * 16 + 0));
    float Y = 0.0f;
    float C = 0.0f;
    float S = 0.0f;
    for (int k = 0; k < 4; k++)
    {
        int n = (px * 4) + k;
        precise float _88 = porch - asfloat(_80.Load(((py * 2728) + n) * 8 + 0));
        precise float _90 = Y + _88;
        Y = _90;
        n = min((n + 2), 2727);
        precise float _104 = porch - asfloat(_80.Load(((py * 2728) + n) * 8 + 0));
        float a = _104;
        float2 b = asfloat(_110.Load2(n * 8 + 0));
        precise float _118 = a * b.x;
        precise float _120 = C + _118;
        C = _120;
        precise float _124 = a * b.y;
        precise float _126 = S + _124;
        S = _126;
    }
    _133.Store4(((py * 682) + px) * 16 + 0, asuint(float4(Y, C, S, 0.0f)));
}

[numthreads(32, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
