// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/rx_reduce.comp - do not edit.
// glsl-sha256: ab784901667fa1a3468386c481052d851b048d1b355ba5b69ed6a1092f8f7c86
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(64u, 1u, 1u);

ByteAddressBuffer _49 : register(t0);
ByteAddressBuffer _86 : register(t1);
RWByteAddressBuffer _130 : register(u2);

static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

void comp_main()
{
    uint g = gl_GlobalInvocationID.x;
    if (g >= 240u)
    {
        return;
    }
    int y = int(g);
    float porch = 0.0f;
    float bc = 0.0f;
    float bs = 0.0f;
    float sync = 0.0f;
    for (int n = 2172; n < 2244; n++)
    {
        precise float _60 = porch + asfloat(_49.Load(((y * 2728) + n) * 8 + 0));
        porch = _60;
    }
    for (int n_1 = 2476; n_1 < 2596; n_1++)
    {
        float a = asfloat(_49.Load(((y * 2728) + n_1) * 8 + 0));
        float2 b = asfloat(_86.Load2(n_1 * 8 + 0));
        precise float _94 = a * b.x;
        precise float _96 = bc + _94;
        bc = _96;
        precise float _101 = a * b.y;
        precise float _103 = bs + _101;
        bs = _103;
    }
    for (int n_2 = 2324; n_2 < 2364; n_2++)
    {
        precise float _123 = sync + asfloat(_49.Load(((y * 2728) + n_2) * 8 + 0));
        sync = _123;
    }
    _130.Store4(y * 16 + 0, asuint(float4(porch / 72.0f, bc / 60.0f, bs / 60.0f, sync / 40.0f)));
}

[numthreads(64, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
