// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/rx_stats_fast.comp - do not edit.
// glsl-sha256: e5a87fffd13b689c40c0d09cf07adeb4d043f6b04c197b870217a39855ed2212
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(64u, 1u, 1u);

ByteAddressBuffer _50 : register(t0);
ByteAddressBuffer _87 : register(t1);
RWByteAddressBuffer _186 : register(u2);
RWByteAddressBuffer _234 : register(u3);
cbuffer AGCParams
{
    float P_lineSeconds : packoffset(c0);
    float P_attack : packoffset(c0.y);
    float P_release : packoffset(c0.z);
    float P_minGain : packoffset(c0.w);
    float P_maxGain : packoffset(c1);
    int P_enabled : packoffset(c1.y);
    int P_delay : packoffset(c1.z);
    int P_pad : packoffset(c1.w);
};


static uint3 gl_WorkGroupID;
static uint3 gl_LocalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_WorkGroupID : SV_GroupID;
    uint3 gl_LocalInvocationID : SV_GroupThreadID;
};

groupshared float4 part[64];

void comp_main()
{
    int y = int(gl_WorkGroupID.x);
    int t = int(gl_LocalInvocationID.x);
    int c = y * 2728;
    float porch = 0.0f;
    float bc = 0.0f;
    float bs = 0.0f;
    float sync = 0.0f;
    int _37 = 2172 + t;
    for (int n = _37; n < 2244; n += 64)
    {
        porch += asfloat(_50.Load((c + n) * 4 + 0));
    }
    int _66 = 2476 + t;
    for (int n_1 = _66; n_1 < 2596; n_1 += 64)
    {
        float a = asfloat(_50.Load((c + n_1) * 4 + 0));
        float2 b = asfloat(_87.Load2(n_1 * 8 + 0));
        bc += (a * b.x);
        bs += (a * b.y);
    }
    int _110 = 2324 + t;
    for (int n_2 = _110; n_2 < 2364; n_2 += 64)
    {
        sync += asfloat(_50.Load((c + n_2) * 4 + 0));
    }
    part[t] = float4(porch, bc, bs, sync);
    GroupMemoryBarrierWithGroupSync();
    for (int w = 32; w > 0; w = w >> 1)
    {
        if (t < w)
        {
            part[t] += part[t + w];
        }
        GroupMemoryBarrierWithGroupSync();
    }
    if (t == 0)
    {
        float4 s = part[0] / float4(72.0f, 60.0f, 60.0f, 40.0f);
        _186.Store4(y * 16 + 0, asuint(s));
        bool _204 = (((y * 2728) + 2324) - P_delay) >= 0;
        bool _216;
        if (_204)
        {
            _216 = (((y * 2728) + 2363) + P_delay) < 654720;
        }
        else
        {
            _216 = _204;
        }
        bool gateValid = _216;
        bool _223 = (P_enabled != 0) && gateValid;
        bool _230;
        if (_223)
        {
            _230 = s.w > 0.0f;
        }
        else
        {
            _230 = _223;
        }
        bool control = _230;
        float _237;
        if (control)
        {
            _237 = clamp(-log(s.w), log(P_minGain), log(P_maxGain));
        }
        else
        {
            _237 = 0.0f;
        }
        _234.Store4(y * 16 + 0, asuint(float4(_237, float(control), 0.0f, 0.0f)));
    }
}

[numthreads(64, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_WorkGroupID = stage_input.gl_WorkGroupID;
    gl_LocalInvocationID = stage_input.gl_LocalInvocationID;
    comp_main();
}
