// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/scatter_drive.comp - do not edit.
// glsl-sha256: d9bcdbbed288b898e7d450f1ade7d96845b93b26c010eb95813d4a1b177a3c92
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(32u, 8u, 1u);

ByteAddressBuffer _115 : register(t0);
ByteAddressBuffer _131 : register(t1);
RWByteAddressBuffer _147 : register(u2);
cbuffer ScatterParams
{
    int P_rows : packoffset(c0);
    int P_ry : packoffset(c0.y);
    int P_pad0 : packoffset(c0.z);
    int P_pad1 : packoffset(c0.w);
    float4 P_kappa : packoffset(c1);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

uint spvPackHalf2x16(float2 value)
{
    uint2 Packed = f32tof16(value);
    return Packed.x | (Packed.y << 16);
}

float2 spvUnpackHalf2x16(uint value)
{
    return f16tof32(uint2(value & 0xffff, value >> 16));
}

float4 unpackH4(uint2 h)
{
    return float4(spvUnpackHalf2x16(h.x), spvUnpackHalf2x16(h.y));
}

uint2 packH4(float4 v)
{
    return uint2(spvPackHalf2x16(v.xy), spvPackHalf2x16(v.zw));
}

void comp_main()
{
    int x = int(gl_GlobalInvocationID.x);
    int y = int(gl_GlobalInvocationID.y);
    bool _63 = x >= 512;
    bool _76;
    if (!_63)
    {
        _76 = y >= P_rows;
    }
    else
    {
        _76 = _63;
    }
    if (_76)
    {
        return;
    }
    float3 s = 0.0f.xxx;
    int lo = max((-P_ry), (-y));
    int hi = min(P_ry, ((P_rows - 1) - y));
    for (int d = lo; d <= hi; d++)
    {
        uint2 param = _115.Load2((((y + d) * 512) + x) * 8 + 0);
        s += (unpackH4(param).xyz * asfloat(_131.Load((d + P_ry) * 4 + 0)));
    }
    float4 param_1 = float4(s * P_kappa.xyz, 1.0f);
    _147.Store2(((y * 512) + x) * 8 + 0, packH4(param_1));
}

[numthreads(32, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
