// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/show.frag - do not edit.
// glsl-sha256: 460da13912c36c92247e524fe7e55329efba22b05d156360792efcced75f96e4
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
ByteAddressBuffer _48 : register(t0);
cbuffer ShowParams
{
    float4 P_dst : packoffset(c0);
    float4 P_src : packoffset(c1);
    int P_ow : packoffset(c2);
    int P_oh : packoffset(c2.y);
    int P_tw : packoffset(c2.z);
    int P_th : packoffset(c2.w);
    float4 P_ndc : packoffset(c3);
};


static float4 gl_FragCoord;
static float4 outColor;

struct SPIRV_Cross_Input
{
    float4 gl_FragCoord : SV_Position;
};

struct SPIRV_Cross_Output
{
    float4 outColor : SV_Target0;
};

float3 tubeAt(inout int x, inout int y)
{
    x = clamp(x, 0, P_ow - 1);
    y = clamp(y, 0, P_oh - 1);
    return asfloat(_48.Load4(((y * P_ow) + x) * 16 + 0)).xyz;
}

float3 showSample(float2 frag)
{
    float u = ((((frag.x - P_dst.x) / P_dst.z) * P_src.z) + P_src.x) - 0.5f;
    float v = ((((frag.y - P_dst.y) / P_dst.w) * P_src.w) + P_src.y) - 0.5f;
    float x0 = floor(u);
    float y0 = floor(v);
    float fx = u - x0;
    float fy = v - y0;
    int ix = int(x0);
    int iy = int(y0);
    int param = ix;
    int param_1 = iy;
    float3 _156 = tubeAt(param, param_1);
    float3 a = _156;
    int param_2 = ix + 1;
    int param_3 = iy;
    float3 _163 = tubeAt(param_2, param_3);
    float3 b = _163;
    int param_4 = ix;
    int param_5 = iy + 1;
    float3 _170 = tubeAt(param_4, param_5);
    float3 c = _170;
    int param_6 = ix + 1;
    int param_7 = iy + 1;
    float3 _178 = tubeAt(param_6, param_7);
    float3 d = _178;
    float3 _182;
    if (fx == 0.0f)
    {
        _182 = a;
    }
    else
    {
        _182 = (a * (1.0f - fx)) + (b * fx);
    }
    float3 top = _182;
    float3 _199;
    if (fx == 0.0f)
    {
        _199 = c;
    }
    else
    {
        _199 = (c * (1.0f - fx)) + (d * fx);
    }
    float3 bot = _199;
    float3 _215;
    if (fy == 0.0f)
    {
        _215 = top;
    }
    else
    {
        _215 = (top * (1.0f - fy)) + (bot * fy);
    }
    return _215;
}

float3 encodeSRGB(inout float3 v)
{
    v = max(0.0f.xxx, v);
    float3 _74 = (pow(v, 0.4166666567325592041015625f.xxx) * 1.05499994754791259765625f) - 0.054999999701976776123046875f.xxx;
    float3 _77 = v * 12.9200000762939453125f;
    bool3 _83 = bool3(v.x <= 0.003130800090730190277099609375f.xxx.x, v.y <= 0.003130800090730190277099609375f.xxx.y, v.z <= 0.003130800090730190277099609375f.xxx.z);
    float3 s = float3(_83.x ? _77.x : _74.x, _83.y ? _77.y : _74.y, _83.z ? _77.z : _74.z);
    return min(s, 1.0f.xxx);
}

void frag_main()
{
    float2 param = gl_FragCoord.xy;
    float3 param_1 = showSample(param);
    float3 _240 = encodeSRGB(param_1);
    outColor = float4(_240, 1.0f);
}

SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
{
    gl_FragCoord = stage_input.gl_FragCoord;
    gl_FragCoord.w = 1.0 / gl_FragCoord.w;
    frag_main();
    SPIRV_Cross_Output stage_output;
    stage_output.outColor = outColor;
    return stage_output;
}
