// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/show_h.frag - do not edit.
// glsl-sha256: 0d3cfc4933422fd4ab2def6c847db4c27aeeff499ce7b7e37501e665cb596ed7
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
ByteAddressBuffer _52 : register(t0);
cbuffer ShowParams
{
    float4 P_dst : packoffset(c0);
    float4 P_src : packoffset(c1);
    int P_ow : packoffset(c2);
    int P_oh : packoffset(c2.y);
    int P_tw : packoffset(c2.z);
    int P_th : packoffset(c2.w);
    float4 P_ndc : packoffset(c3);
};


static float4 gl_FragCoord;
static float4 outColor;

struct SPIRV_Cross_Input
{
    float4 gl_FragCoord : SV_Position;
};

struct SPIRV_Cross_Output
{
    float4 outColor : SV_Target0;
};

uint spvPackHalf2x16(float2 value)
{
    uint2 Packed = f32tof16(value);
    return Packed.x | (Packed.y << 16);
}

float2 spvUnpackHalf2x16(uint value)
{
    return f16tof32(uint2(value & 0xffff, value >> 16));
}

float3 tubeAt(inout int x, inout int y)
{
    x = clamp(x, 0, P_ow - 1);
    y = clamp(y, 0, P_oh - 1);
    uint2 q = _52.Load2(((y * P_ow) + x) * 8 + 0);
    return float3(spvUnpackHalf2x16(q.x), spvUnpackHalf2x16(q.y).x);
}

float3 showSample(float2 frag)
{
    float u = ((((frag.x - P_dst.x) / P_dst.z) * P_src.z) + P_src.x) - 0.5f;
    float v = ((((frag.y - P_dst.y) / P_dst.w) * P_src.w) + P_src.y) - 0.5f;
    float x0 = floor(u);
    float y0 = floor(v);
    float fx = u - x0;
    float fy = v - y0;
    int ix = int(x0);
    int iy = int(y0);
    int param = ix;
    int param_1 = iy;
    float3 _169 = tubeAt(param, param_1);
    float3 a = _169;
    int param_2 = ix + 1;
    int param_3 = iy;
    float3 _176 = tubeAt(param_2, param_3);
    float3 b = _176;
    int param_4 = ix;
    int param_5 = iy + 1;
    float3 _183 = tubeAt(param_4, param_5);
    float3 c = _183;
    int param_6 = ix + 1;
    int param_7 = iy + 1;
    float3 _191 = tubeAt(param_6, param_7);
    float3 d = _191;
    float3 _195;
    if (fx == 0.0f)
    {
        _195 = a;
    }
    else
    {
        _195 = (a * (1.0f - fx)) + (b * fx);
    }
    float3 top = _195;
    float3 _212;
    if (fx == 0.0f)
    {
        _212 = c;
    }
    else
    {
        _212 = (c * (1.0f - fx)) + (d * fx);
    }
    float3 bot = _212;
    float3 _228;
    if (fy == 0.0f)
    {
        _228 = top;
    }
    else
    {
        _228 = (top * (1.0f - fy)) + (bot * fy);
    }
    return _228;
}

float3 encodeSRGB(inout float3 v)
{
    v = max(0.0f.xxx, v);
    float3 _90 = (pow(v, 0.4166666567325592041015625f.xxx) * 1.05499994754791259765625f) - 0.054999999701976776123046875f.xxx;
    float3 _93 = v * 12.9200000762939453125f;
    bool3 _99 = bool3(v.x <= 0.003130800090730190277099609375f.xxx.x, v.y <= 0.003130800090730190277099609375f.xxx.y, v.z <= 0.003130800090730190277099609375f.xxx.z);
    float3 s = float3(_99.x ? _93.x : _90.x, _99.y ? _93.y : _90.y, _99.z ? _93.z : _90.z);
    return min(s, 1.0f.xxx);
}

void frag_main()
{
    float2 param = gl_FragCoord.xy;
    float3 param_1 = showSample(param);
    float3 _253 = encodeSRGB(param_1);
    outColor = float4(_253, 1.0f);
}

SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
{
    gl_FragCoord = stage_input.gl_FragCoord;
    gl_FragCoord.w = 1.0 / gl_FragCoord.w;
    frag_main();
    SPIRV_Cross_Output stage_output;
    stage_output.outColor = outColor;
    return stage_output;
}
