// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/show_kernel_h.comp - do not edit.
// glsl-sha256: 87eaaad5ee7c91d927fd71c81ad77eefad27a895475858db4b5318ac1d290ba2
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(16u, 16u, 1u);

ByteAddressBuffer _52 : register(t0);
RWByteAddressBuffer _340 : register(u1);
cbuffer ShowParams
{
    float4 P_dst : packoffset(c0);
    float4 P_src : packoffset(c1);
    int P_ow : packoffset(c2);
    int P_oh : packoffset(c2.y);
    int P_tw : packoffset(c2.z);
    int P_th : packoffset(c2.w);
    float4 P_ndc : packoffset(c3);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

uint spvPackHalf2x16(float2 value)
{
    uint2 Packed = f32tof16(value);
    return Packed.x | (Packed.y << 16);
}

float2 spvUnpackHalf2x16(uint value)
{
    return f16tof32(uint2(value & 0xffff, value >> 16));
}

float3 tubeAt(inout int x, inout int y)
{
    x = clamp(x, 0, P_ow - 1);
    y = clamp(y, 0, P_oh - 1);
    uint2 q = _52.Load2(((y * P_ow) + x) * 8 + 0);
    return float3(spvUnpackHalf2x16(q.x), spvUnpackHalf2x16(q.y).x);
}

float3 showSample(float2 frag)
{
    float u = ((((frag.x - P_dst.x) / P_dst.z) * P_src.z) + P_src.x) - 0.5f;
    float v = ((((frag.y - P_dst.y) / P_dst.w) * P_src.w) + P_src.y) - 0.5f;
    float x0 = floor(u);
    float y0 = floor(v);
    float fx = u - x0;
    float fy = v - y0;
    int ix = int(x0);
    int iy = int(y0);
    int param = ix;
    int param_1 = iy;
    float3 _169 = tubeAt(param, param_1);
    float3 a = _169;
    int param_2 = ix + 1;
    int param_3 = iy;
    float3 _176 = tubeAt(param_2, param_3);
    float3 b = _176;
    int param_4 = ix;
    int param_5 = iy + 1;
    float3 _183 = tubeAt(param_4, param_5);
    float3 c = _183;
    int param_6 = ix + 1;
    int param_7 = iy + 1;
    float3 _191 = tubeAt(param_6, param_7);
    float3 d = _191;
    float3 _195;
    if (fx == 0.0f)
    {
        _195 = a;
    }
    else
    {
        _195 = (a * (1.0f - fx)) + (b * fx);
    }
    float3 top = _195;
    float3 _212;
    if (fx == 0.0f)
    {
        _212 = c;
    }
    else
    {
        _212 = (c * (1.0f - fx)) + (d * fx);
    }
    float3 bot = _212;
    float3 _228;
    if (fy == 0.0f)
    {
        _228 = top;
    }
    else
    {
        _228 = (top * (1.0f - fy)) + (bot * fy);
    }
    return _228;
}

float3 encodeSRGB(inout float3 v)
{
    v = max(0.0f.xxx, v);
    float3 _90 = (pow(v, 0.4166666567325592041015625f.xxx) * 1.05499994754791259765625f) - 0.054999999701976776123046875f.xxx;
    float3 _93 = v * 12.9200000762939453125f;
    bool3 _99 = bool3(v.x <= 0.003130800090730190277099609375f.xxx.x, v.y <= 0.003130800090730190277099609375f.xxx.y, v.z <= 0.003130800090730190277099609375f.xxx.z);
    float3 s = float3(_99.x ? _93.x : _90.x, _99.y ? _93.y : _90.y, _99.z ? _93.z : _90.z);
    return min(s, 1.0f.xxx);
}

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _256 = int(g.x) >= P_tw;
    bool _267;
    if (!_256)
    {
        _267 = int(g.y) >= P_th;
    }
    else
    {
        _267 = _256;
    }
    if (_267)
    {
        return;
    }
    float2 frag = float2(g) + 0.5f.xx;
    bool _282 = frag.x >= P_dst.x;
    bool _290;
    if (_282)
    {
        _290 = frag.y >= P_dst.y;
    }
    else
    {
        _290 = _282;
    }
    bool _301;
    if (_290)
    {
        _301 = frag.x < (P_dst.x + P_dst.z);
    }
    else
    {
        _301 = _290;
    }
    bool _312;
    if (_301)
    {
        _312 = frag.y < (P_dst.y + P_dst.w);
    }
    else
    {
        _312 = _301;
    }
    bool inside = _312;
    float3 _315;
    if (inside)
    {
        float2 param = frag;
        float3 param_1 = showSample(param);
        float3 _322 = encodeSRGB(param_1);
        _315 = _322;
    }
    else
    {
        _315 = 0.0f.xxx;
    }
    float3 c = _315;
    uint3 q = uint3(floor((clamp(c, 0.0f.xxx, 1.0f.xxx) * 255.0f) + 0.5f.xxx));
    _340.Store(((int(g.y) * P_tw) + int(g.x)) * 4 + 0, ((4278190080u | (q.x << uint(16))) | (q.y << uint(8))) | q.z);
}

[numthreads(16, 16, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
