// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/show.vert - do not edit.
// glsl-sha256: 79565449b367e025e0e7371bfe22ee65900f0180457a7cfe1b53b90f8fe849e1
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
cbuffer ShowParams
{
    float4 P_dst : packoffset(c0);
    float4 P_src : packoffset(c1);
    int P_ow : packoffset(c2);
    int P_oh : packoffset(c2.y);
    int P_tw : packoffset(c2.z);
    int P_th : packoffset(c2.w);
    float4 P_ndc : packoffset(c3);
};


static float4 gl_Position;
static int gl_VertexIndex;
struct SPIRV_Cross_Input
{
    uint gl_VertexIndex : SV_VertexID;
};

struct SPIRV_Cross_Output
{
    float4 gl_Position : SV_Position;
};

void vert_main()
{
    float2 c = float2(float(gl_VertexIndex & 1), float((gl_VertexIndex >> 1) & 1));
    gl_Position = float4(P_ndc.x + (c.x * P_ndc.z), P_ndc.y + (c.y * P_ndc.w), 0.0f, 1.0f);
    gl_Position.y = -gl_Position.y;
}

SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
{
    gl_VertexIndex = int(stage_input.gl_VertexIndex);
    vert_main();
    SPIRV_Cross_Output stage_output;
    stage_output.gl_Position = gl_Position;
    return stage_output;
}
