// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/spot_h.comp - do not edit.
// glsl-sha256: 590412ebce2e99f25c3b0fb62d130384a336eec89c30572d591518675934c76c
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(32u, 8u, 1u);

ByteAddressBuffer _164 : register(t0);
RWByteAddressBuffer _211 : register(u1);
cbuffer SpotParams
{
    int P_width : packoffset(c0);
    int P_rows : packoffset(c0.y);
    int P_radius : packoffset(c0.z);
    float P_k1 : packoffset(c0.w);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

float spotW(float u, int k)
{
    precise float _27 = P_k1 * sqrt(max(u, 0.0f));
    float s = _27;
    if (s <= 9.9999999747524270787835121154785e-07f)
    {
        return float(k == 0);
    }
    float sum = 0.0f;
    int _46 = -P_radius;
    for (int i = _46; i <= P_radius; i++)
    {
        precise float _61 = (-0.5f) * float(i * i);
        precise float _64 = s * s;
        precise float _65 = _61 / _64;
        precise float _68 = sum + exp(_65);
        sum = _68;
    }
    return exp(((-0.5f) * float(k * k)) / (s * s)) / sum;
}

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _102 = int(g.x) >= P_width;
    bool _113;
    if (!_102)
    {
        _113 = int(g.y) >= P_rows;
    }
    else
    {
        _113 = _102;
    }
    if (_113)
    {
        return;
    }
    int px = int(g.x);
    int py = int(g.y);
    float3 acc = 0.0f.xxx;
    int _132 = -P_radius;
    for (int k = _132; k <= P_radius; k++)
    {
        int j = px - k;
        bool _147 = j < 0;
        bool _155;
        if (!_147)
        {
            _155 = j >= P_width;
        }
        else
        {
            _155 = _147;
        }
        if (_155)
        {
            continue;
        }
        float3 u = asfloat(_164.Load4(((py * P_width) + j) * 16 + 0)).xyz;
        float param = u.x;
        int param_1 = k;
        precise float _183 = u.x * spotW(param, param_1);
        float param_2 = u.y;
        int param_3 = k;
        precise float _192 = u.y * spotW(param_2, param_3);
        float param_4 = u.z;
        int param_5 = k;
        precise float _202 = u.z * spotW(param_4, param_5);
        precise float3 _205 = acc + float3(_183, _192, _202);
        acc = _205;
    }
    _211.Store4(((py * P_width) + px) * 16 + 0, asuint(float4(acc, 1.0f)));
}

[numthreads(32, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
