// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/supply_row.comp - do not edit.
// glsl-sha256: 8d456ce8329f8a999fa08463dee7ab3e0b2d0278cd7070b9f33cf3e275e8f9e0
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(64u, 1u, 1u);

ByteAddressBuffer _58 : register(t0);
ByteAddressBuffer _130 : register(t1);
RWByteAddressBuffer _152 : register(u2);
cbuffer SupplyParams
{
    int P_width : packoffset(c0);
    int P_rows : packoffset(c0.y);
    float P_decay : packoffset(c0.z);
    float P_v0 : packoffset(c0.w);
    float P_reff : packoffset(c1);
    float P_imax : packoffset(c1.y);
    float P_n : packoffset(c1.z);
    float P_relax : packoffset(c1.w);
    float P_reqScale : packoffset(c2);
    float P_ablFraction : packoffset(c2.y);
    float P_ilim : packoffset(c2.z);
    float P_pad : packoffset(c2.w);
    float4 P_share : packoffset(c3);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

float supplyLoop(float4 state, int last, inout float req)
{
    float v = state.x;
    float gain = state.z;
    float rq = 0.0f;
    for (int j = 0; j < P_rows; j++)
    {
        if (j > last)
        {
            break;
        }
        float3 u = asfloat(_58.Load4(j * 16 + 0)).xyz;
        float drive = dot(u, P_share.xyz);
        precise float _83 = P_reff * P_imax;
        precise float _85 = _83 * gain;
        precise float _87 = _85 * drive;
        precise float _88 = P_v0 - _87;
        float target = _88;
        precise float _92 = v - target;
        precise float _96 = _92 * P_decay;
        precise float _97 = target + _96;
        v = _97;
        precise float _101 = P_imax * drive;
        precise float _103 = rq + _101;
        rq = _103;
    }
    req = rq;
    return v;
}

void comp_main()
{
    uint g = gl_GlobalInvocationID.x;
    if (int(g) >= P_rows)
    {
        return;
    }
    float4 st = asfloat(_130.Load4(0));
    float4 param = st;
    int param_1 = int(g);
    float param_2;
    float _141 = supplyLoop(param, param_1, param_2);
    float req = param_2;
    float v = _141;
    float m = sqrt(P_v0 / v);
    _152.Store4(g * 16 + 0, asuint(float4(m, (st.z * pow(v / P_v0, P_n)) / m, 0.0f, 1.0f)));
}

[numthreads(64, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
