// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/supply_resample.comp - do not edit.
// glsl-sha256: 02c33181245b0a0991a4af2722709d850ff758b2091fb0fedbe9dd901d7f19eb
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(32u, 8u, 1u);

ByteAddressBuffer _84 : register(t1);
ByteAddressBuffer _134 : register(t0);
RWByteAddressBuffer _178 : register(u2);
cbuffer SupplyParams
{
    int P_width : packoffset(c0);
    int P_rows : packoffset(c0.y);
    float P_decay : packoffset(c0.z);
    float P_v0 : packoffset(c0.w);
    float P_reff : packoffset(c1);
    float P_imax : packoffset(c1.y);
    float P_n : packoffset(c1.z);
    float P_relax : packoffset(c1.w);
    float P_reqScale : packoffset(c2);
    float P_ablFraction : packoffset(c2.y);
    float P_ilim : packoffset(c2.z);
    float P_pad : packoffset(c2.w);
    float4 P_share : packoffset(c3);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

float3 glmix3(float3 x, float3 y, float a)
{
    precise float _20 = 1.0f - a;
    precise float3 _21 = x * _20;
    precise float3 _24 = y * a;
    precise float3 _25 = _21 + _24;
    float3 r = _25;
    return r;
}

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _53 = int(g.x) >= P_width;
    bool _65;
    if (!_53)
    {
        _65 = int(g.y) >= P_rows;
    }
    else
    {
        _65 = _53;
    }
    if (_65)
    {
        return;
    }
    int px = int(g.x);
    int py = int(g.y);
    float2 k = asfloat(_84.Load4(py * 16 + 0)).xy;
    precise float _95 = float(P_width) / 2.0f;
    float halfW = _95;
    precise float _101 = float(px) + 0.5f;
    precise float _103 = _101 - halfW;
    precise float _106 = _103 / k.x;
    precise float _107 = halfW + _106;
    precise float _108 = _107 - 0.5f;
    float sx = _108;
    int x0 = int(floor(sx));
    float t = sx - float(x0);
    bool _120 = x0 >= 0;
    bool _127;
    if (_120)
    {
        _127 = x0 < P_width;
    }
    else
    {
        _127 = _120;
    }
    float3 _128;
    if (_127)
    {
        _128 = asfloat(_134.Load4(((py * P_width) + x0) * 16 + 0)).xyz;
    }
    else
    {
        _128 = 0.0f.xxx;
    }
    float3 a = _128;
    bool _151 = (x0 + 1) >= 0;
    bool _159;
    if (_151)
    {
        _159 = (x0 + 1) < P_width;
    }
    else
    {
        _159 = _151;
    }
    float3 _160;
    if (_159)
    {
        _160 = asfloat(_134.Load4((((py * P_width) + x0) + 1) * 16 + 0)).xyz;
    }
    else
    {
        _160 = 0.0f.xxx;
    }
    float3 b = _160;
    float3 param = a;
    float3 param_1 = b;
    float param_2 = t;
    _178.Store4(((py * P_width) + px) * 16 + 0, asuint(float4(glmix3(param, param_1, param_2) * k.y, 1.0f)));
}

[numthreads(32, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
