// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/supply_state.comp - do not edit.
// glsl-sha256: 70deab79cda6132cf2cc707197b5867195445cefba64a1e755215d7d017a5e3d
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(1u, 1u, 1u);

ByteAddressBuffer _58 : register(t0);
RWByteAddressBuffer _200 : register(u2);
ByteAddressBuffer _211 : register(t1);
cbuffer SupplyParams
{
    int P_width : packoffset(c0);
    int P_rows : packoffset(c0.y);
    float P_decay : packoffset(c0.z);
    float P_v0 : packoffset(c0.w);
    float P_reff : packoffset(c1);
    float P_imax : packoffset(c1.y);
    float P_n : packoffset(c1.z);
    float P_relax : packoffset(c1.w);
    float P_reqScale : packoffset(c2);
    float P_ablFraction : packoffset(c2.y);
    float P_ilim : packoffset(c2.z);
    float P_prime : packoffset(c2.w);
    float4 P_share : packoffset(c3);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

float supplyLoop(float4 state, int last, inout float req)
{
    float v = state.x;
    float gain = state.z;
    float rq = 0.0f;
    for (int j = 0; j < P_rows; j++)
    {
        if (j > last)
        {
            break;
        }
        float3 u = asfloat(_58.Load4(j * 16 + 0)).xyz;
        float drive = dot(u, P_share.xyz);
        precise float _83 = P_reff * P_imax;
        precise float _85 = _83 * gain;
        precise float _87 = _85 * drive;
        precise float _88 = P_v0 - _87;
        float target = _88;
        precise float _92 = v - target;
        precise float _96 = _92 * P_decay;
        precise float _97 = target + _96;
        v = _97;
        precise float _101 = P_imax * drive;
        precise float _103 = rq + _101;
        rq = _103;
    }
    req = rq;
    return v;
}

void comp_main()
{
    if (gl_GlobalInvocationID.x != 0u)
    {
        return;
    }
    if (P_prime != 0.0f)
    {
        float4 param = float4(P_v0, 0.0f, 1.0f, 1.0f);
        int param_1 = P_rows - 1;
        float param_2;
        float _137 = supplyLoop(param, param_1, param_2);
        float req0 = param_2;
        precise float _144 = req0 * P_reqScale;
        float requested = _144;
        float _151;
        if (requested > P_ilim)
        {
            precise float _157 = P_ilim / requested;
            _151 = _157;
        }
        else
        {
            _151 = 1.0f;
        }
        float gain = _151;
        float v = P_v0;
        float param_5;
        for (int i = 0; i < 3; i++)
        {
            float4 param_3 = float4(v, requested, gain, 1.0f);
            int param_4 = P_rows - 1;
            float _182 = supplyLoop(param_3, param_4, param_5);
            float r2 = param_5;
            v = _182;
            precise float _189 = v - P_v0;
            precise float _193 = _189 * P_relax;
            precise float _194 = P_v0 + _193;
            v = _194;
        }
        _200.Store4(0, asuint(float4(v, requested, gain, 1.0f)));
        return;
    }
    float4 st = asfloat(_211.Load4(0));
    float4 param_6 = st;
    int param_7 = P_rows - 1;
    float param_8;
    float _223 = supplyLoop(param_6, param_7, param_8);
    float req = param_8;
    float v_1 = _223;
    precise float _230 = v_1 - P_v0;
    precise float _233 = _230 * P_relax;
    precise float _234 = P_v0 + _233;
    v_1 = _234;
    precise float _242 = req * P_reqScale;
    precise float _245 = _242 - st.y;
    precise float _249 = _245 * P_ablFraction;
    precise float _250 = st.y + _249;
    float requested_1 = _250;
    float _257;
    if (requested_1 > P_ilim)
    {
        _257 = P_ilim / requested_1;
    }
    else
    {
        _257 = 1.0f;
    }
    _200.Store4(0, asuint(float4(v_1, requested_1, _257, 1.0f)));
}

[numthreads(1, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
