// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/supply_mean.comp - do not edit.
// glsl-sha256: c9da84ac8d52d765a5fc1dbb0b4934545189293712afd4d3747884071cbe01c9
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(64u, 1u, 1u);

ByteAddressBuffer _56 : register(t0);
RWByteAddressBuffer _74 : register(u1);
cbuffer SupplyParams
{
    int P_width : packoffset(c0);
    int P_rows : packoffset(c0.y);
    float P_decay : packoffset(c0.z);
    float P_v0 : packoffset(c0.w);
    float P_reff : packoffset(c1);
    float P_imax : packoffset(c1.y);
    float P_n : packoffset(c1.z);
    float P_relax : packoffset(c1.w);
    float P_reqScale : packoffset(c2);
    float P_ablFraction : packoffset(c2.y);
    float P_ilim : packoffset(c2.z);
    float P_pad : packoffset(c2.w);
    float4 P_share : packoffset(c3);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

void comp_main()
{
    uint g = gl_GlobalInvocationID.x;
    if (int(g) >= P_rows)
    {
        return;
    }
    int y = int(g);
    float3 s = 0.0f.xxx;
    for (int x = 0; x < P_width; x++)
    {
        precise float3 _68 = s + asfloat(_56.Load4(((y * P_width) + x) * 16 + 0)).xyz;
        s = _68;
    }
    _74.Store4(y * 16 + 0, asuint(float4(s / float(P_width).xxx, 1.0f)));
}

[numthreads(64, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
