// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/supply_state.comp - do not edit.
// glsl-sha256: ccb22da85eb1ab219bb2188f0cf8f2eef6a3b263ff8b003b2cbba2c84131c7a8
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(1u, 1u, 1u);

ByteAddressBuffer _58 : register(t0);
ByteAddressBuffer _124 : register(t1);
RWByteAddressBuffer _169 : register(u2);
cbuffer SupplyParams
{
    int P_width : packoffset(c0);
    int P_rows : packoffset(c0.y);
    float P_decay : packoffset(c0.z);
    float P_v0 : packoffset(c0.w);
    float P_reff : packoffset(c1);
    float P_imax : packoffset(c1.y);
    float P_n : packoffset(c1.z);
    float P_relax : packoffset(c1.w);
    float P_reqScale : packoffset(c2);
    float P_ablFraction : packoffset(c2.y);
    float P_ilim : packoffset(c2.z);
    float P_pad : packoffset(c2.w);
    float4 P_share : packoffset(c3);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

float supplyLoop(float4 state, int last, inout float req)
{
    float v = state.x;
    float gain = state.z;
    float rq = 0.0f;
    for (int j = 0; j < P_rows; j++)
    {
        if (j > last)
        {
            break;
        }
        float3 u = asfloat(_58.Load4(j * 16 + 0)).xyz;
        float drive = dot(u, P_share.xyz);
        precise float _83 = P_reff * P_imax;
        precise float _85 = _83 * gain;
        precise float _87 = _85 * drive;
        precise float _88 = P_v0 - _87;
        float target = _88;
        precise float _92 = v - target;
        precise float _96 = _92 * P_decay;
        precise float _97 = target + _96;
        v = _97;
        precise float _101 = P_imax * drive;
        precise float _103 = rq + _101;
        rq = _103;
    }
    req = rq;
    return v;
}

void comp_main()
{
    if (gl_GlobalInvocationID.x != 0u)
    {
        return;
    }
    float4 st = asfloat(_124.Load4(0));
    float4 param = st;
    int param_1 = P_rows - 1;
    float param_2;
    float _136 = supplyLoop(param, param_1, param_2);
    float req = param_2;
    float v = _136;
    precise float _143 = v - P_v0;
    precise float _147 = _143 * P_relax;
    precise float _148 = P_v0 + _147;
    v = _148;
    precise float _157 = req * P_reqScale;
    precise float _160 = _157 - st.y;
    precise float _164 = _160 * P_ablFraction;
    precise float _165 = st.y + _164;
    float requested = _165;
    float _177;
    if (requested > P_ilim)
    {
        _177 = P_ilim / requested;
    }
    else
    {
        _177 = 1.0f;
    }
    _169.Store4(0, asuint(float4(v, requested, _177, 1.0f)));
}

[numthreads(1, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
