// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/supply_fast.comp - do not edit.
// glsl-sha256: 92c6d619847ece7952e3bd80cdeed8f7e274f011af5e6bb72233a0a3b7c76a4a
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(256u, 1u, 1u);

ByteAddressBuffer _40 : register(t0);
ByteAddressBuffer _143 : register(t1);
RWByteAddressBuffer _321 : register(u2);
RWByteAddressBuffer _366 : register(u3);
cbuffer SupplyParams
{
    int P_width : packoffset(c0);
    int P_rows : packoffset(c0.y);
    float P_decay : packoffset(c0.z);
    float P_v0 : packoffset(c0.w);
    float P_reff : packoffset(c1);
    float P_imax : packoffset(c1.y);
    float P_n : packoffset(c1.z);
    float P_relax : packoffset(c1.w);
    float P_reqScale : packoffset(c2);
    float P_ablFraction : packoffset(c2.y);
    float P_ilim : packoffset(c2.z);
    float P_prime : packoffset(c2.w);
    float4 P_share : packoffset(c3);
};


static uint3 gl_LocalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_LocalInvocationID : SV_GroupThreadID;
};

groupshared float red[256];
groupshared float4 st;
groupshared float scan[2][256];
groupshared float vStart;

void comp_main()
{
    int t = int(gl_LocalInvocationID.x);
    int R = P_rows;
    float _34;
    if (t < R)
    {
        _34 = dot(asfloat(_40.Load4(t * 16 + 0)).xyz, P_share.xyz);
    }
    else
    {
        _34 = 0.0f;
    }
    float drive = _34;
    red[t] = P_imax * drive;
    GroupMemoryBarrierWithGroupSync();
    for (int w = 128; w > 0; w = w >> 1)
    {
        if (t < w)
        {
            red[t] += red[t + w];
        }
        GroupMemoryBarrierWithGroupSync();
    }
    float req = red[0];
    if (t == 0)
    {
        if (P_prime != 0.0f)
        {
            float requested = req * P_reqScale;
            float _128;
            if (requested > P_ilim)
            {
                _128 = P_ilim / requested;
            }
            else
            {
                _128 = 1.0f;
            }
            st = float4(P_v0, requested, _128, 1.0f);
        }
        else
        {
            st = asfloat(_143.Load4(0));
        }
    }
    GroupMemoryBarrierWithGroupSync();
    float4 s0 = st;
    float a = P_decay;
    int cur = 0;
    float _161;
    if (t < R)
    {
        _161 = (1.0f - a) * (P_v0 - (((P_reff * P_imax) * s0.z) * drive));
    }
    else
    {
        _161 = 0.0f;
    }
    scan[0][t] = _161;
    GroupMemoryBarrierWithGroupSync();
    float ao = a;
    for (int o = 1; o < 256; o = o << 1)
    {
        float v = scan[cur][t];
        if (t >= o)
        {
            v += (ao * scan[cur][t - o]);
        }
        scan[1 - cur][t] = v;
        cur = 1 - cur;
        ao *= ao;
        GroupMemoryBarrierWithGroupSync();
    }
    if (t == 0)
    {
        float aR = pow(a, float(R));
        float last = scan[cur][R - 1];
        float v_1 = s0.x;
        if (P_prime != 0.0f)
        {
            for (int i = 0; i < 3; i++)
            {
                v_1 = P_v0 + ((((aR * v_1) + last) - P_v0) * P_relax);
            }
        }
        vStart = v_1;
        float vEnd = P_v0 + ((((aR * v_1) + last) - P_v0) * P_relax);
        float _296;
        if (P_prime != 0.0f)
        {
            _296 = s0.y;
        }
        else
        {
            _296 = s0.y + (((req * P_reqScale) - s0.y) * P_ablFraction);
        }
        float requested_1 = _296;
        float _328;
        if (requested_1 > P_ilim)
        {
            _328 = P_ilim / requested_1;
        }
        else
        {
            _328 = 1.0f;
        }
        _321.Store4(0, asuint(float4(vEnd, requested_1, _328, 1.0f)));
    }
    GroupMemoryBarrierWithGroupSync();
    if (t < R)
    {
        float v_2 = (pow(a, float(t + 1)) * vStart) + scan[cur][t];
        float m = sqrt(P_v0 / v_2);
        _366.Store4(t * 16 + 0, asuint(float4(m, (s0.z * pow(v_2 / P_v0, P_n)) / m, 0.0f, 1.0f)));
    }
}

[numthreads(256, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_LocalInvocationID = stage_input.gl_LocalInvocationID;
    comp_main();
}
