// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/tube_lit.comp - do not edit.
// glsl-sha256: cd78616d7614a0a49633522e73fe7fe2b545221f67705964c538a16df787e6b4
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(32u, 8u, 1u);

ByteAddressBuffer _65 : register(t0);
ByteAddressBuffer _80 : register(t1);
RWByteAddressBuffer _93 : register(u2);
cbuffer TubeParams
{
    int P_width : packoffset(c0);
    int P_height : packoffset(c0.y);
    int P_ow : packoffset(c0.z);
    int P_oh : packoffset(c0.w);
    int P_xCount : packoffset(c1);
    int P_yCount : packoffset(c1.y);
    int P_gCount : packoffset(c1.z);
    int P_levels : packoffset(c1.w);
    float P_gain : packoffset(c2);
    float P_scatterFraction : packoffset(c2.y);
    float P_keep : packoffset(c2.z);
    int P_radius : packoffset(c2.w);
    int P_depth : packoffset(c3);
    int P_extra : packoffset(c3.y);
    int P_pad1 : packoffset(c3.z);
    int P_pad2 : packoffset(c3.w);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

uint spvPackHalf2x16(float2 value)
{
    uint2 Packed = f32tof16(value);
    return Packed.x | (Packed.y << 16);
}

float2 spvUnpackHalf2x16(uint value)
{
    return f16tof32(uint2(value & 0xffff, value >> 16));
}

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _30 = int(g.x) >= P_ow;
    bool _42;
    if (!_30)
    {
        _42 = int(g.y) >= P_oh;
    }
    else
    {
        _42 = _30;
    }
    if (_42)
    {
        return;
    }
    int i = (int(g.y) * P_ow) + int(g.x);
    precise float3 _76 = asfloat(_65.Load4(i * 16 + 0)).xyz * P_keep;
    precise float3 _88 = asfloat(_80.Load4(i * 16 + 0)).xyz * P_scatterFraction;
    precise float3 _89 = _76 + _88;
    float3 v = _89;
    _93.Store2((((P_extra * P_ow) * P_oh) + i) * 8 + 0, uint2(spvPackHalf2x16(v.xy), spvPackHalf2x16(float2(v.z, 1.0f))));
}

[numthreads(32, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
