// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/tube_persist.comp - do not edit.
// glsl-sha256: 2ef1e0a62af608fa07f18f4c1933b8c085ebe98a7349c0f217fbae8d69b70c8b
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(32u, 8u, 1u);

ByteAddressBuffer _64 : register(t1);
ByteAddressBuffer _86 : register(t0);
ByteAddressBuffer _116 : register(t3);
RWByteAddressBuffer _131 : register(u2);
cbuffer TubeParams
{
    int P_width : packoffset(c0);
    int P_height : packoffset(c0.y);
    int P_ow : packoffset(c0.z);
    int P_oh : packoffset(c0.w);
    int P_xCount : packoffset(c1);
    int P_yCount : packoffset(c1.y);
    int P_gCount : packoffset(c1.z);
    int P_levels : packoffset(c1.w);
    float P_gain : packoffset(c2);
    float P_scatterFraction : packoffset(c2.y);
    float P_keep : packoffset(c2.z);
    int P_radius : packoffset(c2.w);
    int P_depth : packoffset(c3);
    int P_extra : packoffset(c3.y);
    int P_pad1 : packoffset(c3.z);
    int P_pad2 : packoffset(c3.w);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

uint spvPackHalf2x16(float2 value)
{
    uint2 Packed = f32tof16(value);
    return Packed.x | (Packed.y << 16);
}

float2 spvUnpackHalf2x16(uint value)
{
    return f16tof32(uint2(value & 0xffff, value >> 16));
}

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _30 = int(g.x) >= P_ow;
    bool _42;
    if (!_30)
    {
        _42 = int(g.y) >= P_oh;
    }
    else
    {
        _42 = _30;
    }
    if (_42)
    {
        return;
    }
    int i = (int(g.y) * P_ow) + int(g.x);
    float3 v = asfloat(_64.Load(i * 4 + 0)).xxx;
    for (int s = 0; s < P_depth; s++)
    {
        uint2 h = _86.Load2((((s * P_ow) * P_oh) + i) * 8 + 0);
        float3 c = float3(spvUnpackHalf2x16(h.x), spvUnpackHalf2x16(h.y).x);
        precise float3 _122 = c * asfloat(_116.Load4(s * 16 + 0)).xyz;
        precise float3 _124 = v + _122;
        v = _124;
    }
    _131.Store4(i * 16 + 0, asuint(float4(v, 1.0f)));
}

[numthreads(32, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
