// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/tube_scatter_x16.comp - do not edit.
// glsl-sha256: d64612362dae648c4e4fbbccaba3acf1ff2e78425b76f05d3aa9f817cce5fa76
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(32u, 8u, 1u);

ByteAddressBuffer _57 : register(t0);
ByteAddressBuffer _133 : register(t1);
RWByteAddressBuffer _231 : register(u2);
cbuffer TubeParams
{
    int P_width : packoffset(c0);
    int P_height : packoffset(c0.y);
    int P_ow : packoffset(c0.z);
    int P_oh : packoffset(c0.w);
    int P_xCount : packoffset(c1);
    int P_yCount : packoffset(c1.y);
    int P_gCount : packoffset(c1.z);
    int P_levels : packoffset(c1.w);
    float P_gain : packoffset(c2);
    float P_scatterFraction : packoffset(c2.y);
    float P_keep : packoffset(c2.z);
    int P_radius : packoffset(c2.w);
    int P_depth : packoffset(c3);
    int P_extra : packoffset(c3.y);
    int P_pad1 : packoffset(c3.z);
    int P_pad2 : packoffset(c3.w);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

float3 fetchSrc(int qx, int qy)
{
    bool _28 = (qx >= 0) && (qy >= 0);
    bool _40;
    if (_28)
    {
        _40 = qx < P_ow;
    }
    else
    {
        _40 = _28;
    }
    bool _48;
    if (_40)
    {
        _48 = qy < P_oh;
    }
    else
    {
        _48 = _40;
    }
    float3 _50;
    if (_48)
    {
        _50 = asfloat(_57.Load4(((qy * P_ow) + qx) * 16 + 0)).xyz;
    }
    else
    {
        _50 = 0.0f.xxx;
    }
    return _50;
}

void scatterSlide(int px, int py, int ax, int ay)
{
    int R = P_radius;
    float3 win[16];
    float3 sum[16];
    for (int k = 0; k < 16; k++)
    {
        int param = px + (ax * (k - R));
        int param_1 = py + (ay * (k - R));
        win[k] = fetchSrc(param, param_1);
        sum[k] = 0.0f.xxx;
    }
    int _119 = -R;
    for (int d = _119; d <= R; d++)
    {
        float w = asfloat(_133.Load((d + R) * 4 + 0));
        for (int k_1 = 0; k_1 < 16; k_1++)
        {
            precise float3 _153 = win[k_1] * w;
            precise float3 _156 = sum[k_1] + _153;
            sum[k_1] = _156;
        }
        for (int k_2 = 0; k_2 < 15; k_2++)
        {
            win[k_2] = win[k_2 + 1];
        }
        int param_2 = px + (ax * (16 + d));
        int param_3 = py + (ay * (16 + d));
        win[15] = fetchSrc(param_2, param_3);
    }
    for (int k_3 = 0; k_3 < 16; k_3++)
    {
        int qx = px + (ax * k_3);
        int qy = py + (ay * k_3);
        bool _218 = qx < P_ow;
        bool _225;
        if (_218)
        {
            _225 = qy < P_oh;
        }
        else
        {
            _225 = _218;
        }
        if (_225)
        {
            _231.Store4(((qy * P_ow) + qx) * 16 + 0, asuint(float4(sum[k_3], 1.0f)));
        }
    }
}

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _265 = (int(g.x) * 16) >= P_ow;
    bool _276;
    if (!_265)
    {
        _276 = int(g.y) >= P_oh;
    }
    else
    {
        _276 = _265;
    }
    if (_276)
    {
        return;
    }
    int param = int(g.x) * 16;
    int param_1 = int(g.y);
    int param_2 = 1;
    int param_3 = 0;
    scatterSlide(param, param_1, param_2, param_3);
}

[numthreads(32, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
