// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/tube_scatter.comp - do not edit.
// glsl-sha256: 177f8ab492d9b0cb59ed425448674e28323bba7ff3e2c038221949dc6d82160a
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(32u, 8u, 1u);

ByteAddressBuffer _118 : register(t0);
ByteAddressBuffer _132 : register(t1);
RWByteAddressBuffer _149 : register(u2);
cbuffer TubeParams
{
    int P_width : packoffset(c0);
    int P_height : packoffset(c0.y);
    int P_ow : packoffset(c0.z);
    int P_oh : packoffset(c0.w);
    int P_xCount : packoffset(c1);
    int P_yCount : packoffset(c1.y);
    int P_gCount : packoffset(c1.z);
    int P_levels : packoffset(c1.w);
    float P_gain : packoffset(c2);
    float P_scatterFraction : packoffset(c2.y);
    float P_keep : packoffset(c2.z);
    int P_radius : packoffset(c2.w);
    int P_depth : packoffset(c3);
    int P_extra : packoffset(c3.y);
    int P_pad1 : packoffset(c3.z);
    int P_pad2 : packoffset(c3.w);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _30 = int(g.x) >= P_ow;
    bool _42;
    if (!_30)
    {
        _42 = int(g.y) >= P_oh;
    }
    else
    {
        _42 = _30;
    }
    if (_42)
    {
        return;
    }
    int px = int(g.x);
    int py = int(g.y);
    int axis = P_extra;
    float3 sum = 0.0f.xxx;
    int _68 = -P_radius;
    for (int d = _68; d <= P_radius; d++)
    {
        int qx = px + ((axis != 0) ? 0 : d);
        int qy = py + ((axis != 0) ? d : 0);
        bool _97 = (qx >= 0) && (qy >= 0);
        bool _104;
        if (_97)
        {
            _104 = qx < P_ow;
        }
        else
        {
            _104 = _97;
        }
        bool _111;
        if (_104)
        {
            _111 = qy < P_oh;
        }
        else
        {
            _111 = _104;
        }
        if (_111)
        {
            precise float3 _140 = asfloat(_118.Load4(((qy * P_ow) + qx) * 16 + 0)).xyz * asfloat(_132.Load((d + P_radius) * 4 + 0));
            precise float3 _142 = sum + _140;
            sum = _142;
        }
    }
    _149.Store4(((py * P_ow) + px) * 16 + 0, asuint(float4(sum, 1.0f)));
}

[numthreads(32, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
