// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/tube_v.comp - do not edit.
// glsl-sha256: 101d5a9ce9b73c8cfa52dff1154946044f4c9c6470eeba9960d4a615a56ca642
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(32u, 8u, 1u);

ByteAddressBuffer _87 : register(t1);
ByteAddressBuffer _104 : register(t0);
RWByteAddressBuffer _144 : register(u2);
cbuffer TubeParams
{
    int P_width : packoffset(c0);
    int P_height : packoffset(c0.y);
    int P_ow : packoffset(c0.z);
    int P_oh : packoffset(c0.w);
    int P_xCount : packoffset(c1);
    int P_yCount : packoffset(c1.y);
    int P_gCount : packoffset(c1.z);
    int P_levels : packoffset(c1.w);
    float P_gain : packoffset(c2);
    float P_scatterFraction : packoffset(c2.y);
    float P_keep : packoffset(c2.z);
    int P_radius : packoffset(c2.w);
    int P_depth : packoffset(c3);
    int P_extra : packoffset(c3.y);
    int P_pad1 : packoffset(c3.z);
    int P_pad2 : packoffset(c3.w);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _30 = int(g.x) >= P_ow;
    bool _42;
    if (!_30)
    {
        _42 = int(g.y) >= P_oh;
    }
    else
    {
        _42 = _30;
    }
    if (_42)
    {
        return;
    }
    int px = int(g.x);
    int py = int(g.y);
    float3 value = 0.0f.xxx;
    for (int parity = 0; parity < 2; parity++)
    {
        float3 sum = 0.0f.xxx;
        for (int k = 0; k < P_yCount; k++)
        {
            float2 w = asfloat(_87.Load2(((((py * 2) + parity) * P_yCount) + k) * 8 + 0));
            precise float3 _126 = asfloat(_104.Load4((((int(w.x) + (parity * P_height)) * P_ow) + px) * 16 + 0)).xyz * w.y;
            precise float3 _128 = sum + _126;
            sum = _128;
        }
        precise float3 _136 = sum * P_gain;
        precise float3 _138 = value + _136;
        value = _138;
    }
    _144.Store4(((py * P_ow) + px) * 16 + 0, asuint(float4(value, 1.0f)));
}

[numthreads(32, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
