// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/tube_h_fast.comp - do not edit.
// glsl-sha256: 466fb3a8926625fadfdb93a69541741572acd166d483192b7c64d5aa98811157
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(384u, 1u, 1u);

ByteAddressBuffer _98 : register(t1);
ByteAddressBuffer _183 : register(t0);
RWByteAddressBuffer _284 : register(u2);
ByteAddressBuffer _926 : register(t3);
cbuffer FastTubeParams
{
    int P_height : packoffset(c0);
    int P_ow : packoffset(c0.y);
    int P_oh : packoffset(c0.z);
    int P_xCount : packoffset(c0.w);
    int P_gCount : packoffset(c1);
    int P_hStride : packoffset(c1.y);
    float P_gain : packoffset(c1.z);
    float P_keep : packoffset(c1.w);
    float4 P_amb : packoffset(c2);
    float4 P_light : packoffset(c3);
};


static uint3 gl_WorkGroupID;
static uint3 gl_LocalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_WorkGroupID : SV_GroupID;
    uint3 gl_LocalInvocationID : SV_GroupThreadID;
};

groupshared float rowv[7716];

void tubeHRows8(int S, int PS, int lid, int c, int y0, int ny, int span, int2 sp, int tapBase, int n, bool live, int o, int ostride)
{
    float2 _92;
    int idx[8];
    float wt[8];
    for (int k = 0; k < 8; k++)
    {
        if (live && (k < n))
        {
            _92 = asfloat(_98.Load2((tapBase + k) * 8 + 0));
        }
        else
        {
            _92 = float2(float(sp.x), 0.0f);
        }
        float2 t = _92;
        idx[k] = int(t.x) - sp.x;
        wt[k] = t.y;
    }
    for (int yb = 0; yb < ny; yb += 16)
    {
        int nb = min(16, (ny - yb));
        GroupMemoryBarrierWithGroupSync();
        for (int i = lid; i < (nb * span); i += 384)
        {
            int r = i / span;
            int x = i - (r * span);
            float4 v = asfloat(_183.Load4((((((y0 + yb) + r) * 512) + sp.x) + x) * 16 + 0));
            rowv[(r * S) + x] = v.x;
            rowv[(PS + (r * S)) + x] = v.y;
            rowv[((2 * PS) + (r * S)) + x] = v.z;
        }
        GroupMemoryBarrierWithGroupSync();
        if (live)
        {
            int rv = c * PS;
            for (int r_1 = 0; r_1 < nb; r_1++)
            {
                float sum = 0.0f;
                for (int k_1 = 0; k_1 < 8; k_1++)
                {
                    sum += (rowv[(rv + (r_1 * S)) + idx[k_1]] * wt[k_1]);
                }
                _284.Store((o + ((yb + r_1) * ostride)) * 4 + 0, asuint(sum));
            }
        }
    }
}

void tubeHRows12(int S, int PS, int lid, int c, int y0, int ny, int span, int2 sp, int tapBase, int n, bool live, int o, int ostride)
{
    float2 _314;
    int idx[12];
    float wt[12];
    for (int k = 0; k < 12; k++)
    {
        if (live && (k < n))
        {
            _314 = asfloat(_98.Load2((tapBase + k) * 8 + 0));
        }
        else
        {
            _314 = float2(float(sp.x), 0.0f);
        }
        float2 t = _314;
        idx[k] = int(t.x) - sp.x;
        wt[k] = t.y;
    }
    for (int yb = 0; yb < ny; yb += 16)
    {
        int nb = min(16, (ny - yb));
        GroupMemoryBarrierWithGroupSync();
        for (int i = lid; i < (nb * span); i += 384)
        {
            int r = i / span;
            int x = i - (r * span);
            float4 v = asfloat(_183.Load4((((((y0 + yb) + r) * 512) + sp.x) + x) * 16 + 0));
            rowv[(r * S) + x] = v.x;
            rowv[(PS + (r * S)) + x] = v.y;
            rowv[((2 * PS) + (r * S)) + x] = v.z;
        }
        GroupMemoryBarrierWithGroupSync();
        if (live)
        {
            int rv = c * PS;
            for (int r_1 = 0; r_1 < nb; r_1++)
            {
                float sum = 0.0f;
                for (int k_1 = 0; k_1 < 12; k_1++)
                {
                    sum += (rowv[(rv + (r_1 * S)) + idx[k_1]] * wt[k_1]);
                }
                _284.Store((o + ((yb + r_1) * ostride)) * 4 + 0, asuint(sum));
            }
        }
    }
}

void tubeHRows16(int S, int PS, int lid, int c, int y0, int ny, int span, int2 sp, int tapBase, int n, bool live, int o, int ostride)
{
    float2 _501;
    int idx[16];
    float wt[16];
    for (int k = 0; k < 16; k++)
    {
        if (live && (k < n))
        {
            _501 = asfloat(_98.Load2((tapBase + k) * 8 + 0));
        }
        else
        {
            _501 = float2(float(sp.x), 0.0f);
        }
        float2 t = _501;
        idx[k] = int(t.x) - sp.x;
        wt[k] = t.y;
    }
    for (int yb = 0; yb < ny; yb += 16)
    {
        int nb = min(16, (ny - yb));
        GroupMemoryBarrierWithGroupSync();
        for (int i = lid; i < (nb * span); i += 384)
        {
            int r = i / span;
            int x = i - (r * span);
            float4 v = asfloat(_183.Load4((((((y0 + yb) + r) * 512) + sp.x) + x) * 16 + 0));
            rowv[(r * S) + x] = v.x;
            rowv[(PS + (r * S)) + x] = v.y;
            rowv[((2 * PS) + (r * S)) + x] = v.z;
        }
        GroupMemoryBarrierWithGroupSync();
        if (live)
        {
            int rv = c * PS;
            for (int r_1 = 0; r_1 < nb; r_1++)
            {
                float sum = 0.0f;
                for (int k_1 = 0; k_1 < 16; k_1++)
                {
                    sum += (rowv[(rv + (r_1 * S)) + idx[k_1]] * wt[k_1]);
                }
                _284.Store((o + ((yb + r_1) * ostride)) * 4 + 0, asuint(sum));
            }
        }
    }
}

void tubeHRows24(int S, int PS, int lid, int c, int y0, int ny, int span, int2 sp, int tapBase, int n, bool live, int o, int ostride)
{
    float2 _689;
    int idx[24];
    float wt[24];
    for (int k = 0; k < 24; k++)
    {
        if (live && (k < n))
        {
            _689 = asfloat(_98.Load2((tapBase + k) * 8 + 0));
        }
        else
        {
            _689 = float2(float(sp.x), 0.0f);
        }
        float2 t = _689;
        idx[k] = int(t.x) - sp.x;
        wt[k] = t.y;
    }
    for (int yb = 0; yb < ny; yb += 16)
    {
        int nb = min(16, (ny - yb));
        GroupMemoryBarrierWithGroupSync();
        for (int i = lid; i < (nb * span); i += 384)
        {
            int r = i / span;
            int x = i - (r * span);
            float4 v = asfloat(_183.Load4((((((y0 + yb) + r) * 512) + sp.x) + x) * 16 + 0));
            rowv[(r * S) + x] = v.x;
            rowv[(PS + (r * S)) + x] = v.y;
            rowv[((2 * PS) + (r * S)) + x] = v.z;
        }
        GroupMemoryBarrierWithGroupSync();
        if (live)
        {
            int rv = c * PS;
            for (int r_1 = 0; r_1 < nb; r_1++)
            {
                float sum = 0.0f;
                for (int k_1 = 0; k_1 < 24; k_1++)
                {
                    sum += (rowv[(rv + (r_1 * S)) + idx[k_1]] * wt[k_1]);
                }
                _284.Store((o + ((yb + r_1) * ostride)) * 4 + 0, asuint(sum));
            }
        }
    }
}

void comp_main()
{
    int lid = int(gl_LocalInvocationID.x);
    int S = P_hStride;
    int PS = ((((16 * S) + 31) / 32) * 32) + 11;
    int c = lid % 3;
    int pxl = (lid / 3) % 64;
    int parity = lid / 192;
    int tile = int(gl_WorkGroupID.x);
    int px = (tile * 64) + pxl;
    int y0 = int(gl_WorkGroupID.y) * 64;
    int ny = min(64, (P_height - y0));
    int2 sp = int2(_926.Load2(tile * 8 + 0));
    int span = (sp.y - sp.x) + 1;
    bool live = px < P_ow;
    int tapBase = (((min(px, (P_ow - 1)) * 6) + (c * 2)) + parity) * P_xCount;
    int o = (((((parity * P_height) + y0) * P_ow) + px) * 4) + c;
    if (P_xCount <= 8)
    {
        int param = S;
        int param_1 = PS;
        int param_2 = lid;
        int param_3 = c;
        int param_4 = y0;
        int param_5 = ny;
        int param_6 = span;
        int2 param_7 = sp;
        int param_8 = tapBase;
        int param_9 = P_xCount;
        bool param_10 = live;
        int param_11 = o;
        int param_12 = P_ow * 4;
        tubeHRows8(param, param_1, param_2, param_3, param_4, param_5, param_6, param_7, param_8, param_9, param_10, param_11, param_12);
    }
    else
    {
        if (P_xCount <= 12)
        {
            int param_13 = S;
            int param_14 = PS;
            int param_15 = lid;
            int param_16 = c;
            int param_17 = y0;
            int param_18 = ny;
            int param_19 = span;
            int2 param_20 = sp;
            int param_21 = tapBase;
            int param_22 = P_xCount;
            bool param_23 = live;
            int param_24 = o;
            int param_25 = P_ow * 4;
            tubeHRows12(param_13, param_14, param_15, param_16, param_17, param_18, param_19, param_20, param_21, param_22, param_23, param_24, param_25);
        }
        else
        {
            if (P_xCount <= 16)
            {
                int param_26 = S;
                int param_27 = PS;
                int param_28 = lid;
                int param_29 = c;
                int param_30 = y0;
                int param_31 = ny;
                int param_32 = span;
                int2 param_33 = sp;
                int param_34 = tapBase;
                int param_35 = P_xCount;
                bool param_36 = live;
                int param_37 = o;
                int param_38 = P_ow * 4;
                tubeHRows16(param_26, param_27, param_28, param_29, param_30, param_31, param_32, param_33, param_34, param_35, param_36, param_37, param_38);
            }
            else
            {
                int param_39 = S;
                int param_40 = PS;
                int param_41 = lid;
                int param_42 = c;
                int param_43 = y0;
                int param_44 = ny;
                int param_45 = span;
                int2 param_46 = sp;
                int param_47 = tapBase;
                int param_48 = P_xCount;
                bool param_49 = live;
                int param_50 = o;
                int param_51 = P_ow * 4;
                tubeHRows24(param_39, param_40, param_41, param_42, param_43, param_44, param_45, param_46, param_47, param_48, param_49, param_50, param_51);
            }
        }
    }
}

[numthreads(384, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_WorkGroupID = stage_input.gl_WorkGroupID;
    gl_LocalInvocationID = stage_input.gl_LocalInvocationID;
    comp_main();
}
