// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/tube_h_rows.comp - do not edit.
// glsl-sha256: 17f2b5be094a6b7886ba5d94edb5192992ff0381d97508b091eddd581a900d7b
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(64u, 1u, 1u);

ByteAddressBuffer _88 : register(t1);
ByteAddressBuffer _184 : register(t0);
RWByteAddressBuffer _218 : register(u2);
cbuffer TubeParams
{
    int P_width : packoffset(c0);
    int P_height : packoffset(c0.y);
    int P_ow : packoffset(c0.z);
    int P_oh : packoffset(c0.w);
    int P_xCount : packoffset(c1);
    int P_yCount : packoffset(c1.y);
    int P_gCount : packoffset(c1.z);
    int P_levels : packoffset(c1.w);
    float P_gain : packoffset(c2);
    float P_scatterFraction : packoffset(c2.y);
    float P_keep : packoffset(c2.z);
    int P_radius : packoffset(c2.w);
    int P_depth : packoffset(c3);
    int P_extra : packoffset(c3.y);
    int P_pad1 : packoffset(c3.z);
    int P_pad2 : packoffset(c3.w);
};


static uint3 gl_WorkGroupID;
static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_WorkGroupID : SV_GroupID;
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

void comp_main()
{
    int px = int(gl_GlobalInvocationID.x);
    if (px >= P_ow)
    {
        return;
    }
    int chunks = ((P_height + 8) - 1) / 8;
    int parity = int(gl_WorkGroupID.y) / chunks;
    int y0 = (int(gl_WorkGroupID.y) % chunks) * 8;
    int idx[48];
    float wt[48];
    for (int c = 0; c < 3; c++)
    {
        for (int k = 0; k < 16; k++)
        {
            if (k >= P_xCount)
            {
                break;
            }
            float2 w = asfloat(_88.Load2((((((px * 6) + (c * 2)) + parity) * P_xCount) + k) * 8 + 0));
            idx[(c * 16) + k] = int(w.x);
            wt[(c * 16) + k] = w.y;
        }
    }
    for (int r = 0; r < 8; r++)
    {
        int y = y0 + r;
        if (y >= P_height)
        {
            break;
        }
        float3 sum = 0.0f.xxx;
        for (int c_1 = 0; c_1 < 3; c_1++)
        {
            for (int k_1 = 0; k_1 < 16; k_1++)
            {
                if (k_1 >= P_xCount)
                {
                    break;
                }
                precise float _206 = asfloat(_184.Load(((y * P_width) + idx[(c_1 * 16) + k_1]) * 16 + c_1 * 4 + 0)) * wt[(c_1 * 16) + k_1];
                precise float _209 = sum[c_1] + _206;
                sum[c_1] = _209;
            }
        }
        _218.Store4((((y + (parity * P_height)) * P_ow) + px) * 16 + 0, asuint(float4(sum, 1.0f)));
    }
}

[numthreads(64, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_WorkGroupID = stage_input.gl_WorkGroupID;
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
