// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/tube_scatter_tx.comp - do not edit.
// glsl-sha256: 988eacfdb0f58ef8d848b14963f760a074eb7dc1682e914891a794a176f577d0
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(256u, 1u, 1u);

ByteAddressBuffer _79 : register(t0);
ByteAddressBuffer _160 : register(t1);
RWByteAddressBuffer _176 : register(u2);
cbuffer TubeParams
{
    int P_width : packoffset(c0);
    int P_height : packoffset(c0.y);
    int P_ow : packoffset(c0.z);
    int P_oh : packoffset(c0.w);
    int P_xCount : packoffset(c1);
    int P_yCount : packoffset(c1.y);
    int P_gCount : packoffset(c1.z);
    int P_levels : packoffset(c1.w);
    float P_gain : packoffset(c2);
    float P_scatterFraction : packoffset(c2.y);
    float P_keep : packoffset(c2.z);
    int P_radius : packoffset(c2.w);
    int P_depth : packoffset(c3);
    int P_extra : packoffset(c3.y);
    int P_pad1 : packoffset(c3.z);
    int P_pad2 : packoffset(c3.w);
};


static uint3 gl_WorkGroupID;
static uint3 gl_LocalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_WorkGroupID : SV_GroupID;
    uint3 gl_LocalInvocationID : SV_GroupThreadID;
};

groupshared float tr[384];
groupshared float tg[384];
groupshared float tb[384];

void comp_main()
{
    int tid = int(gl_LocalInvocationID.x);
    int x0 = int(gl_WorkGroupID.x) * 256;
    int py = int(gl_WorkGroupID.y);
    int R = P_radius;
    float3 _72;
    for (int i = tid; i < (256 + (2 * R)); i += 256)
    {
        int qx = (x0 - R) + i;
        bool _64 = qx >= 0;
        bool _71;
        if (_64)
        {
            _71 = qx < P_ow;
        }
        else
        {
            _71 = _64;
        }
        if (_71)
        {
            _72 = asfloat(_79.Load4(((py * P_ow) + qx) * 16 + 0)).xyz;
        }
        else
        {
            _72 = 0.0f.xxx;
        }
        float3 v = _72;
        tr[i] = v.x;
        tg[i] = v.y;
        tb[i] = v.z;
    }
    GroupMemoryBarrierWithGroupSync();
    int px = x0 + tid;
    if (px >= P_ow)
    {
        return;
    }
    float3 sum = 0.0f.xxx;
    int _132 = -R;
    for (int d = _132; d <= R; d++)
    {
        int i_1 = (tid + R) + d;
        precise float3 _167 = float3(tr[i_1], tg[i_1], tb[i_1]) * asfloat(_160.Load((d + R) * 4 + 0));
        precise float3 _169 = sum + _167;
        sum = _169;
    }
    _176.Store4(((py * P_ow) + px) * 16 + 0, asuint(float4(sum, 1.0f)));
}

[numthreads(256, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_WorkGroupID = stage_input.gl_WorkGroupID;
    gl_LocalInvocationID = stage_input.gl_LocalInvocationID;
    comp_main();
}
