// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/tube_h_fast.comp - do not edit.
// glsl-sha256: 8021fb68c9272636ae5301d8921813d7f7a7ef169651cce8bbbec1627a2a2916
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(384u, 1u, 1u);

ByteAddressBuffer _73 : register(t1);
RWByteAddressBuffer _156 : register(u2);
ByteAddressBuffer _510 : register(t3);
ByteAddressBuffer _549 : register(t0);
cbuffer FastTubeParams
{
    int P_height : packoffset(c0);
    int P_ow : packoffset(c0.y);
    int P_oh : packoffset(c0.z);
    int P_xCount : packoffset(c0.w);
    int P_gCount : packoffset(c1);
    int P_hStride : packoffset(c1.y);
    float P_gain : packoffset(c1.z);
    float P_keep : packoffset(c1.w);
    float4 P_amb : packoffset(c2);
    float4 P_light : packoffset(c3);
};


static uint3 gl_WorkGroupID;
static uint3 gl_LocalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_WorkGroupID : SV_GroupID;
    uint3 gl_LocalInvocationID : SV_GroupThreadID;
};

groupshared float rowv[7716];

void tubeHRows8(int rv, int S, int ny, int tapBase, int n, int first, int o, int ostride)
{
    float2 _67;
    int idx[8];
    float wt[8];
    for (int k = 0; k < 8; k++)
    {
        if (k < n)
        {
            _67 = asfloat(_73.Load2((tapBase + k) * 8 + 0));
        }
        else
        {
            _67 = float2(float(first), 0.0f);
        }
        float2 t = _67;
        idx[k] = int(t.x) - first;
        wt[k] = t.y;
    }
    for (int r = 0; r < ny; r++)
    {
        float sum = 0.0f;
        for (int k_1 = 0; k_1 < 8; k_1++)
        {
            sum += (rowv[(rv + (r * S)) + idx[k_1]] * wt[k_1]);
        }
        _156.Store((o + (r * ostride)) * 4 + 0, asuint(sum));
    }
}

void tubeHRows12(int rv, int S, int ny, int tapBase, int n, int first, int o, int ostride)
{
    float2 _180;
    int idx[12];
    float wt[12];
    for (int k = 0; k < 12; k++)
    {
        if (k < n)
        {
            _180 = asfloat(_73.Load2((tapBase + k) * 8 + 0));
        }
        else
        {
            _180 = float2(float(first), 0.0f);
        }
        float2 t = _180;
        idx[k] = int(t.x) - first;
        wt[k] = t.y;
    }
    for (int r = 0; r < ny; r++)
    {
        float sum = 0.0f;
        for (int k_1 = 0; k_1 < 12; k_1++)
        {
            sum += (rowv[(rv + (r * S)) + idx[k_1]] * wt[k_1]);
        }
        _156.Store((o + (r * ostride)) * 4 + 0, asuint(sum));
    }
}

void tubeHRows16(int rv, int S, int ny, int tapBase, int n, int first, int o, int ostride)
{
    float2 _272;
    int idx[16];
    float wt[16];
    for (int k = 0; k < 16; k++)
    {
        if (k < n)
        {
            _272 = asfloat(_73.Load2((tapBase + k) * 8 + 0));
        }
        else
        {
            _272 = float2(float(first), 0.0f);
        }
        float2 t = _272;
        idx[k] = int(t.x) - first;
        wt[k] = t.y;
    }
    for (int r = 0; r < ny; r++)
    {
        float sum = 0.0f;
        for (int k_1 = 0; k_1 < 16; k_1++)
        {
            sum += (rowv[(rv + (r * S)) + idx[k_1]] * wt[k_1]);
        }
        _156.Store((o + (r * ostride)) * 4 + 0, asuint(sum));
    }
}

void tubeHRows24(int rv, int S, int ny, int tapBase, int n, int first, int o, int ostride)
{
    float2 _364;
    int idx[24];
    float wt[24];
    for (int k = 0; k < 24; k++)
    {
        if (k < n)
        {
            _364 = asfloat(_73.Load2((tapBase + k) * 8 + 0));
        }
        else
        {
            _364 = float2(float(first), 0.0f);
        }
        float2 t = _364;
        idx[k] = int(t.x) - first;
        wt[k] = t.y;
    }
    for (int r = 0; r < ny; r++)
    {
        float sum = 0.0f;
        for (int k_1 = 0; k_1 < 24; k_1++)
        {
            sum += (rowv[(rv + (r * S)) + idx[k_1]] * wt[k_1]);
        }
        _156.Store((o + (r * ostride)) * 4 + 0, asuint(sum));
    }
}

void comp_main()
{
    int lid = int(gl_LocalInvocationID.x);
    int S = P_hStride;
    int PS = ((((16 * S) + 31) / 32) * 32) + 11;
    int c = lid % 3;
    int pxl = (lid / 3) % 64;
    int parity = lid / 192;
    int tile = int(gl_WorkGroupID.x);
    int px = (tile * 64) + pxl;
    int y0 = int(gl_WorkGroupID.y) * 16;
    int ny = min(16, (P_height - y0));
    int2 sp = int2(_510.Load2(tile * 8 + 0));
    int span = (sp.y - sp.x) + 1;
    for (int i = lid; i < (ny * span); i += 384)
    {
        int r = i / span;
        int x = i - (r * span);
        float4 v = asfloat(_549.Load4(((((y0 + r) * 512) + sp.x) + x) * 16 + 0));
        rowv[(r * S) + x] = v.x;
        rowv[(PS + (r * S)) + x] = v.y;
        rowv[((2 * PS) + (r * S)) + x] = v.z;
    }
    GroupMemoryBarrierWithGroupSync();
    if (px >= P_ow)
    {
        return;
    }
    int tapBase = (((px * 6) + (c * 2)) + parity) * P_xCount;
    int o = (((((parity * P_height) + y0) * P_ow) + px) * 4) + c;
    int rv = c * PS;
    if (P_xCount <= 8)
    {
        int param = rv;
        int param_1 = S;
        int param_2 = ny;
        int param_3 = tapBase;
        int param_4 = P_xCount;
        int param_5 = sp.x;
        int param_6 = o;
        int param_7 = P_ow * 4;
        tubeHRows8(param, param_1, param_2, param_3, param_4, param_5, param_6, param_7);
    }
    else
    {
        if (P_xCount <= 12)
        {
            int param_8 = rv;
            int param_9 = S;
            int param_10 = ny;
            int param_11 = tapBase;
            int param_12 = P_xCount;
            int param_13 = sp.x;
            int param_14 = o;
            int param_15 = P_ow * 4;
            tubeHRows12(param_8, param_9, param_10, param_11, param_12, param_13, param_14, param_15);
        }
        else
        {
            if (P_xCount <= 16)
            {
                int param_16 = rv;
                int param_17 = S;
                int param_18 = ny;
                int param_19 = tapBase;
                int param_20 = P_xCount;
                int param_21 = sp.x;
                int param_22 = o;
                int param_23 = P_ow * 4;
                tubeHRows16(param_16, param_17, param_18, param_19, param_20, param_21, param_22, param_23);
            }
            else
            {
                int param_24 = rv;
                int param_25 = S;
                int param_26 = ny;
                int param_27 = tapBase;
                int param_28 = P_xCount;
                int param_29 = sp.x;
                int param_30 = o;
                int param_31 = P_ow * 4;
                tubeHRows24(param_24, param_25, param_26, param_27, param_28, param_29, param_30, param_31);
            }
        }
    }
}

[numthreads(384, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_WorkGroupID = stage_input.gl_WorkGroupID;
    gl_LocalInvocationID = stage_input.gl_LocalInvocationID;
    comp_main();
}
