// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/tube_v_fast.comp - do not edit.
// glsl-sha256: 0042e3e7b7a362631c750fe297ffb078f122f09c688d5fe2e79d0e1d577e58b8
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(32u, 8u, 1u);

ByteAddressBuffer _108 : register(t3);
ByteAddressBuffer _129 : register(t2);
ByteAddressBuffer _167 : register(t0);
ByteAddressBuffer _181 : register(t1);
ByteAddressBuffer _302 : register(t4);
RWByteAddressBuffer _429 : register(u5);
cbuffer FastTubeParams
{
    int P_height : packoffset(c0);
    int P_ow : packoffset(c0.y);
    int P_oh : packoffset(c0.z);
    int P_xCount : packoffset(c0.w);
    int P_gCount : packoffset(c1);
    int P_hStride : packoffset(c1.y);
    float P_gain : packoffset(c1.z);
    float P_keep : packoffset(c1.w);
    float4 P_amb : packoffset(c2);
    float4 P_light : packoffset(c3);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

uint spvPackHalf2x16(float2 value)
{
    uint2 Packed = f32tof16(value);
    return Packed.x | (Packed.y << 16);
}

float2 spvUnpackHalf2x16(uint value)
{
    return f16tof32(uint2(value & 0xffff, value >> 16));
}

float4 unpackH4(uint2 h)
{
    return float4(spvUnpackHalf2x16(h.x), spvUnpackHalf2x16(h.y));
}

uint2 packH4(float4 v)
{
    return uint2(spvPackHalf2x16(v.xy), spvPackHalf2x16(v.zw));
}

void comp_main()
{
    int px = int(gl_GlobalInvocationID.x);
    int py = int(gl_GlobalInvocationID.y);
    bool _69 = px >= P_ow;
    bool _78;
    if (!_69)
    {
        _78 = py >= P_oh;
    }
    else
    {
        _78 = _69;
    }
    if (_78)
    {
        return;
    }
    int plane = P_height * P_ow;
    float3 value = 0.0f.xxx;
    for (int parity = 0; parity < 2; parity++)
    {
        int2 fr = int2(_108.Load2(((py * 2) + parity) * 8 + 0));
        int cf = ((py * 2) + parity) * P_gCount;
        float3 sc = asfloat(_129.Load4(((parity * P_ow) + px) * 16 + 0)).xyz;
        int h0 = ((parity * plane) + (fr.x * P_ow)) + px;
        float3 sum = 0.0f.xxx;
        for (int k = 0; k < fr.y; k++)
        {
            float3 hv = asfloat(_167.Load4((h0 + (k * P_ow)) * 16 + 0)).xyz;
            float4 c = asfloat(_181.Load4((cf + k) * 16 + 0));
            float3 u = clamp(hv * sc, 0.0f.xxx, 1.0f.xxx);
            sum += (hv * ((((((u * c.w) + c.z.xxx) * u) + c.y.xxx) * u) + c.x.xxx));
        }
        value += (sum * P_gain);
    }
    float sx = (((float(px) + 0.5f) * 512.0f) / float(P_ow)) - 0.5f;
    float sy = (((float(py) + 0.5f) * float(P_height)) / float(P_oh)) - 0.5f;
    float fx0 = floor(sx);
    float fy0 = floor(sy);
    float fx = sx - fx0;
    float fy = sy - fy0;
    int x0 = clamp(int(fx0), 0, 511);
    int x1 = clamp(int(fx0) + 1, 0, 511);
    int y0 = clamp(int(fy0), 0, P_height - 1);
    int y1 = clamp(int(fy0) + 1, 0, P_height - 1);
    uint2 param = _302.Load2(((y0 * 512) + x0) * 8 + 0);
    uint2 param_1 = _302.Load2(((y0 * 512) + x1) * 8 + 0);
    float3 top = lerp(unpackH4(param).xyz, unpackH4(param_1).xyz, fx.xxx);
    uint2 param_2 = _302.Load2(((y1 * 512) + x0) * 8 + 0);
    uint2 param_3 = _302.Load2(((y1 * 512) + x1) * 8 + 0);
    float3 bot = lerp(unpackH4(param_2).xyz, unpackH4(param_3).xyz, fx.xxx);
    float nx = ((((float(px) + 0.5f) / float(P_ow)) * 2.0f) - 1.0f) * P_amb.z;
    float ny = ((((float(py) + 0.5f) / float(P_oh)) * 2.0f) - 1.0f) * P_amb.w;
    float cosine = max(0.0f, (((nx * P_light.x) + (ny * P_light.y)) + P_light.z) / sqrt(((nx * nx) + (ny * ny)) + 1.0f));
    float3 val = ((P_amb.x * (P_amb.y + ((1.0f - P_amb.y) * cosine))).xxx + (value * P_keep)) + lerp(top, bot, fy.xxx);
    float4 param_4 = float4(val, 1.0f);
    _429.Store2(((py * P_ow) + px) * 8 + 0, packH4(param_4));
}

[numthreads(32, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
