// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/tube_mix.comp - do not edit.
// glsl-sha256: 054bfe6e146d02180b725481b4d8a9e650625f3ea154154683ab6164a7128b66
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(32u, 8u, 1u);

ByteAddressBuffer _64 : register(t2);
ByteAddressBuffer _75 : register(t0);
ByteAddressBuffer _90 : register(t1);
RWByteAddressBuffer _103 : register(u3);
cbuffer TubeParams
{
    int P_width : packoffset(c0);
    int P_height : packoffset(c0.y);
    int P_ow : packoffset(c0.z);
    int P_oh : packoffset(c0.w);
    int P_xCount : packoffset(c1);
    int P_yCount : packoffset(c1.y);
    int P_gCount : packoffset(c1.z);
    int P_levels : packoffset(c1.w);
    float P_gain : packoffset(c2);
    float P_scatterFraction : packoffset(c2.y);
    float P_keep : packoffset(c2.z);
    int P_radius : packoffset(c2.w);
    int P_depth : packoffset(c3);
    int P_extra : packoffset(c3.y);
    int P_pad1 : packoffset(c3.z);
    int P_pad2 : packoffset(c3.w);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _30 = int(g.x) >= P_ow;
    bool _42;
    if (!_30)
    {
        _42 = int(g.y) >= P_oh;
    }
    else
    {
        _42 = _30;
    }
    if (_42)
    {
        return;
    }
    int i = (int(g.y) * P_ow) + int(g.x);
    precise float3 _85 = asfloat(_75.Load4(i * 16 + 0)).xyz * P_keep;
    precise float3 _86 = asfloat(_64.Load(i * 4 + 0)).xxx + _85;
    precise float3 _98 = asfloat(_90.Load4(i * 16 + 0)).xyz * P_scatterFraction;
    precise float3 _99 = _86 + _98;
    float3 v = _99;
    _103.Store4(i * 16 + 0, asuint(float4(v, 1.0f)));
}

[numthreads(32, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
