// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/tube_v_growth.comp - do not edit.
// glsl-sha256: 2b5b8d31533170ac200f3acd9bda786aeedc27adf32b9c7b8fcd9575815b4708
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(32u, 8u, 1u);

ByteAddressBuffer _101 : register(t2);
ByteAddressBuffer _152 : register(t1);
ByteAddressBuffer _170 : register(t0);
RWByteAddressBuffer _294 : register(u3);
cbuffer TubeParams
{
    int P_width : packoffset(c0);
    int P_height : packoffset(c0.y);
    int P_ow : packoffset(c0.z);
    int P_oh : packoffset(c0.w);
    int P_xCount : packoffset(c1);
    int P_yCount : packoffset(c1.y);
    int P_gCount : packoffset(c1.z);
    int P_levels : packoffset(c1.w);
    float P_gain : packoffset(c2);
    float P_scatterFraction : packoffset(c2.y);
    float P_keep : packoffset(c2.z);
    int P_radius : packoffset(c2.w);
    int P_depth : packoffset(c3);
    int P_extra : packoffset(c3.y);
    int P_pad1 : packoffset(c3.z);
    int P_pad2 : packoffset(c3.w);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

float glmix1(float x, float y, float a)
{
    precise float _18 = 1.0f - a;
    precise float _19 = x * _18;
    precise float _22 = y * a;
    precise float _23 = _19 + _22;
    float r = _23;
    return r;
}

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _50 = int(g.x) >= P_ow;
    bool _62;
    if (!_50)
    {
        _62 = int(g.y) >= P_oh;
    }
    else
    {
        _62 = _50;
    }
    if (_62)
    {
        return;
    }
    int px = int(g.x);
    int py = int(g.y);
    int rowWidth = P_levels * P_gCount;
    float3 value = 0.0f.xxx;
    for (int parity = 0; parity < 2; parity++)
    {
        float3 cs = float3(asfloat(_101.Load(((parity * P_ow) + px) * 4 + 0)), asfloat(_101.Load((((2 + parity) * P_ow) + px) * 4 + 0)), asfloat(_101.Load((((4 + parity) * P_ow) + px) * 4 + 0)));
        float3 sum = 0.0f.xxx;
        int row = (py * 2) + parity;
        for (int k = 0; k < P_gCount; k++)
        {
            float fy = asfloat(_152.Load(((row * rowWidth) + k) * 8 + 0));
            if (fy < 0.0f)
            {
                continue;
            }
            float3 h = asfloat(_170.Load4((((int(fy) + (parity * P_height)) * P_ow) + px) * 16 + 0)).xyz;
            for (int c = 0; c < 3; c++)
            {
                bool _199 = h[c] == 0.0f;
                bool _207;
                if (!_199)
                {
                    _207 = cs[c] <= 0.0f;
                }
                else
                {
                    _207 = _199;
                }
                if (!_207)
                {
                    precise float _218 = h[c] / cs[c];
                    precise float _224 = clamp(_218, 0.0f, 1.0f) * float(P_levels - 1);
                    float t = _224;
                    int kk = min((P_levels - 2), int(floor(t)));
                    precise float _237 = t - float(kk);
                    float f = _237;
                    float param = asfloat(_152.Load((((row * rowWidth) + (kk * P_gCount)) + k) * 8 + 4));
                    float param_1 = asfloat(_152.Load((((row * rowWidth) + ((kk + 1) * P_gCount)) + k) * 8 + 4));
                    float param_2 = f;
                    precise float _272 = h[c] * glmix1(param, param_1, param_2);
                    precise float _275 = sum[c] + _272;
                    sum[c] = _275;
                }
            }
        }
        precise float3 _286 = sum * P_gain;
        precise float3 _288 = value + _286;
        value = _288;
    }
    _294.Store4(((py * P_ow) + px) * 16 + 0, asuint(float4(value, 1.0f)));
}

[numthreads(32, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
