// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/tube_h.comp - do not edit.
// glsl-sha256: 339b61e500e2c5cd12c225a795281d2de0fd3f12b2cbf2842be90aff81a55f10
// shaderc v2026.1 unknown hash; spirv-cross 1.4.363.0
// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md
static const uint3 gl_WorkGroupSize = uint3(32u, 8u, 1u);

ByteAddressBuffer _98 : register(t1);
ByteAddressBuffer _120 : register(t0);
RWByteAddressBuffer _148 : register(u2);
cbuffer TubeParams
{
    int P_width : packoffset(c0);
    int P_height : packoffset(c0.y);
    int P_ow : packoffset(c0.z);
    int P_oh : packoffset(c0.w);
    int P_xCount : packoffset(c1);
    int P_yCount : packoffset(c1.y);
    int P_gCount : packoffset(c1.z);
    int P_levels : packoffset(c1.w);
    float P_gain : packoffset(c2);
    float P_scatterFraction : packoffset(c2.y);
    float P_keep : packoffset(c2.z);
    int P_radius : packoffset(c2.w);
    int P_depth : packoffset(c3);
    int P_extra : packoffset(c3.y);
    int P_pad1 : packoffset(c3.z);
    int P_pad2 : packoffset(c3.w);
};


static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

void comp_main()
{
    uint2 g = gl_GlobalInvocationID.xy;
    bool _30 = int(g.x) >= P_ow;
    bool _43;
    if (!_30)
    {
        _43 = int(g.y) >= (P_height * 2);
    }
    else
    {
        _43 = _30;
    }
    if (_43)
    {
        return;
    }
    int px = int(g.x);
    int parity = int(g.y) / P_height;
    int y = int(g.y) % P_height;
    float3 sum = 0.0f.xxx;
    for (int c = 0; c < 3; c++)
    {
        for (int k = 0; k < P_xCount; k++)
        {
            float2 w = asfloat(_98.Load2((((((px * 6) + (c * 2)) + parity) * P_xCount) + k) * 8 + 0));
            precise float _136 = asfloat(_120.Load(((y * P_width) + int(w.x)) * 16 + c * 4 + 0)) * w.y;
            precise float _139 = sum[c] + _136;
            sum[c] = _139;
        }
    }
    _148.Store4(((int(g.y) * P_ow) + px) * 16 + 0, asuint(float4(sum, 1.0f)));
}

[numthreads(32, 8, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
