#!/usr/bin/env python3
"""Embeds a data file into the frontend core as a C byte array (any size, every compiler).

  embed_data.py <input> <out.inc> <symbol>

Writes `static const unsigned char <symbol>Data[] = {...}; static const size_t <symbol>Size = N;`.
"""
import sys


def main():
    src, out, sym = sys.argv[1:4]
    data = open(src, "rb").read()
    lines = []
    for i in range(0, len(data), 24):
        lines.append(",".join(str(b) for b in data[i:i + 24]))
    body = ",\n".join(lines) if data else "0"
    text = ("// Generated by frontend/tools/embed_data.py from %s. Do not edit.\n"
            "static const unsigned char %sData[] = {\n%s\n};\n"
            "static const size_t %sSize = %d;\n") % (src.replace("\\", "/").split("/")[-1], sym, body, sym, len(data))
    try:
        if open(out, encoding="utf-8").read() == text:
            return
    except OSError:
        pass
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


if __name__ == "__main__":
    main()
