#!/usr/bin/env python3
"""Generates the frontend core's localization table from the String Catalog.

apps/macos/Resources/Localizable.xcstrings stays the single source of truth for every UI string
(en = the key or its explicit "en" value, ja = the Japanese translation). This build step turns it
into a C++ table (sorted by key bytes, binary searched at run time) and, optionally, a JSON file
{"<key>": {"en": "...", "ja": "..."}} for tooling.

  gen_l10n.py <Localizable.xcstrings> <out.inc> [--json <out.json>]
"""
import json
import os
import sys


def unit_value(entry, lang):
    unit = entry.get("localizations", {}).get(lang, {}).get("stringUnit")
    if unit and unit.get("value"):
        return unit["value"]
    return None


def c_literal(s):
    out = ['"']
    for b in s.encode("utf-8"):
        c = chr(b)
        if 0x20 <= b < 0x7F and c not in '"\\?':
            out.append(c)
        else:
            out.append("\\%03o" % b)
    out.append('"')
    return "".join(out)


def main():
    args = sys.argv[1:]
    json_out = None
    if "--json" in args:
        i = args.index("--json")
        json_out = args[i + 1]
        del args[i:i + 2]
    if len(args) != 2:
        print(__doc__)
        return 2
    src, out = args
    cat = json.load(open(src, encoding="utf-8"))
    rows = []
    for key, entry in cat["strings"].items():
        en = unit_value(entry, "en") or key
        ja = unit_value(entry, "ja") or en
        rows.append((key, en, ja))
    rows.sort(key=lambda r: r[0].encode("utf-8"))
    lines = [
        "// Generated by frontend/tools/gen_l10n.py from apps/macos/Resources/Localizable.xcstrings.",
        "// Do not edit: change the String Catalog instead.",
        "static const rnf::L10nEntry kL10nTable[] = {",
    ]
    for key, en, ja in rows:
        lines.append("  {%s, %s, %s}," % (c_literal(key), c_literal(en), c_literal(ja)))
    lines.append("};")
    text = "\n".join(lines) + "\n"
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    # Rewrite only on change (keeps incremental builds incremental).
    if not os.path.exists(out) or open(out, encoding="utf-8").read() != text:
        with open(out, "w", encoding="utf-8") as f:
            f.write(text)
    if json_out:
        obj = {key: {"en": en, "ja": ja} for key, en, ja in rows}
        with open(json_out, "w", encoding="utf-8") as f:
            json.dump(obj, f, ensure_ascii=False, indent=1, sort_keys=True)
            f.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
