// Metal CRT port vs nesterm's CPU reference models (tests/fixtures/crt/reference.json, generated by
// tools/crt-reference/generate-fixtures.mjs). Inputs mirror that script's formulas exactly.
// No XCTest import: also usable from a command-line harness.
// SPDX-License-Identifier: GPL-2.0-or-later
import Foundation
import Metal

struct CRTConformance {
    struct Diff: CustomStringConvertible {
        var maxAbs = 0.0, meanAbs = 0.0, count = 0
        var description: String { String(format: "max %.3g mean %.3g (n=%d)", maxAbs, meanAbs, count) }
    }
    struct Case { let width: Int; let height: Int; let rows: [Int]; let data: [Float]; let meta: [String: Any] }

    let cases: [String: Case]
    let device: MTLDevice
    let queue: MTLCommandQueue

    static var fixtureURL: URL {
        URL(fileURLWithPath: #filePath).deletingLastPathComponent()
            .appendingPathComponent("../../../tests/fixtures/crt/reference.json").standardizedFileURL
    }

    init?(url: URL = CRTConformance.fixtureURL) {
        guard let device = MTLCreateSystemDefaultDevice(), let queue = device.makeCommandQueue(),
              let d = try? Data(contentsOf: url),
              let json = try? JSONSerialization.jsonObject(with: d) as? [String: Any],
              let cs = json["cases"] as? [String: [String: Any]] else { return nil }
        var out: [String: Case] = [:]
        for (name, c) in cs {
            var floats: [Float] = []
            if let b64 = c["data"] as? String, let raw = Data(base64Encoded: b64) {
                floats = raw.withUnsafeBytes { Array($0.bindMemory(to: Float.self)) }
            }
            out[name] = Case(width: c["width"] as? Int ?? 0, height: c["height"] as? Int ?? 0, rows: c["rows"] as? [Int] ?? [],
                             data: floats, meta: c)
        }
        cases = out
        self.device = device
        self.queue = queue
    }

    // MARK: inputs (mirror generate-fixtures.mjs)

    static let codes: [UInt16] = {
        let bars: [UInt16] = [0x30, 0x28, 0x2C, 0x2A, 0x24, 0x16, 0x12, 0x0F]
        var c = [UInt16](repeating: 0, count: 256 * 240)
        for y in 0..<240 { for x in 0..<256 {
            let v: Int
            if y < 100 { v = Int(bars[x >> 5]) }
            else if y < 150 { v = ((x >> 4) & 15) | ((((y - 100) / 13) & 3) << 4) }
            else if y < 200 { v = ((x >> 4) & 15) | (2 << 4) | ((((y - 150) / 7) & 7) << 6) }
            else { v = ((x >> 3) + (y >> 3)) % 2 == 0 ? 0x30 : 0x0F }
            c[y * 256 + x] = UInt16(v)
        } }
        return c
    }()

    /// variant 0: plain; 1: min(1, v + 0.5); 2: 1 - v; 3: v * 0.25 (double arithmetic like JS).
    static func drive(variant: Int = 0) -> [SIMD4<Float>] {
        var d = [SIMD4<Float>](repeating: SIMD4(0, 0, 0, 1), count: 512 * 240)
        for y in 0..<240 { for x in 0..<512 { for c in 0..<3 {
            var v: Double
            if x < 128 { v = Double((x + 3 * y + 50 * c) % 200) / 199 }
            else if x < 256 { v = ((x >> 4) + y / 30 + c) % 3 == 0 ? 1 : 0.05 * Double(c) }
            else if x < 384 { v = ((x >> 1) + y) % 2 != 0 ? 0.8 : 0 }
            else { v = Double((x * 37 + y * 101 + c * 53) % 1000) / 999 }
            switch variant {
            case 1: v = min(1, v + 0.5)
            case 2: v = 1 - v
            case 3: v = v * 0.25
            default: break
            }
            d[y * 512 + x][c] = Float(v)
        } } }
        return d
    }

    /// Black drive. ReplayNES starts the temporal state from the first picture held (supply steady
    /// state, persistence history filled with it); nesterm's reference starts from an idle tube and
    /// an empty history, which is exactly a black frame held before the sequence.
    static let black = [SIMD4<Float>](repeating: SIMD4(0, 0, 0, 1), count: 512 * 240)

    // MARK: running the port

    /// The conformance checks run the reference path (the 1:1 port); the fast path is checked
    /// against it (fastVsReference).
    func renderer(_ s: CRTRenderer.Settings, ow: Int = 256, oh: Int = 192, quality: CRTRenderer.Quality = .reference) throws -> CRTRenderer {
        let r = try CRTRenderer(device: device, targetPixelFormat: nil)
        r.quality = quality
        r.configure(settings: s, outputWidth: ow, outputHeight: oh, synchronous: true)
        return r
    }

    func run(_ r: CRTRenderer, _ input: CRTRenderer.Input, ordinal: UInt64) {
        let cb = queue.makeCommandBuffer()!
        r.encode(input, ordinal: ordinal, into: cb)
        cb.commit()
        cb.waitUntilCompleted()
    }

    func compare(_ name: String, _ got: [SIMD4<Float>], width: Int) -> Diff {
        guard let c = cases[name] else { return Diff(maxAbs: .infinity) }
        var diff = Diff()
        var sum = 0.0
        for (i, y) in c.rows.enumerated() { for x in 0..<c.width { for ch in 0..<3 {
            let ref = Double(c.data[(i * c.width + x) * 3 + ch]), v = Double(got[y * width + x][ch])
            let e = abs(ref - v)
            diff.maxAbs = max(diff.maxAbs, e.isNaN ? .infinity : e); sum += e; diff.count += 1
        } } }
        diff.meanAbs = sum / Double(max(1, diff.count))
        return diff
    }

    static let off = CRTRenderer.Settings(lines: 240, beamGrowth: false, persistence: false, supply: false)

    func receiver(noise: Bool) throws -> Diff {
        var s = Self.off
        if noise { s.antennaDbuv = 30 }
        let r = try renderer(s)
        r.noiseEnabled = noise
        Self.codes.withUnsafeBufferPointer { run(r, .codes($0.baseAddress!, burstPhase: 1), ordinal: 7) }
        return compare(noise ? "receiverNoise" : "receiver", r.read(.receiver), width: 512)
    }

    func tube(growth: Bool) throws -> Diff {
        var s = Self.off
        s.beamGrowth = growth
        let r = try renderer(s)
        r.disableSpotH = true
        Self.drive().withUnsafeBufferPointer { run(r, .drive($0.baseAddress!), ordinal: 1) }
        return compare(growth ? "tubeGrowth" : "tube", r.read(.output), width: 256)
    }

    func raster160() throws -> Diff {
        var s = Self.off
        s.lines = 160
        let r = try renderer(s)
        Self.drive().withUnsafeBufferPointer { run(r, .drive($0.baseAddress!), ordinal: 1) }
        return compare("raster160", r.read(.tubeInput), width: 512)
    }

    func supply() throws -> Diff {
        var s = Self.off
        s.supply = true
        let r = try renderer(s)
        Self.black.withUnsafeBufferPointer { run(r, .drive($0.baseAddress!), ordinal: 0) }  // nesterm's idle start
        for f in 0..<3 { Self.drive(variant: f == 1 ? 1 : 0).withUnsafeBufferPointer { run(r, .drive($0.baseAddress!), ordinal: UInt64(f + 1)) } }
        return compare("supply", r.read(.tubeInput), width: 512)
    }

    func spotH() throws -> Diff {
        var s = Self.off
        s.beamGrowth = true
        let r = try renderer(s)
        Self.drive().withUnsafeBufferPointer { run(r, .drive($0.baseAddress!), ordinal: 1) }
        return compare("spotH", r.read(.tubeInput), width: 512)
    }

    func persistence() throws -> Diff {
        var s = Self.off
        s.persistence = true
        let r = try renderer(s)
        Self.black.withUnsafeBufferPointer { run(r, .drive($0.baseAddress!), ordinal: 9) }  // nesterm's empty history
        for f in 0..<3 {
            Self.drive(variant: f == 0 ? 2 : f == 1 ? 3 : 0).withUnsafeBufferPointer { run(r, .drive($0.baseAddress!), ordinal: UInt64(10 + f)) }
        }
        return compare("persistence", r.read(.output), width: 256)
    }

    /// A still after a discontinuity (seek / rewind / load: a non-increasing ordinal) vs the same
    /// picture shown in continuous play, all effects on, noise off. `phases`: burst phase per
    /// sequence frame (the still uses the last one). Returns (max abs diff, worst per-channel mean
    /// difference) of the tube output; a fresh renderer's first frame is checked the same way.
    func stillAfterSeek(phases: [UInt32], quality: CRTRenderer.Quality = .reference) throws -> (maxAbs: Double, meanAbs: Double) {
        func mean(_ a: [SIMD4<Float>]) -> SIMD3<Double> {
            var m = SIMD3<Double>(0, 0, 0)
            for v in a { m += SIMD3(Double(v.x), Double(v.y), Double(v.z)) }
            return m / Double(max(1, a.count))
        }
        func diff(_ a: [SIMD4<Float>], _ b: [SIMD4<Float>]) -> (Double, Double) {
            guard a.count == b.count, !a.isEmpty else { return (.infinity, .infinity) }
            var m = 0.0
            for i in 0..<a.count { for c in 0..<3 { let e = Double(abs(a[i][c] - b[i][c])); m = max(m, e.isNaN ? .infinity : e) } }
            let ma = mean(a), mb = mean(b), d = SIMD3<Double>(Swift.abs(ma.x - mb.x), Swift.abs(ma.y - mb.y), Swift.abs(ma.z - mb.z))
            return (m, max(d.x, d.y, d.z))
        }
        let last = UInt64(phases.count)
        let r = try renderer(CRTRenderer.Settings(), quality: quality)
        r.noiseEnabled = false
        for (i, b) in phases.enumerated() { Self.codes.withUnsafeBufferPointer { run(r, .codes($0.baseAddress!, burstPhase: b), ordinal: UInt64(i + 1)) } }
        let played = r.read(.output)
        Self.codes.withUnsafeBufferPointer { run(r, .codes($0.baseAddress!, burstPhase: phases.last!), ordinal: last) }  // seek back
        let afterSeek = r.read(.output)
        let fresh = try renderer(CRTRenderer.Settings(), quality: quality)
        fresh.noiseEnabled = false
        Self.codes.withUnsafeBufferPointer { run(fresh, .codes($0.baseAddress!, burstPhase: phases.last!), ordinal: last) }
        let (m1, a1) = diff(played, afterSeek), (m2, a2) = diff(played, fresh.read(.output))
        return (max(m1, m2), max(a1, a2))
    }

    /// The restructured kernels (threadgroup FFT, register-window scatter) produce the same bits as
    /// the 1:1 multi-pass port of the WebGL shaders.
    func fastPathsMatchDirectPort() throws -> Bool {
        var outs: [[SIMD4<Float>]] = []
        for fast in [false, true] {
            let r = try renderer(CRTRenderer.Settings())
            r.useFastFFT = fast
            r.useFastScatter = fast
            for f in 0..<3 { Self.codes.withUnsafeBufferPointer { run(r, .codes($0.baseAddress!, burstPhase: UInt32(f % 3)), ordinal: UInt64(f)) } }
            outs.append(r.read(.receiver) + r.read(.output))
        }
        return outs[0] == outs[1] && !outs[0].isEmpty
    }

    /// Two fresh renderers fed the same frame sequence produce bit-identical output.
    func deterministic(quality: CRTRenderer.Quality = .reference) throws -> Bool {
        let s = CRTRenderer.Settings()
        var outs: [[SIMD4<Float>]] = []
        for _ in 0..<2 {
            let r = try renderer(s, quality: quality)
            for f in 0..<4 { Self.codes.withUnsafeBufferPointer { run(r, .codes($0.baseAddress!, burstPhase: UInt32(f % 3)), ordinal: UInt64(f)) } }
            outs.append(r.read(.output))
        }
        return outs[0] == outs[1] && !outs[0].isEmpty
    }

    // MARK: fast path (CRTRenderer.Quality.fast)

    /// Moving test picture: the fixture codes scrolled `f` pixels (and the burst phase advanced)
    /// per frame, so persistence, AGC, supply and the RF artefacts all change between frames.
    static func movingCodes(_ f: Int) -> [UInt16] {
        var c = [UInt16](repeating: 0, count: 256 * 240)
        for y in 0..<240 { for x in 0..<256 { c[y * 256 + x] = codes[y * 256 + (x + 3 * f) % 256] } }
        return c
    }

    struct Quality: CustomStringConvertible {
        var psnr = Double.infinity, maxAbs = 0.0, meanAbs = 0.0
        var description: String { String(format: "PSNR %.1f dB, max %.3g, mean %.3g", psnr, maxAbs, meanAbs) }
    }

    /// The fast path against the reference on the same moving sequence: the worst frame's PSNR of
    /// the displayed (sRGB-encoded, clamped) tube picture over the last `checked` frames.
    func fastVsReference(_ s: CRTRenderer.Settings = CRTRenderer.Settings(), ow: Int = 320, oh: Int = 240, frames: Int = 10,
                         checked: Int = 4, rgb: Bool = false) throws -> Quality {
        let rs = [try renderer(s, ow: ow, oh: oh, quality: .reference), try renderer(s, ow: ow, oh: oh, quality: .fast)]
        func encode(_ v: Float) -> Double {
            let x = Double(min(max(v, 0), 1))
            return x <= 0.0031308 ? 12.92 * x : 1.055 * pow(x, 1 / 2.4) - 0.055
        }
        var q = Quality()
        for f in 0..<frames {
            let c = Self.movingCodes(f)
            var outs: [[SIMD4<Float>]] = []
            for r in rs {
                if rgb {
                    let px = c.map { UInt32(0xFF00_0000) | UInt32($0 & 0x3F) * 0x0004_0201 }
                    px.withUnsafeBufferPointer { run(r, .rgb($0.baseAddress!), ordinal: UInt64(f + 1)) }
                } else {
                    c.withUnsafeBufferPointer { run(r, .codes($0.baseAddress!, burstPhase: UInt32(f % 3)), ordinal: UInt64(f + 1)) }
                }
                if f >= frames - checked { outs.append(r.read(.output)) }
            }
            guard outs.count == 2 else { continue }
            guard outs[0].count == ow * oh, outs[1].count == ow * oh else { return Quality(psnr: -.infinity) }
            var se = 0.0, sum = 0.0, mx = 0.0
            for i in 0..<(ow * oh) { for ch in 0..<3 {
                let d = abs(encode(outs[0][i][ch]) - encode(outs[1][i][ch]))
                se += d * d; sum += d; mx = max(mx, d.isNaN ? .infinity : d)
            } }
            let n = Double(ow * oh * 3)
            q.psnr = min(q.psnr, se > 0 ? 10 * log10(n / se) : 200)
            q.maxAbs = max(q.maxAbs, mx); q.meanAbs = max(q.meanAbs, sum / n)
        }
        return q
    }
}
