#!/bin/bash
# Regenerates the Direct3D 11 CRT shaders (apps/windows/shaders/crt/*.hlsl) from the Vulkan GLSL
# sources (apps/linux/shaders/crt), which stay the single source of the CRT kernels on Windows and
# Linux (docs/CRT_PORT.md, docs/WINDOWS.md):
#   GLSL --glslc--> SPIR-V --spirv-cross --hlsl --shader-model 50--> HLSL (CS/VS/PS 5.0)
# The HLSL is committed and compiled at run time by D3DCompile (d3dcompiler_47.dll, part of
# Windows 10/11), so a Windows build needs neither tool. `precise` (NoContraction) survives the
# translation; storage buffers become (RW)ByteAddressBuffer at t<binding> / u<binding>, the push
# constants a cbuffer (b0).
# Each file records the SHA-256 of its GLSL inputs; `--check` (CI, needs only shasum) fails when
# a GLSL source changed without regenerating.
#   scripts/generate-crt-hlsl.sh           regenerate (needs glslc + spirv-cross: brew install shaderc spirv-cross)
#   scripts/generate-crt-hlsl.sh --check   verify the recorded source hashes
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/apps/linux/shaders/crt"
OUT="$ROOT/apps/windows/shaders/crt"
SHADERS="rf_forward_tg.comp rf_inverse_tg.comp rf_init_codes.comp rf_butterfly2.comp rf_butterfly.comp rf_multiply.comp
  rf_extract.comp rx_reduce.comp rx_agc.comp rx_prepare.comp rx_decode.comp raster_area.comp supply_mean.comp
  supply_row.comp supply_state.comp supply_resample.comp spot_h.comp tube_h.comp tube_v.comp tube_v_growth.comp
  tube_scatter.comp tube_scatter_x16.comp tube_scatter_y16.comp tube_mix.comp tube_lit.comp tube_persist.comp
  show_kernel.comp tube_scatter_tx.comp tube_h_rows.comp tube_lit_persist.comp show.vert show.frag
  rf_fast.comp rx_stats_fast.comp rx_agc_fast.comp rx_decode_fast.comp row_mean_fast.comp supply_fast.comp drive_post_fast.comp
  scatter_drive.comp tube_h_fast.comp tube_v_fast.comp show_kernel_h.comp show_h.frag"

# Hash of a shader's inputs: the file itself + every file it includes (recursively).
includes() { grep -ho '#include "[^"]*"' "$SRC/$1" | cut -d'"' -f2 | while read -r i; do echo "$i"; includes "$i"; done; }
source_hash() { (cd "$SRC" && cat "$1" $(includes "$1" | sort -u)) | shasum -a 256 | cut -c1-64; }
outname() { echo "$1" | sed 's/\.comp$//; s/\.vert$/_vert/; s/\.frag$/_frag/'; }

if [ "${1:-}" = "--check" ]; then
  bad=0
  for s in $SHADERS; do
    o="$OUT/$(outname "$s").hlsl"
    want="$(source_hash "$s")"
    got="$(sed -n 's|^// glsl-sha256: \([0-9a-f]*\)$|\1|p' "$o" 2>/dev/null | head -1)"
    [ "$want" = "$got" ] || { echo "stale: $(basename "$o") (GLSL $s changed; run scripts/generate-crt-hlsl.sh)"; bad=1; }
  done
  [ $bad = 0 ] && echo "CRT HLSL up to date ($(echo $SHADERS | wc -w | tr -d ' ') shaders)"
  exit $bad
fi

command -v glslc >/dev/null || { echo "glslc missing (brew install shaderc)"; exit 1; }
command -v spirv-cross >/dev/null || { echo "spirv-cross missing (brew install spirv-cross)"; exit 1; }
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
mkdir -p "$OUT"
TOOLS="$(glslc --version | head -1 | cut -d, -f1); spirv-cross $(brew list --versions spirv-cross 2>/dev/null | cut -d" " -f2 || true)"
for s in $SHADERS; do
  n="$(outname "$s")"
  glslc --target-env=vulkan1.1 -I "$SRC" -o "$TMP/$n.spv" "$SRC/$s"
  extra=()
  case "$s" in *.vert) extra=(--flip-vert-y) ;; esac  # Vulkan clip y points down, Direct3D's up
  spirv-cross "$TMP/$n.spv" --hlsl --shader-model 50 ${extra[@]+"${extra[@]}"} --output "$TMP/$n.hlsl"
  {
    echo "// GENERATED by scripts/generate-crt-hlsl.sh from apps/linux/shaders/crt/$s - do not edit."
    echo "// glsl-sha256: $(source_hash "$s")"
    echo "// $TOOLS"
    echo "// SPDX-License-Identifier: GPL-2.0-or-later (port); original MIT, see THIRD_PARTY_NOTICES.md"
    cat "$TMP/$n.hlsl"
  } > "$OUT/$n.hlsl"
done
echo "wrote $(echo $SHADERS | wc -w | tr -d ' ') shaders to ${OUT#$ROOT/}"
