# Writes OUT (C++) with the bytes of the icon fonts (apps/desktop/src/icons.cpp reads them):
#   cmake -DDIR=<this dir> -DOUT=<file.cpp> -P embed_fonts.cmake
function(rnl_embed var file out)
  file(READ ${file} hex HEX)
  string(LENGTH "${hex}" n)
  math(EXPR bytes "${n} / 2")
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," body "${hex}")
  # Break the initializer into lines (compilers have line length limits).
  string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)" "\\1\n" body "${body}")
  file(APPEND ${out} "extern const unsigned char ${var}[] = {\n${body}};\nextern const unsigned int ${var}_size = ${bytes};\n")
endfunction()

file(WRITE ${OUT} "// Generated by apps/desktop/resources/fonts/embed_fonts.cmake: Tabler Icons subsets (MIT).\n")
rnl_embed(rnl_icon_font ${DIR}/tabler-subset.ttf ${OUT})
rnl_embed(rnl_icon_font_filled ${DIR}/tabler-subset-filled.ttf ${OUT})
