#!/usr/bin/env python3
"""Builds the desktop UI's icon font: a subset of Tabler Icons (MIT, https://tabler.io/icons) with only
the glyphs the UI uses, plus icons.inc (name -> code point) for apps/desktop/src/icons.h.

  make_icon_font.py <tabler-icons-webfont dir (dist/)> <out dir>

The input is the npm package @tabler/icons-webfont (dist/fonts/tabler-icons-outline.ttf,
dist/fonts/tabler-icons-filled.ttf, dist/tabler-icons.css); needs fontTools (pip install fonttools).
The result (tabler-subset.ttf, icons.inc) is committed; rerun after adding a name to ICONS.
"""
import os
import re
import sys

ICONS = [
    # Quick Menu / pages (frontend/src/menu.cpp)
    "menu-2", "history", "git-branch", "bookmark", "target", "share", "settings", "device-desktop",
    "device-gamepad", "device-gamepad-2", "volume", "volume-2", "adjustments-horizontal", "adjustments",
    "device-tv-old", "keyboard", "download", "info-circle", "folder", "folder-open", "player-play",
    "player-record", "arrow-back-up", "eye", "movie", "broadcast", "maximize", "aspect-ratio", "bolt-off",
    "bolt", "crop", "line-height", "sun-low", "antenna", "restore", "arrows-horizontal", "player-pause",
    "clock", "arrows-diff", "language", "brand-steam", "power", "refresh", "file-text", "license",
    "text-size", "chart-line", "layout-grid", "device-floppy", "file-plus", "baseline-density-medium",
    "line-scan", "device-gamepad-3",
    # UI chrome
    "chevron-right", "chevron-left", "plus", "search", "x", "check", "photo", "trash", "pencil", "flag",
    "repeat", "player-stop", "player-track-next", "player-track-prev", "player-skip-back",
    "player-skip-forward", "alert-triangle", "folder-plus", "list", "rewind-backward-5",
    "rewind-forward-5", "circle-check", "lock",
    # filled variants
    "player-play-filled", "player-pause-filled", "player-record-filled", "bookmark-filled",
    "star-filled", "circle-filled",
]


def main():
    src, out = sys.argv[1], sys.argv[2]
    from fontTools import subset
    from fontTools.ttLib import TTFont

    css = open(os.path.join(src, "tabler-icons.css"), encoding="utf-8").read()
    codes = {m.group(1): int(m.group(2), 16) for m in re.finditer(r"\.ti-([a-z0-9-]+):before\s*\{\s*content:\s*\"\\([0-9a-f]+)\"", css)}
    missing = [n for n in ICONS if n not in codes]
    if missing:
        sys.exit("unknown icons: " + ", ".join(missing))
    outline = TTFont(os.path.join(src, "fonts", "tabler-icons-outline.ttf"))
    filled = TTFont(os.path.join(src, "fonts", "tabler-icons-filled.ttf"))
    want_o = sorted(codes[n] for n in ICONS if not n.endswith("-filled"))
    want_f = sorted(codes[n] for n in ICONS if n.endswith("-filled"))
    cmap_o, cmap_f = outline.getBestCmap(), filled.getBestCmap()
    absent = [hex(c) for c in want_o if c not in cmap_o] + [hex(c) for c in want_f if c not in cmap_f]
    if absent:
        sys.exit("code points missing from the fonts: " + ", ".join(absent))
    os.makedirs(out, exist_ok=True)
    opts = subset.Options()
    opts.layout_features = []
    opts.name_IDs = ["*"]
    opts.notdef_outline = True
    for font, want, name in ((outline, want_o, "tabler-subset.ttf"), (filled, want_f, "tabler-subset-filled.ttf")):
        s = subset.Subsetter(opts)
        s.populate(unicodes=want)
        s.subset(font)
        font.save(os.path.join(out, name))
    with open(os.path.join(out, "icons.inc"), "w", encoding="utf-8") as f:
        f.write("// Generated by make_icon_font.py: Tabler Icons name -> code point (subset fonts next to it).\n")
        for n in ICONS:
            f.write('{"%s", 0x%04x},\n' % (n, codes[n]))
    print("icons: %d outline, %d filled" % (len(want_o), len(want_f)))


if __name__ == "__main__":
    main()
