# Embeds the generated CRT HLSL (apps/windows/shaders/crt/*.hlsl) into a C++ include file:
#   cmake -DDIR=<shader dir> -DOUT=<file.inc> -P cmake/embed_hlsl.cmake
# Output: one char array per shader (NUL-terminated) and kCrtHlsl[] = {name, source, length}.
# Hex arrays, so no compiler string-literal length limit applies (MSVC: 16 KB per literal).
file(GLOB files "${DIR}/*.hlsl")
list(SORT files)
set(body "// Generated by cmake/embed_hlsl.cmake from ${DIR} - do not edit.\n")
set(table "")
foreach(f ${files})
  get_filename_component(name ${f} NAME_WE)
  file(READ ${f} hex HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex "${hex}")
  string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)" "\\1\n" hex "${hex}")
  string(APPEND body "static const char kHlsl_${name}[] = {\n${hex}0};\n")
  string(APPEND table "  {\"${name}\", kHlsl_${name}, sizeof(kHlsl_${name}) - 1},\n")
endforeach()
string(APPEND body "struct CrtHlslSource { const char* name; const char* text; unsigned long size; };\n")
string(APPEND body "static const CrtHlslSource kCrtHlsl[] = {\n${table}};\n")
file(WRITE "${OUT}.tmp" "${body}")
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${OUT}.tmp" "${OUT}")
file(REMOVE "${OUT}.tmp")
