#!/usr/bin/env python3
# SPDX-License-Identifier: CC0-1.0
"""Builds the ReplayNES Test Cartridge from source (no third-party tools).

  build.py                 regenerate engine/src/testrom/TestCartridge.inc
  build.py --check         exit 1 if the committed TestCartridge.inc differs from the source
  build.py --nes out.nes   also write the ROM image (for other emulators / real hardware)
  build.py -D NAME=value   override an assembler constant (timing experiments)

Output: iNES, mapper 0 (NROM-128), 16 KiB PRG at $C000 + 8 KiB CHR, vertical mirroring.
"""
import argparse
import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
INC = os.path.join(ROOT, 'engine', 'src', 'testrom', 'TestCartridge.inc')
SYMS = os.path.join(ROOT, 'engine', 'src', 'testrom', 'TestCartridgeSyms.inc')
sys.path.insert(0, HERE)

import asm6502  # noqa: E402
import chr as chrgen  # noqa: E402

# Symbols the engine tests read (RAM addresses of the rapid-fire meter, screen ids).
EXPORTS = ['screen', 'mp_frame', 'big', 'm_cnt_lo', 'm_cnt_hi', 'm_ecnt_lo', 'm_ecnt_hi', 'm_peakp',
           'm_peake', 'm_minpp', 'm_lhold', 'm_lgap', 'm_hist_lo', 'm_hist_hi', 'r_rate_lo', 'r_rate_hi',
           'r_ppavg_lo', 'r_ppavg_hi', 'r_ppsd_lo', 'r_ppsd_hi', 'r_rravg_lo', 'r_rravg_hi',
           'r_rrsd_lo', 'r_rrsd_hi', 'r_hdavg_lo', 'r_hdavg_hi', 'r_gpavg_lo', 'r_gpavg_hi',
           'r_duty', 't_per', 't_hold', 't_gap', 't_duty', 't_min', 't_max', 'm_mode', 'best_a',
           'best_e', 'SCR_TITLE', 'SCR_PALETTE', 'SCR_BARS', 'SCR_SPRITES', 'SCR_SCROLL', 'SCR_PADS',
           'SCR_METER', 'SCR_SOUND']


def build(defines=None):
    chr_data, tile_syms = chrgen.build()
    a = asm6502.Assembler(fill=0xFF)
    out, syms, _ = a.assemble(os.path.join(HERE, 'testcart.s'), predefined=tile_syms, overrides=defines)
    prg = asm6502.image(out, 0xC000, 0x10000)
    header = bytes([0x4E, 0x45, 0x53, 0x1A, 1, 1, 0x01, 0x00, 0, 0, 0, 0, 0, 0, 0, 0])
    rom = header + prg + chr_data
    used = len(out)
    return rom, syms, used


def inc_text(rom, syms):
    sha = hashlib.sha256(rom).hexdigest()
    lines = [
        '// ReplayNES Test Cartridge ROM image - GENERATED by tools/testcart/build.py from',
        '// tools/testcart/*.s, chr.py and font.txt. Do not edit; run the script instead.',
        '// SPDX-License-Identifier: CC0-1.0',
        '// sha256 %s' % sha,
        'static const unsigned char kTestCartridgeRom[%d] = {' % len(rom),
    ]
    for i in range(0, len(rom), 24):
        lines.append('    ' + ','.join(str(b) for b in rom[i:i + 24]) + ',')
    lines.append('};')
    return '\n'.join(lines) + '\n'


def syms_text(syms):
    lines = ['// ReplayNES Test Cartridge symbols - GENERATED by tools/testcart/build.py. Do not edit.',
             '// SPDX-License-Identifier: CC0-1.0',
             '// CPU RAM addresses and screen numbers (tests read the rapid-fire meter from RAM).']
    for name in EXPORTS:
        lines.append('constexpr unsigned %s = 0x%04X;' % (name, syms[name]))
    return '\n'.join(lines) + '\n'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--nes')
    ap.add_argument('--no-inc', action='store_true')
    ap.add_argument('--syms', help='write all labels (address order) for debugging')
    ap.add_argument('-D', action='append', default=[])
    args = ap.parse_args()
    defines = {}
    for d in args.D:
        k, v = d.split('=')
        defines[k] = int(v, 0)
    rom, syms, used = build(defines)
    outputs = {INC: inc_text(rom, syms), SYMS: syms_text(syms)}
    if args.syms:
        with open(args.syms, 'w') as f:
            for k, v in sorted(syms.items(), key=lambda kv: kv[1]):
                if v >= 0x8000:
                    f.write('%04X %s\n' % (v, k))
    if args.nes:
        with open(args.nes, 'wb') as f:
            f.write(rom)
    if args.check:
        for path, text in outputs.items():
            try:
                with open(path, encoding='utf-8') as f:
                    cur = f.read()
            except OSError:
                cur = ''
            if cur != text:
                print('%s is out of date: run tools/testcart/build.py' % os.path.relpath(path, ROOT),
                      file=sys.stderr)
                return 1
        print('TestCartridge.inc matches the source (%d PRG bytes used)' % used)
        return 0
    if not args.no_inc and not defines:
        for path, text in outputs.items():
            with open(path, 'w', encoding='utf-8', newline='\n') as f:
                f.write(text)
    print('built: %d PRG bytes used of 16384, sha256 %s' % (used, hashlib.sha256(rom).hexdigest()))
    return 0


if __name__ == '__main__':
    sys.exit(main())
